### ISSUE TITLE
Create and send out call for volunteers

### ISSUE THREAD

**Issue by desilinguist** [acl-org/acl-2020-virtual-conference#1]
- [x] Create a call for 8-10 volunteers well-versed in CSS/JS/Python/Flask web apps.
- [x] Post call on ACl 2020 website
- [x] Coordinate with Emily Bender (ACL 2020 publicity chair) to publicize the call on social media and with Priscilla  Rasmussen to send to all ACL members.
- [x] Go through volunteer info and pick volunteers.

**Comment by hao-fang** [comment]
This is done in our meeting today.
