### ISSUE TITLE
[RocketChat] Customize the Home page message

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#101]
**Number of Volunteers: 2**

Need to check with Dan & PCs about the message.

![image](https://user-images.githubusercontent.com/9957482/84973758-b71f6780-b0d6-11ea-818a-50518444694a.png)

The RocketChat admin page looks like below, i.e., we will need to use HTML to customize the body.
![image](https://user-images.githubusercontent.com/9957482/85322988-189b5980-b47c-11ea-8383-706549521932.png)

**Comment by hao-fang** [comment]
We should put the list of channels on the Home Page, e.g.,
* announcements, firsttimers, ...
* workshop-xxx
* tutorial-xxx
* sponsor-xxx
* keynote-xxx

**Comment by hao-fang** [comment]
We should also put the CodeOfConduct and etc. on the Home page for visibility.

**Comment by vladdy** [comment]
@hao-fang I could do this. Do we have a list of channels somewhere already?

**Comment by hao-fang** [comment]
@vladdy We are collecting the information https://docs.google.com/spreadsheets/d/1S3u6Q401kDyyqXL1SEPBOIHawqHDEUN4F-B0KxOraLQ/edit?usp=sharing

Once it is ready, we can see how we should advertise these channels. I think the issue is with ~800 channels for papers, the user will not be able to browse all the channels and decide which one to join.
Let me know if you have any thoughts.

**Comment by vladdy** [comment]
I wonder if we could create links to the channels from the pages with article info, but on the other hand 800 channels appears to be something hard to manage. Do you have any thoughts about that?

In the meantime let me know if there is something I need to do.

**Comment by hao-fang** [comment]
> I wonder if we could create links to the channels from the pages with article info, but on the other hand 800 channels appears to be something hard to manage. Do you have any thoughts about that?

Our webpage for a paper looks like this. (You can go to virtual.acl2020.org to see what it looks like currently as well). The user will join the channel for the specific paper on the webpage.
![image](https://user-images.githubusercontent.com/9957482/85635488-d2d4c180-b632-11ea-9dc9-e9e7941ec750.png)

So we probably only need to list channels that do not have an entry point on the webpages, which would be things like helpdesk, firsttimers, etc.

> In the meantime let me know if there is something I need to do.

I think the top priority on your plate is #55 .

**Comment by anaerobeth** [comment]
I created a shared doc here https://docs.google.com/document/d/1lNx8wbkDlAmm-P8g9vVGKH15NWRGNifFwLt2TO0MYEc/edit and have started listing relevant channels from the ACL2020 RocketChat doc.

**Comment by hao-fang** [comment]
@anaerobeth Thanks a lot! Let me know when you have a draft and I'll send it over to the committee to review.

**Comment by anaerobeth** [comment]
@hao-fang @vladdy I added some information and comments to the shared doc. Let me know if I missed anything.

**Comment by hao-fang** [comment]
@anaerobeth -- Thanks! I'll get back to you in a few days. Need to sort out some other things first.

**Comment by hao-fang** [comment]
@anaerobeth Thanks a lot for working on this. Unfortunately I don't have enough time to update it in the RocketChat.
So I simply turned off the `Show "Home Button"` option.
Sorry about missing this.. and you have made a lot of other great contributions to our website!
