### ISSUE TITLE
[AWS] verify all user emails to make sure they can reset passwords

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#118]
I'll do it and document the command.
I should also update the bash script.

**Comment by hao-fang** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cognito-idp.html

**Comment by hao-fang** [comment]
See #122

**Comment by hao-fang** [comment]
@stupid-2020 Can you do this for all current users in our pool? Currently I'm using this bash script for adhoc requests. https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/awscognito/verify_user_email.sh

**Comment by stupid-2020** [comment]
ok.
