### ISSUE TITLE
Fix workshops page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#124]
**Number of Volunteers: 1**

**NOTE**: Check with @kaushal0494 first since he is working on #21. 

Currently it looks like below.
![image](https://user-images.githubusercontent.com/9957482/85104169-ec9e8080-b1bc-11ea-91de-42e0ebf9cc35.png)

We should make each box roughly at the same size. Probably we need to replace the text with a blurb. If so, we need to ask workshop organizers to provide such information.

ICLR version: https://iclr.cc/virtual_2020/workshops.html
![image](https://user-images.githubusercontent.com/9957482/85104206-05a73180-b1bd-11ea-8afa-3f55e355088d.png)

**Comment by raosudha89** [comment]
@hao-fang  What if we don't include the blurb (description) instead just have the title and the list of organizers? I did that for tutorials page https://virtual.acl2020.org/tutorials.html 

I think at this point asking workshop organizers for a shorter text is going to take additional time. And anyways, it is just a matter of someone clicking on the link. They can then view the description in the individual workshop page.

**Comment by hao-fang** [comment]
@raosudha89 Sure. Let's do the simple version.

**Comment by raosudha89** [comment]
Sounds good. I will work on this.

**Comment by raosudha89** [comment]
Done and created a PR for this https://github.com/acl-org/acl-2020-virtual-conference/pull/130
