### ISSUE TITLE
Improve Workshops & Socials pages

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#135]
Use the same size for all boxes.
Also, the font seems to be a small and different from other top-level pages. Please fix.

![image](https://user-images.githubusercontent.com/9957482/85190732-2c727000-b270-11ea-8fb0-cfb496f28826.png)

![image](https://user-images.githubusercontent.com/9957482/85190754-56c42d80-b270-11ea-9608-053ec3c455a1.png)

**Comment by raosudha89** [comment]
I created a PR for making all workshop blocks of equal height: https://github.com/acl-org/acl-2020-virtual-conference/pull/147

**Comment by tlikhit** [comment]
I switched a few things up and fixed the socials and workshop pages: #149
