### ISSUE TITLE
Extract images from SRW and demo papers

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#136]
- [x] Ask SRW chair to get the PDFs
- [ ] Ask Demo chairs to get the PDFs
- [ ] Extract images and add them to the repo

**Comment by hao-fang** [comment]
@prabhat1081 We have added PDF urls in the `sitedata_acl2020/demo_papers.csv` and `sitedata_acl2020/srw_papers.csv`. Will you be able to extract images for those two files?
I think the SRW chair has also send the PDF via email. Not sure which one is easy.
If you need the demo PDFs in an email, I can ask the demo chairs to provide it.

**Comment by prabhat1081** [comment]
Thanks @hao-fang. I have added the images for SRW papers in #176. I will use the links in demo_papers.csv to get the pdfs and add images.
