### ISSUE TITLE
Figure out the right way to embed SlidesLive videos on the Home page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#137]
**Number of Volunteers: 1**

See https://github.com/acl-org/acl-2020-virtual-conference/issues/19#issuecomment-646242274 for more details

**Comment by sgdgp** [comment]
working on this

**Comment by sgdgp** [comment]
Created a PR. I changed the div id for the second video and called the same (new) div id from the javascript to embed the video.
