### ISSUE TITLE
Figure out a better way to display the Track of a paper

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#139]
**Number of Volunteers: 1**

There may have two colons when displaying the track. 
![image](https://user-images.githubusercontent.com/9957482/85193715-f63cec80-b27f-11ea-820c-3dd5c94c36f3.png)

Is there a better way to display the information?
Also we may want to make the track as a clickable link, but it depends on how we implement #30 .

**Comment by vladdy** [comment]
@hao-fang What do you think about putting the track above the title in a form like:

Track "Semantics: Textual Inference and Other Areas of Semantics"

It probably could be made italic as well.

**Comment by hao-fang** [comment]
@vladdy Thanks for the suggestion! (cc @salma-elanigri since he is working on #126 
I think at this moment, the right solution is to make the track clickable. With #167 we will have a HTML page for each track.

**Comment by hao-fang** [comment]
The current page looks like below
![image](https://user-images.githubusercontent.com/9957482/85367938-174f4880-b4df-11ea-9773-66f541f891c1.png)


We will just need to make the track `Semantics: Sentence Level` a clickable button to ``track_{{ track_name }}.html` (e.g., `track_Semantics:%20Textual%20Inference%20and%20Other%20Areas%20of%20Semantics.html`).
