### ISSUE TITLE
update `poster_schedule.yml` for SRW papers 

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#141]
This PR https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/31 only adds the papers. Still needs to add the slots to the schedule.

**Comment by ardakdemir** [comment]
Sure!

**Comment by hao-fang** [comment]
ah... sorry I forgot we already have an issue here. I have created a new one #172 so I'm going to close this.
