### ISSUE TITLE
Add PDF links to ACL Anthology

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#157]
**Number of Volunteers: 1--2**

ACL2020 proceedings are now live at https://www.aclweb.org/anthology/events/acl-2020/
We should add PDF links of individual papers.

cc @GuyAglionby in case your script can do this easily

**Comment by GuyAglionby** [comment]
This should be pretty straightforward if the IDs here are parallel with those used in the Anthology, though I'm not sure that this is the case at the moment with the Demo and SRW papers. Would it be useful if I generated a mapping of submission id -> Anthology id for these?

**Comment by hao-fang** [comment]
@GuyAglionby That sounds good! Are you using exact match on the title to get the mapping?
I think this is a general good practice, because in theory, we will always get the session slots assigned using the submission ID. The Anthology ID will be a relatively independent process and we do not want it to block the website development.

**Comment by GuyAglionby** [comment]
That's the plan. That also makes sense!

**Comment by GuyAglionby** [comment]
There's 5 SRW papers that are in the current [srw_papers.csv](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/srw_papers.csv) but aren't on the Anthology: submission IDs 46, 79, 99, 105, 115, 116. Can we confirm if they should be included?

**Comment by GuyAglionby** [comment]
Here are the mappings: [demo-ids.xlsx](https://github.com/acl-org/acl-2020-virtual-conference/files/4816108/demo-ids.xlsx) [srw-ids.xlsx](https://github.com/acl-org/acl-2020-virtual-conference/files/4816110/srw-ids.xlsx). #72 and #73 are still open: should I leave it to those authors to integrate these into their ingestion scripts? (I think they're slightly modified from the one used for main track papers.)

**Comment by hao-fang** [comment]
> Here are the mappings: [demo-ids.xlsx](https://github.com/acl-org/acl-2020-virtual-conference/files/4816108/demo-ids.xlsx) [srw-ids.xlsx](https://github.com/acl-org/acl-2020-virtual-conference/files/4816110/srw-ids.xlsx). #72 and #73 are still open: should I leave it to those authors to integrate these into their ingestion scripts? (I think they're slightly modified from the one used for main track papers.)

I went ahead to re-generate the `demo_papers.csv` and `srw_papers.csv`. 
https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/45
https://github.com/acl-org/acl-2020-virtual-conference/pull/171

@georgepar @ardakdemir -- we still need to get the session information into the `paper_schedule.yml`.
