### ISSUE TITLE
Regular Paper Page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#16]
**Number of Volunteers**: 1

## ICLR Layout
![image](https://user-images.githubusercontent.com/9957482/83800945-215af580-a65d-11ea-832c-00c54aa3eaa0.png)

## Update (2020-06-12)
Rre-org the components for the paper webpage. Currently, it looks like this
![image](https://user-images.githubusercontent.com/9957482/84549418-c6f51100-acbc-11ea-9a05-9319b21e7227.png)

- [x] Remove the red text "Add content for posters. ...."
- [x] Put the SlidesLive & RocketChat in the same row.
- [x] We will not have the poster PDF. Check if there is a way to disable it (rather than deleting the code).

**Comment by hao-fang** [comment]
@salma-elanigri Thanks for volunteering on this issue. I updated the instruction (see the section "Update (2020-06-12)".

Please check these https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING.md and https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING-ACL2020.md for setting up your local environment.
You can launch a local server via `make run`.

Let me know if you have any questions :)

**Comment by salma-elanigri** [comment]
Okay, thank you @hao-fang

**Comment by hao-fang** [comment]
@salma-elanigri I'll answer your RocketChat question here for visibility so that other people can refer to this in future.

The template is indeed specified by the `template/poster.html`. This is a Jinja2 template. See details [here](https://jinja.palletsprojects.com/en/2.11.x/templates/).
The data `paper` is populated in `main.py` [here](http://github.com/acl-org/acl-2020-virtual-conference/blob/5961cb0695a04ab4213dcb1c731620d64f3b80bc/main.py#L196-L196). See the method `format_paper` for more details.
The `by_uid` is populated [here](http://github.com/acl-org/acl-2020-virtual-conference/blob/5961cb0695a04ab4213dcb1c731620d64f3b80bc/main.py#L31-L34).

So for this specific issue, you will need to edit the `template/poster.html`.
To see your changes locally, you can run `make run` and open your browser to look at the outcome.

Feel free to let me know if you have more questions.

**Comment by raosudha89** [comment]
Note from PCs:
- [ ] The paper title should appear in a different color than the 'Live', 'Q&A', 'Cal' links to show that the title is not clickable.

**Comment by jcklie** [comment]
@salma-elanigri How is your progress so far? I would like to support you on this task but do not want to get in your way. Which tasks are you working on right now and which can I take?

**Comment by salma-elanigri** [comment]
Hi @jcklie ! I am working on this task " See if we can display the time of the paper in the current timezone of the attendee (as used by the schedule calendar). " I tried to  use the moments and moment-timezonejs to convert the session.time to the user time zone but I don't how to make it work inside a Jinja loop.

**Comment by jcklie** [comment]
You can use the `static/js/time-extend.js` function we already wrote and use throughout the website, e.g. on the [sponsor page](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/templates/sponsor.html#L119). You need to format the time in a particular format, then it does the rest for you.

**Comment by salma-elanigri** [comment]
thanks I will check this.

**Comment by salma-elanigri** [comment]
![notfound](https://user-images.githubusercontent.com/36210302/85395269-c6c00580-b547-11ea-801a-bb6c67b0719f.PNG)
![paper_vis tml](https://user-images.githubusercontent.com/36210302/85395273-c7f13280-b547-11ea-829a-3fd46fcb68ce.png)

I have a problem with loading paper page after the last changes in the repository ( I already did a git pull)

**Comment by raosudha89** [comment]
Looks like all tasks in this issue are done. Thank you very much @salma-elanigri and @jcklie
