### ISSUE TITLE
Improve Home page layout

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#169]
**Number of Volunteers: 1**

The two videos are a little too small. Can anyone check if we can improve the layout a little bit?

![image](https://user-images.githubusercontent.com/9957482/85358094-bc5e2700-b4c7-11ea-9f0d-be1f72e6c287.png)

**Comment by raosudha89** [comment]
@hao-fang  How about instead of the two videos side-by-side, we can change it so that they are one below the other (with the announcement being the second column)? 

If that sounds good, I can work on this.

**Comment by hao-fang** [comment]
@raosudha89 
I tried to put them one below the other, but it doesn't look very nice. But I have to admit that I'm not good at frontend design. Maybe you can try it..
FYI -- This is an enhancement which has lower priority. I put these issues under the "Website Enhancement" project. So we should prioritize those "Basic Website" issues first.

**Comment by jcklie** [comment]
You could make a tab menu or a carousel so that you can switch between the two

**Comment by hao-fang** [comment]
Closing this with #198
