### ISSUE TITLE
Calendar / Schedule page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#18]
**Number of Volunteers**: 1

One volunteer should be in charge of the calendar/schedule webpage.

- [x] get the final schedule from the PCs. I'll send the info via email.
- [x] update the calendar based on the final schedule
  - [x] For main conference paper QA sessions, should be completed by #74 
  - [x] Need to update the plenary sessions schedule & other events
- [x] change the background color to make it more ACL (maybe use red?)

**Comment by raosudha89** [comment]
Request from PCs:
- [ ] In the calendar, have a way to distinguish between what has already happened and what is yet to come and also have a way to know where are we currently i.e. which day and what time.

**Comment by raosudha89** [comment]
- [ ] We should include 'Sunday' also in the calendar for tutorials.

**Comment by hao-fang** [comment]
@tanvidadu I think we should first add all QA sessions to the calendar.
The QA sessions are explained https://github.com/acl-org/acl-2020-virtual-conference/issues/74
For now, I think you should grab `sitedata_acl2020/poster_schedule.yml` and add the sessions (e.g., 1A, 1B, ...) to the calendar.

**Comment by raosudha89** [comment]
@hao-fang and @tanvidadu  I will work on including 'sunday' in the calendar to make sure tutorials are seen. Instead of adding schedule of each tutorial (which is already shown under tutorials page), I will add a high-level session times under 'sunday' i.e.
- 6:00 AM to 9:30 AM (Seattle Time)
- 10:30 AM to 2:00 PM (Seattle Time)
- 3:00 PM to 6:30 PM (Seattle Time)

**Comment by hao-fang** [comment]
@raosudha89 sounds good!
@tanvidadu We still need to add the QA sessions to the calendar. It seems that it can be done based on https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README_Schedule.md ?

**Comment by tanvidadu** [comment]
@hao-fang Yes, thanks, I'm on it!

**Comment by raosudha89** [comment]
@hao-fang  It looks like the entire main_calendar.json is still from ICLR. In addition to QA sessions, we need to add other events to this calendar as well. Do we already have other volunteers working on it?

**Comment by hao-fang** [comment]
@raosudha89 I think @tanvidadu is working on it https://github.com/acl-org/acl-2020-virtual-conference/issues/18#issuecomment-648254468
But we need to double check the paper_schedule.yml file because it is not very clear which timezone it was.
I'll take a look later today when I have time.
Do you think we can manually enter information into the json file? Or should we follow https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README_Schedule.md to generate it from a yml file?

**Comment by tanvidadu** [comment]
@hao-fang  @raosudha89 Yes, as of now, I've made followed the instructions from [https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README_Schedule.md](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README_Schedule.md) assuming Seattle time. Could you kindly confirm the time zone of the paper_schedule.yml file?

**Comment by hao-fang** [comment]
@tanvidadu The timezone is UTC+0. Is it easy to change the script?

**Comment by raosudha89** [comment]
@tanvidadu The script you are working on will add the paper QA sessions to main_calendar.json right? 
If yes, then once you do that, I can work on adding the following other events to the calendar:
- Plenary sessions
- Tutorials
- Workshops

**Comment by hao-fang** [comment]
@raosudha89 Probably you can make a similar `yaml` file so that we can modify that script to re-generate the `main_calendar.json` with two input files.
This way you two can work in parallel.
I'll think about how to automate this inside `load_site_data.py`.

**Comment by raosudha89** [comment]
@hao-fang  @tanvidadu  As far as I understand, https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README_Schedule.md script uses a given calendar (.ics file) to directly create main_calendar.json 

Which script is being to generate yaml file? 

I ask because, I can create a calendar (with plenary sessions, tutorials and workshops) and directly add entries into main_calendar.json  I don't need to create the intermediate yaml file. Should I just do that?

**Comment by tanvidadu** [comment]
I created a .ics file and generated the json, however, I can write a script if needed for converting the YAML file. 

@hao-fang Great, I'll do the same and change it for UTC+0.

@raosudha89 I agree, if there's no need for the YAML file, you may use the same procedure too.

**Comment by raosudha89** [comment]
@tanvidadu  Sounds great. I will update the main_calendar.json directly then. Thanks.

**Comment by tanvidadu** [comment]
I've created a PR in the sitedata repository for adding the QA sessions into the main_calendar.json.

**Comment by raosudha89** [comment]
Great. I will work on adding rest of the sessions as detailed in [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=936853935) into the main_calendar.json

**Comment by raosudha89** [comment]
> Great. I will work on adding rest of the sessions as detailed in [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=936853935) into the main_calendar.json

I have created a PR for this https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/49

**Comment by hao-fang** [comment]
@jcklie The new calendar looks nice!
I did some modification https://github.com/acl-org/acl-2020-virtual-conference/pull/193.
It looks like below now.
![image](https://user-images.githubusercontent.com/9957482/85486039-baa36a80-b57e-11ea-8eae-bbafdd2557b9.png)

There are still some things we may need to fix. Can you work on these items?
- [ ] Can we make "local" as the default Timezone?
- [ ] Figure out a better way to show plenary sessions. Maybe just group them into one card.
- [ ] @raosudha89 The "Tutorials (Session 1)" ... it might be confused with the "QA Sessions" but I don't have a good suggestion.. Just in case you have any ideas.

**Comment by raosudha89** [comment]
Closing this issue since main tasks are done. I created some additional new issues to handle some enhancements mentioned in here.
