### ISSUE TITLE
create RocketChat channels for SRW papers

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#197]
**Number of Volunteers: 1**

Similar to #38, but we should use `sitedata_acl2020/srw_papers.csv` instead.

**Comment by hao-fang** [comment]
@GuyAglionby  -- can you do this? Should be easy with your script, and you have the acl2020-admin-bot account information.

**Comment by GuyAglionby** [comment]
Done!
