### ISSUE TITLE
Get answers from ICLR chairs

### ISSUE THREAD

**Issue by desilinguist** [acl-org/acl-2020-virtual-conference#2]
We need to know the answers to the following questions from the ICLR 2020 chairs

- [x] Did they use a completely static website? If so, did they just use GitHub pages? 
We ran a server ourselves for auth, although we just hosted images etc on github pages. Probably we could have put them anywhere
- [x] If you used a server to host the ICLR website, which server did you use?

> I think it was NGinx. It just had auth and static pages. 

- [x] How did they integrate login/validation into GitHub Pages?

> We didn't. Guessing you can't do that, but it would have been nice. 

- [x] Did they have any issues with a lot of traffic slowing down the website on busy days or times?

> No, it was actually very stable. I think modern web servers are really good at static things. Our chat server and sponsor on the other hand both went down. We had to up the size of the server. 

- [x] Do you mind sharing the specs of the server you used? Was it an AWS instance? 

>No it was just the https://neurips.cc/ server.

**Comment by desilinguist** [comment]
@raosudha89 can you please add Sasha's answers from the email here so we have them documented a single place?

**Comment by raosudha89** [comment]
> @raosudha89 can you please add Sasha's answers from the email here so we have them documented a single place?

I updated the comment with his answers

**Comment by desilinguist** [comment]
Based on his answers, I _think_ we can just get a basic DO droplet for $5/mo, set up nginx on it and then just deploy the static website there. However, I want to hear what specs the NIPS server had before suggesting a final solution.

**Comment by desilinguist** [comment]
The server they ended up piggybacking on was a pretty beefy NeurIPS server with dozes of cores and 128G of RAM. We have asked if more moderate specs (e.g., Digital Ocean droplets with 4CPUs and 16G of RAM) would suffice for serving static content via nginx. Waiting for a reply.
