### ISSUE TITLE
Display paper types (Long/Short/CL/TACL)

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#206]
**Number of Volunteers: 1**

PC asked whether we can display the paper type on the webpage.
This is our current webpage.
![image](https://user-images.githubusercontent.com/9957482/85612275-93e04500-b60d-11ea-8d9d-82541f10eafe.png)

A basic solution would be making another button next to the track "Interpretability and Analysis of Models for NLP". But we should not make it look like "clickable".

**Comment by salma-elanigri** [comment]
Where can I get the information about the type of paper?

**Comment by hao-fang** [comment]
> Where can I get the information about the type of paper?

@salma-elanigri For main papers, it should be already in the `sitedata_acl2020/main_papers.csv` (see the column "paper_type").
You will need to edit `load_site_data` to populate that information, and then `paper.html` to add `{{ paper.paper_type }}` to display the information.
Let me know if you have additional questions.

**Comment by anaerobeth** [comment]
I can help with this feature if needed.

**Comment by hao-fang** [comment]
> I can help with this feature if needed.

@anaerobeth Yes! That would be great! Does the above description make sense to you?

**Comment by anaerobeth** [comment]
The instructions look good to me. However, I am having issues with setting up the repo and could not see the file `sitedata_acl2020/main_papers.csv` in master:
```
➜  acl-2020-virtual-conference git:(master) source .venv/bin/activate
(.venv) ➜  acl-2020-virtual-conference git:(master) pip install -r requirements.txt
(.venv) ➜  acl-2020-virtual-conference git:(master) make run
export FLASK_DEBUG=True; export FLASK_DEVELOPMENT=True; python3 main.py sitedata_acl2020/
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    extra_files = load_site_data(args.path, site_data, by_uid, qa_session_length_hr)
  File "/Users/tenorio/Documents/exercises/acl-2020-virtual-conference/miniconf/load_site_data.py", line 83, in load_site_data
    assert set(site_data.keys()) == registered_sitedata
AssertionError
make: *** [run] Error 1
```
What am I missing?

**Comment by hao-fang** [comment]
@anaerobeth Did you run `git submodule update --init --recursive` when you clone the repo?

You may want to take a look at https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING-ACL2020.md first.

**Comment by anaerobeth** [comment]
Proposed UI displaying the paper type in a gray rectangle next to the track:
<img width="877" alt="Screen Shot 2020-06-27 at 9 54 20 PM" src="https://user-images.githubusercontent.com/3663322/85935605-cd8ca680-b8c0-11ea-99dd-0c8c05e94569.png">

@hao-fang Let me know if this works.

**Comment by hao-fang** [comment]
@anaerobeth Looks nice! Can you make a PR for this? Thanks!
