### ISSUE TITLE
[RocketChat] Python scripts to manage RocketChat

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#208]
**Number of Volunteers: 1 - 2**

There are 800+ channels in our RocketChat and it is a little bit difficult to manage them on the web interface.
It would be nice to write a python script to list all channels so we can do some regex on the channel names to surface some unused channels.

It would be also nice to list all users so we can activate / deactivate users in a batch.
Examples for creating channels: https://github.com/acl-org/acl-2020-virtual-conference/blob/master/chat/make_poster_rooms.py
It uses this library: https://github.com/jadolg/rocketchat_API

**Comment by hao-fang** [comment]
Basically I want to be able to dump the channels into a file so I can use a text editor to view the information.
It can be as simple as a txt file with each line being a channel. But if you can do something fancier it would be useful too.

Same for the users. But we may want to do more on users soon, e.g., automatically add all users to a channel.
Feel free to post update on the Github issue -- I'll assign it to you.
If there are other volunteers who want to work on this, I'll put them in contact with you so you can collaborate on this.

**Comment by hao-fang** [comment]
cc @vladdy & @anaerobeth since this may help you on the #101: @GuyAglionby & @Robert-Alonso will work on this issue.

**Comment by hao-fang** [comment]
I just learned that 
> the "Featured" label will lift the channels (flagged as featured) to the top of the list in Directory, these ones will basically always be the first ones to notice: 

![image](https://user-images.githubusercontent.com/9957482/85628165-84202b00-b624-11ea-8c81-35082fa62a21.png)

Can you make the python script be able to print out all "featured" channels as well?

**Comment by hao-fang** [comment]
Another request -- we want to be able to assign users to be the owner of the channel.
Would be nice to be able to do it via a Python script which consume a csv/excel file.

@GuyAglionby @Robert-Alonso  -- let me know if you want to get one more volunteer on this.

**Comment by GuyAglionby** [comment]
@hao-fang Should be no problem. Would it be alright if this depended on the two original files requested (user list + channel list)? This is to allow the new script to be run with channel name + usernames rather than internal rocketchat IDs, which can be hard to find

**Comment by hao-fang** [comment]
> @hao-fang Should be no problem. Would it be alright if this depended on the two original files requested (user list + channel list)? This is to allow the new script to be run with channel name + usernames rather than internal rocketchat IDs, which can be hard to find

Yes, our unique identifier is the user's email in our AWS Cognito user pool, so we should rely on the email address instead of RocketChat IDs.

**Comment by hao-fang** [comment]
Another request -- can we make a python script to make a batch of channels to be "featured"?
It's fine to hard-code the channel names in the python script.

For example, I want to run
```bash
python make_channel_featured.py --channel-name-prefix "sponsor-"
```
which will make all channels prefixed by "sponsor-" as featured.

![image](https://user-images.githubusercontent.com/9957482/85639359-5eebe680-b63d-11ea-8309-aa84097eb2e5.png)

**Comment by Robert-Alonso** [comment]
ok, will work on it 👍

**Comment by panda-baba** [comment]
Could I also help you folks with the above scripts? I am familiar with python but not with rocket chat. Since we only need to make api calls to rocket chat. I guess I can help.

**Comment by Robert-Alonso** [comment]
Hi @panda-baba, thanks for your help! I think you could work on the `make_channel_featured.py` script Hao mentioned.

**Comment by hao-fang** [comment]
@panda-baba thanks for helping! Can you let me know your email so I can keep track the volunteers who currently have tasks? You can email me directly.

**Comment by hao-fang** [comment]
@GuyAglionby @panda-baba @Robert-Alonso  Can you start checking code to https://github.com/acl-org/acl-2020-virtual-conference-tools . You can put things under `acl2020_tools/chat`.
I'm going to remove scripts from this main repo after the transition.

**Comment by Robert-Alonso** [comment]
Hi @hao-fang I saw the `list_channels.py` in the `acl2020_tools` repo. Let me know if there's anything else to be done :+1:

**Comment by hao-fang** [comment]
@Robert-Alonso It would be nice if we can have a script to clear all messages in a list of channels.
We are going to do some dry-run and people may post test messages. We would like to remove those before the website goes live.

**Comment by hao-fang** [comment]
- [ ] We also need a script to add all users to a list of channels (supplied by a file).

**Comment by panda-baba** [comment]
I am facing some issues setting up the rocket chat server. I got it up but I am not getting the featured attribute while querying it through the API or the UI. Could you tell me what I am doing wrong? 
<img width="1336" alt="Screenshot 2020-06-27 at 12 43 10 PM" src="https://user-images.githubusercontent.com/19544783/85918577-b4183a00-b881-11ea-8411-f7bf697e5012.png">

**Comment by hao-fang** [comment]
> I am facing some issues setting up the rocket chat server. I got it up but I am not getting the featured attribute while querying it through the API or the UI. Could you tell me what I am doing wrong?
> <img alt="Screenshot 2020-06-27 at 12 43 10 PM" width="1336" src="https://user-images.githubusercontent.com/19544783/85918577-b4183a00-b881-11ea-8411-f7bf697e5012.png">

Maybe our acl2020.rocket.chat uses a different version than you?

**Comment by hao-fang** [comment]
New requests -- can someone write a script to do the following?
Given a csv file with email and paper UID (e.g., main-2), add the user to the corresponding channel (e.g., `#paper-main-2`) and set the user as the owner of the channel.
Thanks!

**Comment by GuyAglionby** [comment]
@hao-fang could this be a flag on https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/chat/add_users_to_channel.py?

**Comment by hao-fang** [comment]
> @hao-fang could this be a flag on https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/chat/add_users_to_channel.py?

@GuyAglionby -- That sounds good!
FWIW -- this will be used to set the author of the paper as the owner of their channel. I'm still trying to figure out where we can get such information (as the author may use a different email to register). Maybe we will need have volunteers to do it manually with a #author-registration-desk channel (which is less automatic, but maybe more close to a physical conference).

**Comment by Robert-Alonso** [comment]
> @Robert-Alonso It would be nice if we can have a script to clear all messages in a list of channels.
> We are going to do some dry-run and people may post test messages. We would like to remove those before the website goes live.
> 
> It is called "Prune Messages" in RocketChat.

Hi @hao-fang, do you know how I could get a RocketChat access token with delete permissions? 

![image](https://user-images.githubusercontent.com/5826177/85969472-60931280-b98d-11ea-84a1-bfa396ee67d4.png)

**Comment by hao-fang** [comment]
> > @Robert-Alonso It would be nice if we can have a script to clear all messages in a list of channels.
> > We are going to do some dry-run and people may post test messages. We would like to remove those before the website goes live.
> > It is called "Prune Messages" in RocketChat.
> 
> Hi @hao-fang, do you know how I could get a RocketChat access token with delete permissions?
> 
> ![image](https://user-images.githubusercontent.com/5826177/85969472-60931280-b98d-11ea-84a1-bfa396ee67d4.png)

@Robert-Alonso I just granted the "Clear Channel History" permission to `acl2020-admin-bot`. Can you check again?
But please be very careful with this permission and do NOT share the account & access token with other people.

cc @vladdy -- FYI I added a new role "admin-bot" which has the permission to "Clear Channel History". I added this role to the `acl2020-admin-bot` account. Do you have any concerns about this? Should I revoke this permission after @Robert-Alonso finishes his testing?

**Comment by Robert-Alonso** [comment]
Thanks @hao-fang! I successfully tested the script and just submitted the PR. I also created a #testchannel in RocketChat, feel free to delete it :+1:

**Comment by hao-fang** [comment]
> Thanks @hao-fang! I successfully tested the script and just submitted the PR. I also created a #testchannel in RocketChat, feel free to delete it 👍 and also revoke the granted permission.

@Robert-Alonso Thanks! I've deleted the channel and revoked the permission. I think talk with @vladdy to see whether we want to grant the permission to `acl2020-admin-bot` in future.
