### ISSUE TITLE
Workshops page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#21]
**Number of volunteers**: 2

**Comment by raosudha89** [comment]
The workshop main page should include following details:
- [ ] Overall schedule of workshops i.e. list of workshops on each day (https://acl2020.org/program/workshops/)
- [ ] A link to each of the individual workshops
- [ ] Some way to ensure only the attendees registered for a workshop get to see the content of the particular workshop.

Each of the individual workshop pages should contain the following information:
- [ ] Schedule of workshop. It can be found [here](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit?usp=sharing)
- [ ] SlidesLive videos of paper presentations
- [ ] RocketChat session for each paper 
- [ ]  Zoom link for live Q&A

**Comment by kaushal0494** [comment]
Hi @hao-fang,  I have few queries: 
1). What is expected for this " A high-level explanation of how to get the best experience of attending a workshop virtually"? Should we provide easy access to the deatils of the workshop page?  is is similar to 'help' instruction? Provide me your thoughts.   

2). For the workshop "Overall schedule of workshops" - Should we use a tabular form like the ICLR 2020 schedule (as given below)?  
![pic1](https://user-images.githubusercontent.com/7456682/84972367-5296f380-b13c-11ea-942d-558bc128324a.png)

**Comment by hao-fang** [comment]
@kaushal0494 

> 1). What is expected for this " A high-level explanation of how to get the best experience of attending a workshop virtually"? Should we provide easy access deatils or navigation instructions of the workshop page? is it similar to the 'help' instruction? Provide me your thoughts on this.

@raosudha89 can you answer this? I'm not sure what you had in mind.

> 
> 2). For the workshop "Overall schedule of workshops" - Should we use a tabular form like the ICLR 2020 schedule (as given below)?
> ![pic1](https://user-images.githubusercontent.com/7456682/84972367-5296f380-b13c-11ea-942d-558bc128324a.png)

I like these "Monday / Tuesday / ..." tabs. We will have one workshop on July 5, 10 on July 9, and another 10 on July 10.
I'm not sure about "Calendar", which I feel we should probably merge into the "Schedule" page rather than having two different places. Can we leave this one out for the first version?

**Comment by kaushal0494** [comment]
okay @hao-fang

**Comment by raosudha89** [comment]
@kaushal0494
> Hi @hao-fang, I have few queries:
> 1). What is expected for this " A high-level explanation of how to get the best experience of attending a workshop virtually"? Should we provide easy access deatils or navigation instructions of the workshop page? is it similar to the 'help' instruction? Provide me your thoughts on this.  
I will work on this. I will insert a short blurb. But I will do that once all workshop material is in the website.

**Comment by raosudha89** [comment]
@kaushal0494  Can you help with inserting all workshop information? Follow the steps below:
- [ ]  I just updated the tutorial page with each tutorial information (https://github.com/acl-org/acl-2020-virtual-conference/pull/109). The goal is to do this for all workshops as well
- [ ] You can get each workshop information from https://acl2020.org/program/workshops/
- [ ] Update the workshops.csv file first.  This needs to be updated in https://github.com/acl-org/acl-2020-virtual-conference-sitedata . Use W1, W2, .. under UID (it should correspond to the numbers in https://acl2020.org/program/workshops/) 
- [ ]  Next, make sure that this change gets reflected on the workshops tab
- [ ]  In workshop.html  add code for embedding slideslive and rocketchat channel,  just like in the tutorials page

**Comment by kaushal0494** [comment]
@raosudha89 I am working on it. I will complete it soon.

**Comment by raosudha89** [comment]
> @raosudha89 I am working on it. I will complete it soon.

Awesome, thanks :)

**Comment by kaushal0494** [comment]
@hao-fang can you provide instructions- how to run locally to see the website page. I run `make format` and all tests are passed.

**Comment by hao-fang** [comment]
> @hao-fang can you provide instructions- how to run locally to see the website page. I run `make format` and all tests are passed. 

You can do ‘make run’ to start the server locally.

**Comment by kaushal0494** [comment]
@hao-fang  all the format tests are passed.
When I am running `make run` then through this error

make run
export FLASK_DEBUG=True; export FLASK_DEVELOPMENT=True; python3 main.py sitedata_acl2020/
Traceback (most recent call last):
  File "main.py", line 465, in <module>
    extra_files = main(args.path)
  File "main.py", line 51, in main
    for p in site_data[typ]:
KeyError: 'papers'
Makefile:23: recipe for target 'run' failed
make: *** [run] Error 1

How to fix this key error.

**Comment by raosudha89** [comment]
> @hao-fang all the format tests are passed.
> When I am running `make run` then through this error
> 
> make run
> export FLASK_DEBUG=True; export FLASK_DEVELOPMENT=True; python3 main.py sitedata_acl2020/
> Traceback (most recent call last):
> File "main.py", line 465, in
> extra_files = main(args.path)
> File "main.py", line 51, in main
> for p in site_data[typ]:
> KeyError: 'papers'
> Makefile:23: recipe for target 'run' failed
> make: *** [run] Error 1
> 
> How to fix this key error.

It looks like your sitedata_acl2020 is most likely empty. Did you follow steps here https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING-ACL2020.md to link correctly to the other private repo that contains acl2020 sitedata?

**Comment by raosudha89** [comment]
@kaushal0494  We recently added a new workshop W20 https://acl2020.org/program/workshops/#w20-nlpcovid  Can you update workshops.csv with its information as well? Thanks.

**Comment by kaushal0494** [comment]
@raosudha89 I will update the contents workshops.csv and submit a PR.  Your suggestion looks good to me.

**Comment by kaushal0494** [comment]
@raosudha89 Done!

**Comment by raosudha89** [comment]
> @raosudha89 Done!

Thanks! I don't see a PR for this. Did you merge it with your previous workshop PR?

**Comment by raosudha89** [comment]
> @raosudha89 Done!

Great, I have approved and merged your PR on sitedata repo.

**Comment by kaushal0494** [comment]
@raosudha89 Let me know ..what next I should focus in this issue?

**Comment by hao-fang** [comment]
@kaushal0494 Can you do the following two things first?
- [ ] move `workshop.html` and `workshops.html` from the root folder to the `template/`.
- [ ] improve the `workshop.html` page

Currently it looks below.
![image](https://user-images.githubusercontent.com/9957482/85192133-43b45c00-b276-11ea-983e-56e5223e851b.png)

Let's chat this to something like below. Probably you can check https://github.com/ICLR/iclr.github.io/blob/master/templates/pages/workshop.html
![image](https://user-images.githubusercontent.com/9957482/85192339-00a6b880-b277-11ea-833a-4b0aaab24679.png)

**Comment by kaushal0494** [comment]
Sure @hao-fang I am on it. Thanks!

**Comment by raosudha89** [comment]
@hao-fang  and @kaushal0494 

I am going to work on displaying a high-level schedule for the workshops in the form of a calendar (just like we have for [tutorials](https://virtual.acl2020.org/tutorials.html)). I think this will be useful since each workshop has a different timeslot as given [here ](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=936853935). 

I will create a PR for this and show you how it looks here. We can then decide if we want to go ahead with it or not.

**Comment by raosudha89** [comment]
Below is a screenshot of the new view of workshops:

![image](https://user-images.githubusercontent.com/7291397/85235446-c4d03800-b3c9-11ea-9a5c-3a1b05e68fd4.png)

**Comment by kaushal0494** [comment]
@hao-fang @raosudha89 my apologies due to heavy rain in India, my internet was down from the last 2 days. I will complete the specified tasks today. Thank you!

**Comment by kaushal0494** [comment]
@raosudha89 This looks good to me. Easy to priorities- the workshops user wants to attend.

**Comment by hao-fang** [comment]
> Below is a screenshot of the new view of workshops. Let me know what you think. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/7291397/85235446-c4d03800-b3c9-11ea-9a5c-3a1b05e68fd4.png)
> 
> 

@raosudha89 looks good. Would it be possible to add workshop titles and organizers?

**Comment by raosudha89** [comment]
Here is a view with title and organizer list. Let me know if it is looking too busy.

![image](https://user-images.githubusercontent.com/7291397/85293813-b7ab5b80-b452-11ea-8899-969421de22a7.png)

**Comment by raosudha89** [comment]
Here is a PR for this feature https://github.com/acl-org/acl-2020-virtual-conference/pull/153

**Comment by raosudha89** [comment]
@ardakdemir  

- [ ] Can you work on customizing each workshop page with their detailed schedule? 

Check tabs named (July 5, July 9 and July 10) is [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372) to get the detailed schedule for each workshop. 

Also, [this page](https://acl2020.org/program/workshops/) contains links to the individual workshops website pages. If the schedule is missing in the spreadsheet for any workshop, you can hopefully get it from their individual website page. 

Let me know if you have any questions.

**Comment by hao-fang** [comment]
> Here is a view with title and organizer list. Let me know if it is looking too busy.
> 
> ![image](https://user-images.githubusercontent.com/7291397/85293813-b7ab5b80-b452-11ea-8899-969421de22a7.png)

@raosudha89 @kaushal0494 This looks nice. Can you test some different timezone? For example, it the whole schedule now span 2 days because of the timezone difference?

**Comment by kaushal0494** [comment]
@raosudha89  @hao-fang I observer some problem when the whole schedule now spans 2 days because of the timezone difference. It is not in a wrap-around manner.  

1). Asia/macau
![pic1](https://user-images.githubusercontent.com/7456682/85322805-84b1a800-b4e4-11ea-8047-0b7853f517ba.png)
2). HongKong
![pic2](https://user-images.githubusercontent.com/7456682/85323192-37820600-b4e5-11ea-92cc-dd5e032a2cfa.png)
3). Pacific/Enderbury
![pic3](https://user-images.githubusercontent.com/7456682/85323382-862fa000-b4e5-11ea-8162-eca7205c9f96.png)

What should we do next?

**Comment by raosudha89** [comment]
@kaushal0494  When a workshop spans multiple days (because of different timezones), it should show up on the tab of the next (or the previous) day. For this we may have to include July 8 and July 11 tabs as well. It would be nice if this shows up only for those whose agenda spills over into those other days. 

@kaushal0494  How about we fix https://github.com/acl-org/acl-2020-virtual-conference/pull/153 first? i.e. correctly showing calendars on multiple tabs. Once that is fixed, we can address this timezone related issue.

**Comment by kaushal0494** [comment]
@raosudha89 I will work on fixing #153

**Comment by raosudha89** [comment]
@kaushal0494 : You may want to look at changes in this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/190  It would be nice to have a similar day/list view under workshops as well.

**Comment by kaushal0494** [comment]
@raosudha89 Sure, let me check!

**Comment by kaushal0494** [comment]
> @kaushal0494 Can you do the following two things first?
> 
> * [x]  move `workshop.html` and `workshops.html` from the root folder to the `template/`.
> * [x]  improve the `workshop.html` page
> 
> Currently it looks below.
> ![image](https://user-images.githubusercontent.com/9957482/85192133-43b45c00-b276-11ea-983e-56e5223e851b.png)
> 
> Let's chat this to something like below. Probably you can check https://github.com/ICLR/iclr.github.io/blob/master/templates/pages/workshop.html
> ![image](https://user-images.githubusercontent.com/9957482/85192339-00a6b880-b277-11ea-833a-4b0aaab24679.png)

Hey @hao-fang I  am in the process of improving `worksho.html` .
I added `Site`,  `Live` and `Chat` tabs. The new-look is:

![pic1](https://user-images.githubusercontent.com/7456682/85530584-acf7ee80-b62b-11ea-8eda-7a860297b9dd.png)

I have few queries:
1). Do we need to add a `Calendar` tab as ICLR2020? 
2). De we need another tab `Schedule` which provides individual schedule?
3). Please provide some reference on how we can add zoom in the `Live` tab.
Thank you!

**Comment by raosudha89** [comment]
@kaushal0494  Regarding the 'Schedule' tab, yes, we do need a separate 'Schedule tab that displays the individual schedule for each workshop.

Check tabs named (July 5, July 9 and July 10) is [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372) to get the detailed schedule for each workshop.

Also, this page contains links to the individual workshops website pages. If the schedule is missing in the spreadsheet for any workshop, you can hopefully get it from their individual website page.

**Comment by kaushal0494** [comment]
@raosudha89 Sure let me add this!

**Comment by raosudha89** [comment]
@kaushal0494  Let me know if you need any help on this. We plan to do a dry-run of the website this Friday. So it would be good to finish this before that.

**Comment by kaushal0494** [comment]
@raosudha89  I am working on it, If I stuck I will ping you

**Comment by raosudha89** [comment]
Since the main workshop page is done (with this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/243), I am closing this and creating a new issue for customizing each workshop page (https://github.com/acl-org/acl-2020-virtual-conference/issues/244) and assigning @kaushal0494  to it.
