### ISSUE TITLE
Bash/Python scripts to generate papers_projection.json and paper_recs.json

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#212]
**Number of volunteers: 1 -- 2**

Currently it involve multiple steps as described in https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README.recommendations.md.
In particular, the paper recommendation involves some hacky steps (e.g., copy-paste files edit the `recs.py` script). It also does not work on CPU machine.
It would be really helpful if we can consolidate these steps in to a single python/bash script (or one for recommendation, one for projection), which takes a `merged_papers.csv` (generated by concatenating `sitedata_acl2020/{main,srw,demo}_papers`).
And we can then add it as a step in Makefile so we can do `make build-projection` and `make build-recommendations` to generate these files in `sitedata_acl2020`.

Required background:
* Python3
* pytorch
* pandas
* mypy (for type annotation)
* Makefile (optional)

**Comment by hao-fang** [comment]
There are some steps which I got stuck on for several minutes when following the steps https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README.recommendations.md#produce-similar-paper-recommendations
* Clone https://github.com/ICLR/iclr.github.io. You will need git-lfs installed.
  * You will need to run `git lfs pull`
* Install missing requirements
  * You should do `pip install openreview-py` instead of `pip install openreview`

Also, it seems that `umap` works better than `tsne` when generating the `papers_projection.json`, but I didn't do a careful test.

**Comment by hao-fang** [comment]
cc @PVinay737 can you self-assign to this issue once you accept the invitation? Thanks!

**Comment by hao-fang** [comment]
@georgepar That's a good idea!
@PVinay737 I've created a repo https://github.com/acl-org/acl-2020-virtual-conference-tools and invited you both to it.
Can you start working there?
I only enabled a "master" branch protection rule, so you will need to create PRs to merge your changes.
We may need to set up the Github Action there. But we can do it later (unless you already know how to set it up.)

**Comment by PVinay737** [comment]
@hao-fang Is it fine if I try to setup either of Circle/Travis CI ? 

@georgepar I'm trying to reproduce the steps following [guidelines](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README.recommendations.md) before I make changes to the Makefile. If there are any specific procedures to be followed do update me and I'll stick to that

**Comment by Robert-Alonso** [comment]
Hi @PVinay737 and @hao-fang 👋  I finished the RocketChat issue I was working on so I would like to help on this one. I've worked with PyTorch before so maybe I can lend a hand.

**Comment by georgepar** [comment]
> @georgepar I'm trying to reproduce the steps following [guidelines](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README.recommendations.md) before I make changes to the Makefile. If there are any specific procedures to be followed do update me and I'll stick to that

Ok there are 2 different processes that need to be automated:

### Paper visualization

 Here you need just the scripts included in this repo under scripts. The pipeline is 
- `merge_paper_csvs.py`: Main, demo and SRW papers are stored in 3 different CSVs. This creates a single CSV with all papers.
- `embeddings.py`: This extracts embeddings from abstracts using BERT. I run it on a GPU machine. not sure how fast it will be on CPU
- `reduce.py`: This performs dimensionality reduction using UMAP or TSNE. UMAP visualization seems a bit better, but I don't know if it's just me.

Just call the scripts with the arguments listed in the README. The result is a papers_viz.json that needs to be PR'd into the sitedata repo and then we can version bump the submodule.

### Paper recommendations

Here we need the scripts from https://github.com/ICLR/iclr.github.io, specifically `recommendations/recs.py` and `data/pkl_to_json.py`. Additionally we need the pretrained model `recommendations/scratch/similarity-model.pt`.
The steps are: 
- Run `scripts/create_recommendations_pickle.py` from this repo. This converts the papers into a `cached_or.pkl` that can be inputted to `recs.py`
- Run `recs.py` to procuce `rec.pkl`. This runs inference using the similarity model, so runing on GPU should make things faster
- Run `pkl_to_json.py` to create `paper_recs.json`. This can be PR'd in sitedata repo and is used for recommendations.

I hope this is clear enough. If you have more questions let me know.
(also these comments can be added to the README for future reference )

**Comment by hao-fang** [comment]
@PVinay737 Can you start checking code to https://github.com/acl-org/acl-2020-virtual-conference-tools . You can put things under `acl2020_tools/utils` or some other module.
I'm going to remove scripts from this main repo after the transition.

**Comment by PVinay737** [comment]
Sure, will follow up from [here](https://github.com/acl-org/acl-2020-virtual-conference-tools/tree/master/acl2020_tools/utils)

**Comment by PVinay737** [comment]
@hao-fang I've been able to reproduce `paper visualization` step and it's visualization gives (In Manual Inspection UMAP gives better correlations)

- UMAP
![umap](https://user-images.githubusercontent.com/44138475/85864145-c04cba80-b7e1-11ea-90cd-9cc6dfab207f.png)

- TSNE
![tsne](https://user-images.githubusercontent.com/44138475/85864040-9dbaa180-b7e1-11ea-8a09-66490bc09cde.png)

I suppose for the inclusion of this step in Makefile also requires the `sitedata` information which is not currently available in `acl2020_tools`. Where exactly should I make changes to the Makefile ? 

Second, Can I migrate scripts from `iclr` repos to `acl2020_tools/utils` once I'm able to fix the `paper recommendation` step ?

**Comment by hao-fang** [comment]
@PVinay737 this looks good.
 
> I suppose for the inclusion of this step in Makefile also requires the `sitedata` information which is not currently available in `acl2020_tools`. Where exactly should I make changes to the Makefile ?

Good questions. Can you hard-code the the path in Makefile? We probably don't want to use git submodule again because it causes a lot of confusion...
```
PATH_TO_SITEDATA = sitedata_acl2020

build-recommendations
  python -m acl2020_tools.xxxxx PATH_TO_SITEDATA
```

Then we add `sitedata_acl2020/` to `.gitignore` so you can make a symlink or a copy of `sitedata_acl2020` inside the `acl-2020-virtual-conference-tools` repo. Does this make sense?


> Second, Can I migrate scripts from `iclr` repos to `acl2020_tools/utils` once I'm able to fix the `paper recommendation` step ?

Sure. Go ahead to do it.

**Comment by hao-fang** [comment]
@PVinay737 This is a little urgent -- can you re-run the pipeline to generate the `paper_recs.json` and `papers_projection.json` by merging the following files in the `sitedata_acl2020`.
* main_papers.csv
* demo_papers.csv
* srw_papers.csv
* cl_papers.csv
* tacl_papers.csv

Thanks a lot!

**Comment by PVinay737** [comment]
Apologies for the delay in reporting @hao-fang.

I have rerun the scripts and added the new ones. Please review this [PR](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/84)

**Comment by anaerobeth** [comment]
@hao-fang If you are still looking for another volunteer, I can help with this issue.

**Comment by PVinay737** [comment]
@anaerobeth please go ahead

**Comment by PVinay737** [comment]
@anaerobeth please go ahead..

**Comment by PVinay737** [comment]
@anaerobeth please go ahead as I'm short of time..if you need anything from myside do update me asap

**Comment by hao-fang** [comment]
@PVinay737 @anaerobeth -- I think this is not time-sensitive anymore since we already get the files in #84 
You can work on other items with higher priority. If you want, you can come back to work on this one after the conference is over.
