### ISSUE TITLE
QA session links in main calendar

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#214]
Currently the QA sessions in the main calendar (under schedule tab) do not point anywhere. 
It would be nice if each QA session pointed to a page that lists all papers that have Q&A at that session so that an attendee can easily find papers that have Q&A at that time slot. This is traditionally what schedule for each session used to look like (for e.g. see naacl2019 schedule https://naacl2019.org/schedule/)

@hao-fang  What do you think about this?

**Comment by hao-fang** [comment]
Yes, we should do this.
MiniConf did this by using URL encoding, e.g., https://iclr.cc/virtual/papers.html?session=Tues+Session+2&filter=keywords
We need to encode this information in our data make this work.
Currently https://virtual.acl2020.org/papers.html?session=Tues+Session+2&filter=titles gives this, but it doesn't really do the job -- the papers can come from **any** session.
![image](https://user-images.githubusercontent.com/9957482/85661647-d173bb00-b66b-11ea-94d8-433f2d3313e9.png)

**Comment by raosudha89** [comment]
Using URL encoding to point to the papers page is a great idea. I am assigning one volunteer from the new pool of volunteers.

**Comment by clefourrier** [comment]
This will also need to update the data (to link each session with its URL encoding) as done in https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/65 . 

Please close after review, all should be done here.
