### ISSUE TITLE
Make tutorials/workshops page calendar similar to main calendar

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#215]
@jcklie  Currently the schedule on the main tutorials page is displayed using a calendar of a different color scheme. Can we align it with whatever the color for tutorials are on the schedule page? 

Regarding workshops page, there is a PR (https://github.com/acl-org/acl-2020-virtual-conference/pull/153) where we are trying to display just the three days of workshops instead of all days of the conference. If you can look into that as well, that would be great.

**Comment by raosudha89** [comment]
@jcklie Yes, replacing it with new one sounds great. I will close this very old PR https://github.com/acl-org/acl-2020-virtual-conference/pull/153  where we were trying to achieve this. Thanks.

**Comment by jcklie** [comment]
@raosudha89 How would the workshop page look with a calendar? Right now, there are only cards with the workshop descriptions. Do you want two tabs or something, one for the overview and one for the calendar or just remove the cards?

**Comment by raosudha89** [comment]
@jcklie  I would suggest removing the cards completely. All in the information in the card can be embedded into the slots in the calendar (just like it currently is under dayview of workshops in main calendar).

**Comment by raosudha89** [comment]
@jcklie  I think after looking through the tutorial calendar page, I think I have some idea of how to do this for workshop page as well. But if you have already finished most of it, then I won't try to do it. 

The reason I am trying to wrap these basic pages is because we have a dry run scheduled tomorrow where we are hoping we can show all main pages to PCs.

**Comment by raosudha89** [comment]
I submitted a PR for this https://github.com/acl-org/acl-2020-virtual-conference/pull/243

**Comment by jcklie** [comment]
@raosudha89 Nice work! I go to sleep when you start working so we missed each other yesterday.

**Comment by jcklie** [comment]
I think your filtering for day/week view is wrong though.

**Comment by raosudha89** [comment]
Aah is it? Please feel free to fix it. I am new to full calendar, so it is
possible I might have done something wrong. Thanks.
