### ISSUE TITLE
Provide a way to show/hide different types of events on the Calendar page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#219]
**Number of volunteers: 1 - 2**

Currently the calendar is very dense, and some text are not shown properly, e.g., 
![image](https://user-images.githubusercontent.com/9957482/85683540-2d493e80-b682-11ea-85cd-81a63ae8c4ec.png)

It would be nice if we can have some buttons to toggle different types of events. Is this something possible @jcklie ? 

Alternatively, we may just hide social events in the overall calendar. This might be controversial -- @raosudha89 do you have any ideas?
The problem will be worse because we will need to add Demo sessions to the calendar view, which are **not** aligned with the regular paper QA sessions.

**Comment by hao-fang** [comment]
@jcklie yeah, i think we are running out of time right now. So maybe we should go with the easier solution (i.e., do not show the social events here).
@raosudha89 what do you think?

**Comment by hao-fang** [comment]
Ok -- I advertised this issue in the mailing list. Let's see if we can get some volunteers who are familiar with the JS magic.

**Comment by jcklie** [comment]
I am happy to mentor if you find someone.

**Comment by raosudha89** [comment]
I have assigned two volunteers from the new pool of volunteers. @finiteautomata  and @MikelKN  Please ask @jcklie  if you need any high level advice.

**Comment by MikelKN** [comment]
I would love to help with that but i do not have experience coding in JavaScript.

**Comment by jcklie** [comment]
The code is in [cal_head.html](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/templates/cal_head.html)

What we need to do:

1. Add a multi dropdown next to the timezone one, see [here](https://developer.snapappointments.com/bootstrap-select/examples/#multiple-select-boxes) for an example. Pass the event types from flask and fill the dropdown with these.
2. Add a `onChange` callback on the dropdown and do the `calendar.refetchEvents` similarly to [datesSet](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/templates/cal_head.html#L81)
3. In the [events callback](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/templates/cal_head.html#L59), use the value from the dropdown to hide the events that are not selected via `obj["display"] = "none"`

**Comment by hao-fang** [comment]
@tlikhit Do you think you can help this based on the instruction above?

**Comment by tlikhit** [comment]
@hao-fang Yeah, I'll work on this

**Comment by hao-fang** [comment]
@tlikhit @jcklie if possible, can we make the dropdown to mark which subset to show?  just like the "labels" in GitHub
![image](https://user-images.githubusercontent.com/9957482/85768383-cfdadf00-b6cd-11ea-95c7-9b5b0864290e.png)

**Comment by tlikhit** [comment]
@hao-fang do you mean you want the ability to choose multiple event types at once? because then we'll have to address the overflow regardless if someone chooses all types...

**Comment by hao-fang** [comment]
> @hao-fang do you mean you want the ability to choose multiple event types at once? because then we'll have to address the overflow regardless in case someone chooses all types...

Yeah, that is what i have in mind. I'm hoping the users would be "okay" with overlapping like below if they can choose which event type to show. 
![image](https://user-images.githubusercontent.com/9957482/85771589-e9c9f100-b6d0-11ea-83e3-7ce2c6866398.png)

We just need to make sure there is no overflow like this
![image](https://user-images.githubusercontent.com/9957482/85771559-e33b7980-b6d0-11ea-92d1-106a406f19bc.png)

Is the overflow issue hard to solve?

**Comment by tlikhit** [comment]
@hao-fang Got it! I haven't used fullcalendar before, but I think I should be able to fix this 👍

**Comment by tlikhit** [comment]
@hao-fang  Currently, content is scrollable to prevent overflow, but I don't think this is ideal. I'm thinking of something like a tooltip wich pops more details on hovering, but it might not be mobile-friendly. What do you think?
![image](https://user-images.githubusercontent.com/58948612/85903678-f0da2780-b7d4-11ea-875b-03e735a054d9.png)

**Comment by hao-fang** [comment]
Tooltip sounds good! Probably we don't need to worry too much about mobile-friendly right now given our timeline.
