### ISSUE TITLE
Help page should say 'paper' instead of 'poster'

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#222]
We don't have any posters for ACL2020 this time. On the help page though, it looks like all references to presentations are called 'poster' (maybe because ICLR had posters).

We should replace poster with paper wherever appropriate throughout the help page. 

Tagging @dreasysnail  to assign appropriate volunteers.

**Comment by clefourrier** [comment]
This is a data problem, not a site problem, and will be fixed with the above mentionned merge.
