### ISSUE TITLE
Improve "Papers" page

### ISSUE THREAD

**Issue by jcklie** [acl-org/acl-2020-virtual-conference#230]
Right now, for every track, there is a button. This does not look so nice.

**Comment by jcklie** [comment]
Some work is left (clicking the paper/visualization buttons sometimes does not work and the title/author button is not checked on visualiazion). Also, it might deserve some care for less wide screens.

**Comment by hao-fang** [comment]
Add one more
- [ ] Make the search bar fill the row
![image](https://user-images.githubusercontent.com/9957482/85803090-46420600-b6fb-11ea-98f7-832879b67d95.png)

**Comment by hao-fang** [comment]
> Some work is left:
> 
> * [ ]  clicking the paper/visualization buttons sometimes does not work
> * [ ]  the title/author button is not checked on visualization
> * [ ]  It would be also cool if the visualization container fills the screen.
> * [ ]  Also, it might deserve some care for less wide screens.

@tlikhit -- Can you see if you can work on these? 
(@jcklie -- Are you actively working on it right now?)

**Comment by tlikhit** [comment]
Ok, I'll work on this. Another minor issue:
- [ ] Fix content moving out of scope when searching
<img width="1274" alt="Screen Shot 2020-06-26 at 5 58 03 PM" src="https://user-images.githubusercontent.com/58948612/85904514-ede03680-b7d6-11ea-9b69-283a778da11e.png">

**Comment by jcklie** [comment]
I do not intend working on this.

**Comment by hao-fang** [comment]
> * [ ]  clicking the paper/visualization buttons sometimes does not work

Should be fixed with #278.
But someone needs to add some margin.
Also it's probably better to increase the "Tracks" box and decrease the size of the search bar.
@tlikhit Will you be able to fix this?

**Comment by hao-fang** [comment]
@tlikhit Please prioritize #240 first. 
I'll close this one because I think it works good enough.
