### ISSUE TITLE
Customize each workshop page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#244]
- [ ] @kaushal0494  Add detailed schedule for each workshop. Check tabs named (July 5, July 9 and July 10) is [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372) to get the detailed schedule for each workshop.

- [ ] @raosudha89  Add a virtual format description for each workshop (just like we have for [each tutorial](https://virtual.acl2020.org/tutorial_T1.html) 

- [x] @kaushal0494 Depending on whether the workshop has prerecorded talk and/or livestreaming of zoom session, embed slideslive video. Check how this is done for tutorials and do similarly.

**Comment by kaushal0494** [comment]
@raosudha89 Sure, Thanks for specific tasks.

**Comment by kaushal0494** [comment]
> * [ ]  @kaushal0494  Add detailed schedule for each workshop. Check tabs named (July 5, July 9 and July 10) is [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372) to get the detailed schedule for each workshop.

@raosudha89  In the schedule tab:  do we need to add schedule with calendar and timezone (as done for the tutorial home page) or simply add the schedule as given in [spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372)?

**Comment by raosudha89** [comment]
> > * [ ]   @kaushal0494  Add detailed schedule for each workshop. Check tabs named (July 5, July 9 and July 10) is [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372) to get the detailed schedule for each workshop.
> 
> @raosudha89 In the schedule tab: do we need to add schedule with calendar and timezone (as done for the tutorial home page) or simply add the schedule as given in [spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=261172372)?

@kaushal0494  Just simply add the schedule as given in the spreadsheet and add a note above that the all times are in PST. No need of a calendar.

**Comment by kaushal0494** [comment]
@raosudha89 Thank you for the clarification.

**Comment by kaushal0494** [comment]
Created PR #279 for prerecorded talk and/or live streaming of zoom session, embed slides live video.  @raosudha89 you can 
 add virtual format description for each workshop. Let me know if I have to add more information.

**Comment by raosudha89** [comment]
@kaushal0494  PR https://github.com/acl-org/acl-2020-virtual-conference/pull/279 was failing some checks. Please check my comments on that PR to fix the issues.

**Comment by raosudha89** [comment]
@kaushal0494  your PR has now been merged.

Do you have an ETA on when the schedule for each workshop will be posted?

**Comment by kaushal0494** [comment]
@raosudha89 I am working on that. Due to the non-uniform schedules, I am facing a problem in including them automatically. I will try to finish today.

**Comment by kaushal0494** [comment]
Again same problem: Unable to add a schedule for individual workshop pages automatically from (using workshop id) .yml file. It will be great If some can have a look. Thanks

**Comment by raosudha89** [comment]
@tlikhit Can you please take a look at the issue @kaushal0494  is facing?

**Comment by raosudha89** [comment]
@tlikhit  Can you please prioritize this? The first workshop (W1: WiNLP) is schedule for July 5th and the website is going live on July 3rd. We really want the detailed schedule for atleast W1 to be up by then. Thanks.

**Comment by raosudha89** [comment]
@tlikhit  I am working on converting workshops.csv to workshops.yml file so that we can include the schedule (i.e. list of talks, their timings and video ids) in them. I will push the yml file and let you know.

**Comment by tlikhit** [comment]
@raosudha89 Please ping me once you've added the workshops.yml file. I'll add in a calendar style schedule.

**Comment by raosudha89** [comment]
@tlikhit  I ended up not working on creating the yml file since I don't know how to do that. 

I instead worked on displaying prerecorded talks on each workshop page. See this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/328

We still need a way to display the schedule. It need not be in the calendar form (since that would be complicated). Can we just list the schedule in the form of start time, end time, name of speaker, and title of talk? I am not sure  how to best do this in yml form. Can you work on this please?

**Comment by tlikhit** [comment]
@raosudha89 Ok, I'll have to add in the schedule info for each workshop from the spreadsheets. I'm assuming I should include everything - breaks, poster sessions, prerecordings and live sessions.
Do I have to take into consideration the subdivisions in the workshop? For example, if I'm not misunderstanding, W1 seems to be divided into 4 sections.

**Comment by sudhra** [comment]
@tlikhit  Each workshop has a dedicated website that you can find here: https://acl2020.org/program/workshops/ 
You can pickup the detailed schedule from there. That will clarify questions about subsections. 
If it is easy to include subsections, add those. Otherwise, we can just keep it linear.

**Comment by sudhra** [comment]
Actually, lets not worry about subsection. Let's mainly add the time and the name of the session. It would be easier that way and honestly, we don't have enough time to be thorough here. So let's just do the minimum we can.

**Comment by raosudha89** [comment]
@tlikhit  Is there any update on this? We need this to be done latest by 3pm PT today. The website goes live tomorrow. Sorry for rushing you, but this is critical at this point. Thanks.

**Comment by tlikhit** [comment]
@raosudha89 In the current merge I used data from the spreadsheet. I'm cleaning and reformatting the data for the rest of the workshops too, should be done soon. A couple of questions:
- W1(WiNLP) website has a sponsored breakfast from 8-9 as first event on its website but not in the spreadsheet. Should I add in events on the workshop websites but not in the spreadsheet?
- The workshops page seems to be organized into tabs for various dates, but some workshops are being held on multiple days (eg: W2 on July 9 & 10). How should I handle this? Maybe I could add in the day in the table and display workshops on multiple days in both tabs?

**Comment by raosudha89** [comment]
@tlikhit  

- Good question. I think the website schedule is old. Let's use the spreadsheet only
- Yes, sounds good

Also, could you make the schedule collapsible and keep it hidden by default? I think it is taking up too much space right now.  Thanks

**Comment by tlikhit** [comment]
>    ~~* The workshops page seems to be organized into tabs for various dates, but some workshops are being held on multiple days (eg: W2 on July 9 & 10). How should I handle this? Maybe I could add in the day in the table and display workshops on multiple days in both tabs?~~ Nvm, I realized it just referenced start dates :p 
I will add in days and make it collapsible 👍

**Comment by raosudha89** [comment]
@tlikhit  Thanks. Please tag me here once you submit the PR for making it collapsible.

**Comment by raosudha89** [comment]
@tlikhit  Are you working on this currently? If not, then I can work on this. We want this updated in the next hour since we will be recording an intro video at 1pm PT and we are hoping this page will be updated by then.

**Comment by tlikhit** [comment]
@raosudha89  I'm done with it! I'm waiting on https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/136 to be merged as I changed some fields

**Comment by raosudha89** [comment]
Thank you so much. I just merged that PR.

**Comment by tlikhit** [comment]
@raosudha89  Thanks, sent in #358

**Comment by raosudha89** [comment]
@tlikhit  Thank you so much! I merged the PR. Closing this now.
