### ISSUE TITLE
Use tabs in workshops page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#251]
**Number of Volunteers: 1**

cc @raosudha89 
This could be controversial, but I found it a little confusing to show the day view by default on the workshops page.
Without reading the text, I'm a little surprised there is only a single workshop in the calendar. And I need to click ">" multiple times to get to the "July 9".

I feel it would be easier to use the tab + cards instead of the calendar view, just like what we have now for "Plenary Sessions".
![image](https://user-images.githubusercontent.com/9957482/85834401-28e75900-b748-11ea-8a33-dccad1a39140.png)

**Comment by raosudha89** [comment]
@hao-fang  I did want to use a tab view but with calendar within it since there are a lot of overlapping workshops on July 9 and July 10. So just listing them one below the other would be less useful for the attendee. 

So can we have tabs but display workshops in the form of a day-view calendar within it?

**Comment by raosudha89** [comment]
@jcklie  I wonder if there is way to display only certain days under week-view of a calendar? If so then we could still use the calendar view but only show days July 5, 9 and 10.

**Comment by jcklie** [comment]
We can do that, but we have the problem of extreme time zones moving slots one day back or forth

**Comment by clefourrier** [comment]
I'm doing this at the moment 
![image](https://user-images.githubusercontent.com/22726840/85865776-b10c4380-b7c6-11ea-907b-206bf46b240a.png)

Could you please tell me rapidly if you want me to do something else instead?

**Comment by raosudha89** [comment]
@clefourrier  This looks good to me. It may help to show the start and end times of workshops in these cards. But we can do that as an enhancement it not easy.

**Comment by clefourrier** [comment]
@raosudha89 I'm done for the tab add, cf the 2 merge requests. Please check if all is good. 

Regarding start/end date, I think it should be added in the data first.

**Comment by raosudha89** [comment]
@clefourrier I merged the sitedata PR. But the other PR has a conflict. 

Regarding start/end date, it is included in overall_calendar.json. We will need to use that show dynamically show the start-end times locally and in GMT (check an e.g. paper https://virtual.acl2020.org/paper_main.367.html)

**Comment by hao-fang** [comment]
@clefourrier @raosudha89 I think we can always use UTC+0 to group workshops into a day.
This is what I currently do for Plenary Sessions.

![image](https://user-images.githubusercontent.com/9957482/85874990-5e139b80-b788-11ea-9c71-217dba6df7c8.png)

I'm basically following the proceedings (see screenshots https://github.com/acl-org/acl-2020-virtual-conference/issues/205#issuecomment-649862715)

**Comment by clefourrier** [comment]
Does this issue need anything else?

**Comment by raosudha89** [comment]
Closing this. Thanks @clefourrier
