### ISSUE TITLE
add CL & TACL papers to sitedata_acl2020

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#252]
**Number of Volunteers: 1 - 2**

We need to add CL&TACL papers to `sitedata_acl2020`.
See the three raw files in this PR https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/73/files

We need to generate the following files
* cl_papers.csv
* tacl_papers.csv
* cl_paper_sessions.yml
* tacl_paper_sessions.yml

Should use scripts in https://github.com/acl-org/acl-2020-virtual-conference-tools/

cc @GuyAglionby @georgepar @ardakdemir -- since you have been working on similar things before?

cc @prabhat1081 -- we also need to extract the images from these PDFs

**Comment by shruti-singh** [comment]
Hi,
I can help with this. Can someone please point me to the format of the csv files? Probably someone who has worked before, can they please point me what needs to be done. Thanks!

**Comment by GuyAglionby** [comment]
@shruti-singh The csv files should have the same format as e.g. [srw_papers.csv](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/srw_papers.csv). There's a lot that can be reused from [process_srw_papers.py](https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/utils/process_srw_papers.py) to create this. Ditto the poster sessions - they'll look something like [this](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/srw_paper_sessions.yml) and [this](https://github.com/acl-org/acl-2020-virtual-conference-tools/blob/master/acl2020_tools/utils/qa_schedule_import.py) script may help. Happy to give any other pointers as needed

**Comment by shruti-singh** [comment]
Hi,
I have one more question regarding the sessions.yml files. Should I use the ID field in [2020_live_Q&A_schedule(forauthors).xlsx](https://docs.google.com/spreadsheets/d/19zvNvqnh3Is_tzfpfpbdTWUiga772KT_gH8qtIAyDqc/) or the SubmissionID field in [ACL2020.CL.papers.xlsx](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/fdd0a206825ea2f01851c0b36e3bb1d6ca7a93e2/inbox/ACL2020.TACL.papers.xlsx) as the paper ids?
Similarly for the cl_papers.csv file, should the UID be SubmissionID from the ACL2020.CL.papers.xlsx or the ID from the ACL 2020 live Q&A schedule (for authors).xlsx?

**Comment by hao-fang** [comment]
> Hi,
> I have one more question regarding the sessions.yml files. Should I use the ID field in [2020_live_Q&A_schedule(forauthors).xlsx](https://docs.google.com/spreadsheets/d/19zvNvqnh3Is_tzfpfpbdTWUiga772KT_gH8qtIAyDqc/) or the SubmissionID field in [ACL2020.CL.papers.xlsx](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/fdd0a206825ea2f01851c0b36e3bb1d6ca7a93e2/inbox/ACL2020.TACL.papers.xlsx) as the paper ids?
> Similarly for the cl_papers.csv file, should the UID be SubmissionID from the ACL2020.CL.papers.xlsx or the ID from the ACL 2020 live Q&A schedule (for authors).xlsx?

@shruti-singh Sorry for the confusion. I asked PCs about it and forgot to post it here.
In the `2020_live_Q&A_schedule (for authors).xlsx` file, you need to strip the "9" (for CL papers) and "99" (for TACL papers). For example, "91482" should become "1482", and "991709" should become "1709".
Then these IDs are consistent with the "Submission ID" in the `ACL2020.CL.papers.xlsx` and `ACL2020.TACL.papers.xlsx`.

For generating the `sessions.yml` and `papers.csv`, can you prefix the ID with `cl` and `tacl`( e.g., `cl.1482`, `tacl.1709`) to be consistent with other papers (e.g., `main.1`, `srw.2`).

BTW, will you able to generate these files today? We are a little blocked by this so we need these files asap. If needed, I can work on the scripts as well. Thanks!

**Comment by shruti-singh** [comment]
> > Hi,
> > I have one more question regarding the sessions.yml files. Should I use the ID field in [2020_live_Q&A_schedule(forauthors).xlsx](https://docs.google.com/spreadsheets/d/19zvNvqnh3Is_tzfpfpbdTWUiga772KT_gH8qtIAyDqc/) or the SubmissionID field in [ACL2020.CL.papers.xlsx](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/fdd0a206825ea2f01851c0b36e3bb1d6ca7a93e2/inbox/ACL2020.TACL.papers.xlsx) as the paper ids?
> > Similarly for the cl_papers.csv file, should the UID be SubmissionID from the ACL2020.CL.papers.xlsx or the ID from the ACL 2020 live Q&A schedule (for authors).xlsx?
> 
> @shruti-singh Sorry for the confusion. I asked PCs about it and forgot to post it here.
> In the `2020_live_Q&A_schedule (for authors).xlsx` file, you need to strip the "9" (for CL papers) and "99" (for TACL papers). For example, "91482" should become "1482", and "991709" should become "1709".
> Then these IDs are consistent with the "Submission ID" in the `ACL2020.CL.papers.xlsx` and `ACL2020.TACL.papers.xlsx`.
> 
> For generating the `sessions.yml` and `papers.csv`, can you prefix the ID with `cl` and `tacl`( e.g., `cl.1482`, `tacl.1709`) to be consistent with other papers (e.g., `main.1`, `srw.2`).
> 
> BTW, will you able to generate these files today? We are a little blocked by this so we need these files asap. If needed, I can work on the scripts as well. Thanks!

Thanks for the clarification! I should be done with this soon.
