### ISSUE TITLE
Host the demo webpage on ACL's AWS account

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#26]
- [x] create AWS resources using [this link](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge) based on [this tutorial](https://aws.amazon.com/blogs/networking-and-content-delivery/authorizationedge-using-cookies-protect-your-amazon-cloudfront-content-from-being-downloaded-by-unauthenticated-users/)
  * > You may find that your application does not render properly -- the default Content Security Policy (CSP) in the CloudFormation parameter may be the issue. As a quick test you can either remove the "Content-Security-Policy":"..." parameter from the CloudFormation's HttpHeaders parameter, or substitute your own. Leave the other headers in the parameter alone unless you have a good reason.
- [x] upload files to S3
  * Because CloudFront uses cache, new files uploaded to S3 may not be immediately updated. We can probably initiate a cache invalidation action.  https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html
- [ ] set up the domain name `virtual.acl2020.org`
  * https://serverless-stack.com/chapters/setup-ssl.html
  * https://serverless-stack.com/chapters/setup-your-domain-with-cloudfront.html
- [x] check if we have enabled HTTPs
- [x] add a version file under `build/` so we know which version is hosted on the S3 bucket.

**Comment by hao-fang** [comment]
With #44, every master commit will automatically publish a new version to AWS S3.

**Comment by stupid-2020** [comment]
@hao-fang Will do it soon.  And try to use pre-commit to automate the SHA update.

**Comment by stupid-2020** [comment]
@hao-fang Do we have the IP address(es) for the virtual.acl2020.org?

BTW, according to my understand, the DNS for acl2020.org is not point to cloudfront (should be some DNS owned by the domain registrar).  Please advise.  Thanks a lot.

**Comment by hao-fang** [comment]
@stupid-2020 Sorry I didn't make it clear. I'm working on the domain name right now. There are a few configurations I need to do on the AWS side. Hopefully this will be done this week.

I'll close this ticket for now to avoid confusion.
