### ISSUE TITLE
[BUG?] Calendar View

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#266]
@tlikhit It seems that there is something wrong with the calendar view? It the whitespace intended for the scroll bar?
![image](https://user-images.githubusercontent.com/9957482/85906766-304c4800-b7c4-11ea-9010-f0e5ede3cd81.png)

**Comment by hao-fang** [comment]
BTW -- do you think it is okay to select all event types by default?

**Comment by tlikhit** [comment]
@hao-fang That's odd, I'm unable to replicate this... Which browser are you using?
In any case, I'll add in tooltips and see if the issue is solved afterward. 
Also, agree that selecting all events will be better.
![image](https://user-images.githubusercontent.com/58948612/85910905-871b4700-b7ef-11ea-9d04-3253c4778daa.png)

**Comment by hao-fang** [comment]
@tlikhit -- I'm using Chrome. Can you try it on https://virtual.acl2020.org/schedule.html?

**Comment by tlikhit** [comment]
Sorry, I'm unable to replicate on the website on chrome too...If you can spare some time, could you try inspecting the box?
<img width="1187" alt="Screen Shot 2020-06-26 at 9 43 03 PM" src="https://user-images.githubusercontent.com/58948612/85911887-38bd7680-b7f6-11ea-921c-ed8b19494531.png">

**Comment by hao-fang** [comment]
hmm..... this is what i have

![image](https://user-images.githubusercontent.com/9957482/85912402-10774d00-b7e1-11ea-854b-732bf1e08152.png)

Maybe after switching to tooltips it will go away

**Comment by hao-fang** [comment]
Also, how should we handle these 15min sessions?

![image](https://user-images.githubusercontent.com/9957482/85914848-095b3980-b7f7-11ea-9d4a-8f44a3116eaf.png)

![image](https://user-images.githubusercontent.com/9957482/85914857-1546fb80-b7f7-11ea-932f-6cf823b65128.png)

**Comment by raosudha89** [comment]
@tlikhit  I second with Hao's suggestion of showing all events by default. Right now, it looks like QA is the only session displayed on the schedule. It is hard to notice the 'Event types' dropdown instantly on that page. Thanks.

**Comment by raosudha89** [comment]
Many internal committee members now have access to the website and may need to use the schedule page for their tasks. Currently the schedule tab is almost unreadable (QA sessions for e.g.) with the scroll bar issue. We need to fix this ASAP.

**Comment by hao-fang** [comment]
@tlikhit Nice job! It looks good now!
