### ISSUE TITLE
Website Enhancement Suggestions

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#269]
**Number of Volunteers: 3-5**

(from Sasha & Hendrik)

- [x] Tutorials: I think it would be great to add the relevant parts of the blog post (Intro, Attendance, Program, Schedule) at the bottom and shrink the calendar height. This makes also clear that the multiple time slots are re-runs and not part 1 and 2 of the same tutorial.
- [x] Papers: "Demo" -> "Demo Papers"
- [x] Papers/Vis: The missing keywords makes the rectangle selection of subsets less useful. If there is a problem with the keywords: I had in an earlier version to just count the most frequent words in all selected abstracts (minus stop words), which could be worth a try?
  * Someone can take a look at https://github.com/Mini-Conf/Mini-Conf/issues/34 ?
- [ ] Socials: I wonder if a high-level sub-category would make sense for "Socials" : "BoF" vs "not BoF" ?
  * Maybe make a "Bird-of-a-Feature" tab and a "Regular" tab? Any suggestion?
- [x] Sponsors: Maybe renaming it into "Sponsor Lounge" or something similar helps communicating that this section is about getting into contact with sponsors and not just a list of them.
- [ ] General: I would recommend to have one person dedicated to look at all subparts to check for color consistency. A large overall amount of different colors makes the experience look less professional.

**Comment by anaerobeth** [comment]
@hao-fang I can help with Papers/Vis: Missing keywords issue since I am already familiar with https://github.com/Mini-Conf/Mini-Conf/issues/34

**Comment by hao-fang** [comment]
> @hao-fang I can help with Papers/Vis: Missing keywords issue since I am already familiar with [Mini-Conf#34](https://github.com/Mini-Conf/Mini-Conf/issues/34)

@anaerobeth That's great! You are definitely the right person!

**Comment by anaerobeth** [comment]
@hao-fang These are the keywords extracted using DyGIE++ from the title+abstract of the main papers:

[acl_keywords.xlsx](https://github.com/acl-org/acl-2020-virtual-conference/files/4849342/acl_keywords.xlsx)

Let me know if anything looks off to you. I can save a new version of main_papers.csv with the missing keywords filled in and create a PR.

**Comment by hao-fang** [comment]
@anaerobeth This looks good.
Can you figure out how to add them so it can be used in the Visualization page?
I imagine you just need to fill in the "keywords" column in `main_papers.csv` under `sitedata_acl2020`. But I'm not 100% sure.

**Comment by anaerobeth** [comment]
New visualization displaying keywords:
<img width="1048" alt="Screen Shot 2020-06-30 at 1 46 16 PM" src="https://user-images.githubusercontent.com/3663322/86159644-aa3c4400-bad8-11ea-876d-da7d2b5ebadf.png">

**Comment by hao-fang** [comment]
@anaerobeth This looks fun!
I wonder whether we should also "search-by-keywords" feature now..
Do you know how to do it? You can probably compare our code with Mini-Conf code...

**Comment by anaerobeth** [comment]
@hao-fang Search by keywords functionality:
<img width="1064" alt="Screen Shot 2020-06-30 at 9 22 19 PM" src="https://user-images.githubusercontent.com/3663322/86192672-19855880-bb18-11ea-8fad-5823ad358deb.png">


Keywords displayed in the paper header:
<img width="1003" alt="Screen Shot 2020-06-30 at 9 22 47 PM" src="https://user-images.githubusercontent.com/3663322/86192614-fe1a4d80-bb17-11ea-96d6-7db4580d089d.png">

**Comment by hao-fang** [comment]
@anaerobeth Thanks a lot!
Let's do this.
* Enable search by keywords in both "Browse" and "Visualization"
* But do **not** display the keywords on the paper header (it is a little bit too noisy).

Can you make the changes and submit a PR in https://github.com/acl-org/acl-2020-virtual-conference-sitedata and another PR in this repo?
Thanks! This is awesome!

**Comment by SebastinSanty** [comment]
@hao-fang I can probably take a stab at the Tutorials section. Also, regarding the colors, we might want to make it accessible for color-blind people.

**Comment by hao-fang** [comment]
@SebastinSanty Sounds great! Please do it!
