### ISSUE TITLE
Socials page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#27]
**Number of Volunteers**: 2

Example from ICLR
[ICLR 2020 - Socials.pdf](https://github.com/acl-org/acl-2020-virtual-conference/files/4783645/ICLR.2020.-.Socials.pdf)
![image](https://user-images.githubusercontent.com/9957482/83109399-312f7400-a076-11ea-8ccc-e825e32d602f.png)

Reach out the social event chairs to collect the following information
1) Organizer names
2) Logo
3) Event description
4) Website link
5) Name of the RocketChat channel, e.g., #queer-in-ai. (the channel name cannot have special characters or space in between)
6) Live Zoom call schedule

**Comment by hao-fang** [comment]
@Robert-Alonso Can you first make a sample webpage with some dummy social events? I'll get back to you with our schedule.
Let me know if you need more instructions about where to start.

**Comment by hao-fang** [comment]
@Robert-Alonso I updated the instructions. 
Maybe you can make the sample webpage using the ICLR template https://github.com/ICLR/iclr.github.io/blob/master/templates/pages/socials.html
Let me know if you need any more information.

Also, if you feel you need another volunteer to pair with you, please let me know and we will see if we can assign another person on this issue.

**Comment by Robert-Alonso** [comment]
Thanks for the extra info and the reference repo @hao-fang, I was just about to ask about some details about the ICLR socials page screenshot which I was replicating in the [branch](https://github.com/acl-org/acl-2020-virtual-conference/tree/feature/27-socials-page) I was working on. I started with a format based on the workshops section with dummy social events, which I'll add to the sitedata repo, I'll be checking out the ICLR template 👍

**Comment by hao-fang** [comment]
@Robert-Alonso @dreasysnail -- I think the current version is good for a basic website.
We can do enhancement with follow-up issues. So I'm closing this ticket for now.
But if you are still working on it, feel free to re-open it.
