### ISSUE TITLE
Enhancements on Home page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#275]
**Number of Volunteers: 1**

- [ ] Remove the first intro video
- [x] Make Move organizers & acknowledgements to its own page "Organizers"
  - [x] Given the many organizers, maybe it's recommendable to allow four picture tiles per row to reduce scrolling.

**Comment by goodmami** [comment]
I'll take this.

**Comment by goodmami** [comment]
PR #300 just moves the organizers to their own page. Once they were off the home page, it didn't actually feel like too much scrolling so I think 3 tiles per row is fine, and in fact 4 might be too crowded on some displays.

And regarding the following:

> - [ ] Remove the first intro video

It looks like there are two video slots on the home page:
1. A Message from the General Chair and Program Chairs
2. About the virtual conference website

Both currently have a placeholder video. Are you suggesting to get rid of slot (1)? Do we have the actual videos for either?

**Comment by hao-fang** [comment]
@goodmami yes, please remove the "A Message from the General Chair and Program Chairs". 
Thanks!

**Comment by goodmami** [comment]
Done in #302. Thanks!
