### ISSUE TITLE
Add start end times in calendar on schedule page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#282]
Right now, it is hard to align some sessions to the time especially on days that have too many parallel sessions. It would be really helpful if the sessions include start time (and if possible end time) along with their names in the calendar. 

For e.g. instead of "Undergraduate student panel" --> "7:00 - 8:30 Undergraduate student panel"

@hao-fang  let me know what you think. I can work on this if you agree.

**Comment by hao-fang** [comment]
@raosudha89 would those text fit into the calendar card?
Go for it if it works better.

**Comment by raosudha89** [comment]
Okay. I will wait for https://github.com/acl-org/acl-2020-virtual-conference/issues/266 to be fixed and then see addition of times look on the calendar.

**Comment by tlikhit** [comment]
@raosudha89  I tried to add in time but it doesn't look good. What I'm thinking of doing is totally removing the first column with times and putting times and partial title on the card. Clicking on card will open a pop-up with full title and link. Does that sound good?

**Comment by hao-fang** [comment]
With #303 -- the current tooltip shows the start&end time, which is nice! Thanks @tlikhit !
