### ISSUE TITLE
Create RocketChat channels for demo, SRW, CL, TACL papers

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#285]
**Number of Volunteers: 1**

The files are under `sitedata_acl2020`.
* srw_papers.csv
* demo_papers.csv
* cl_papers.csv
* tacl_papers.csv

I notice that I have used submission ID as the UID for SRW and Demo papers, although they have an Anthology ID. (The `main_papers.csv` still use the Anthology ID for UID.)
This is a little bit unfortunate but we should **NOT** change it now b/c our Zoom accounts have been created using these IDs.

cc @GuyAglionby @Robert-Alonso in case one of you can run this using the `acl2020-admin-bot`.

**Comment by GuyAglionby** [comment]
Done :)

**Comment by hao-fang** [comment]
@GuyAglionby  Thank you so much!
