### ISSUE TITLE
Workshop: Add time and zoom link for live sessions just like paper page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#296]
This is similar to the https://github.com/acl-org/acl-2020-virtual-conference/issues/295

Currently the workshop header looks like this

![image](https://user-images.githubusercontent.com/7291397/86056746-c2499000-ba12-11ea-8531-485f887fdb15.png)

Instead, we should make it more similar to each paper page where the time and the zoom link for the live session is displayed in the header

![image](https://user-images.githubusercontent.com/7291397/86056498-6b43bb00-ba12-11ea-938d-a603d8f764b3.png)

**Comment by hao-fang** [comment]
FYI @tlikhit -- this one and the #295 currently have higher priority which you can work on next.

**Comment by anaerobeth** [comment]
@raosudha89 I can help with this task if needed

**Comment by tlikhit** [comment]
@anaerobeth Please feel free to work on this and hmu if you get stuck  :)

**Comment by clefourrier** [comment]
@anaerobeth If you still want to work on this issue, could you please self assign? 
(Else feel free to assign me and I'll have a go at it ^^)

**Comment by anaerobeth** [comment]
Proposed workshop header with zoom link and session time:

<img width="985" alt="Screen Shot 2020-06-30 at 7 59 35 PM" src="https://user-images.githubusercontent.com/3663322/86188382-73802100-bb0c-11ea-8f8e-0164140f82f4.png">

I will need to add new columns for zoom_link, session1_time, session2_time to `workshops.csv`. Is there a link to a document with those values? Also, should the workshops page display the session times in the individual workshop cards?

**Comment by raosudha89** [comment]
@anaerobeth  You can find the start and end time of the live sessions for each workshop in their respective tabs in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=1154304671)

We still do not have the zoom links as yet. You can just fill those with https://zoom.com for now.

**Comment by anaerobeth** [comment]
Updated Workshop UI with the live session schedules and hardcoded zoom link:

<img width="985" alt="Screen Shot 2020-07-02 at 12 35 22 AM" src="https://user-images.githubusercontent.com/3663322/86316890-fcc25100-bbfb-11ea-8205-08f19e53188a.png">

**Comment by raosudha89** [comment]
Thanks @anaerobeth  :)

**Comment by raosudha89** [comment]
@anaerobeth  It looks like some workshop schedule is displayed incorrectly. Like W2 is from 9am to 1:30 PDT but it has been listed as 09:00-13:30 GMT. I haven't checked the other schedules. But please note that the schedule mentioned in [this spreadsheet](https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=1713259850) are in PST (and not GMT).

**Comment by raosudha89** [comment]
@anaerobeth  I created a new issue for this https://github.com/acl-org/acl-2020-virtual-conference/issues/405
