### ISSUE TITLE
Search by Track

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#30]
**Number of Volunteers**: 2

Enable web-interface shows (or allows searching) presentations organized by topic/track (though the topics are spread throughout the 3 days and various sessions).

I think this is basically supported by Mini-Conf. But we should double check with the PCs to see what they want.

UPDATE from PCs:

> The topic areas correspond to the tracks where the papers were reviewed.  A list of tracks can be found: https://acl2020.org/calls/papers/
> 
> So for each of the ten QA sessions each day, we will provide you a list of papers, authors, and their corresponding topic area/track. For the web interface, papers can be grouped together based on their topic area.

**Comment by hao-fang** [comment]
We probably can put these information on the "Schedule".
It might be too much work to implement "search-by-track". Alternatively, we can make track as a keyword.
Any thoughts?

**Comment by dpappas** [comment]
Hello!

If you also have some keywords for each track we could probably include them in the search. 
We could use keywords added by authors in their papers in similar tracks last year.
When the user enters a keyword, and the keyword matches with one we already have, we will return the parent track.

**Comment by hao-fang** [comment]
@dpappas I didn't know there are keywords in last year. Can you find some examples? 

We do have the "track" information in the https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/papers.csv 
I like the autocomplete function for track search, which seems promising.

I think a top priority here is to surface the "track" information either in the Schedule page, or in a separate webpage. This might depend on #74. If this is true, can you check with the volunteer in that comment to see how to coordinate?

**Comment by dpappas** [comment]
Hi Hao!

Since I could not find any keywords in the papers I grouped all papers per task and used SGRANK to extract some keywords automatically. 

I created this json file from the abstracts in the papers.csv file.
I tried to push it to the sitedata directory but as github mentions 

> Review required
> At least 1 approving review is required by reviewers with write access. 

I believe, during searching, these keywords could be used for autocomplete and the parent task could be returned. I have seen that multiple tasks share some keywords so maybe we could just narrow down to these. Additionally, we could also return the papers where this keyword was found.

**Comment by raosudha89** [comment]
Note from PCs
- [ ] In the search option, add 'search by track'.

**Comment by hao-fang** [comment]
@dpappas I merged the PR in the `sitedata_acl2020`. Can you see how you would implement the search-by-track function? Maybe give some examples? I'm still not sure how this would work.

**Comment by raosudha89** [comment]
- [ ] Student Research Workshop should be one of the tracks.

**Comment by hao-fang** [comment]
Closing this with #167 
We will need follow-up PRs to fix several issues.
