### ISSUE TITLE
Calendar: Do not change color on hover

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#306]
I found the changing of color to red on hovering over calendar elements to be a bit distracting. @hao-fang @tlikhit  What do you think? If you think it is okay, we can keep it.

**Comment by tlikhit** [comment]
I concur. Will remove or change to a milder color based on Hao's opinion.

**Comment by hao-fang** [comment]
@raosudha89 @tlikhit -- This is a fairly low priority issue. Let's first finish all other issues, i.e., the individual tutorial pages & workshop pages.

**Comment by hao-fang** [comment]
Closing this to clean up the issues.
