### ISSUE TITLE
Tutorials: Add SlidesLive video IDs for all prerecorded talks

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#309]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=1249246662) has  slideslive video ids for all pre-recorded tutorial talks. 

Embed this appropriately into tutorial page.

**Comment by raosudha89** [comment]
@goodmami  Please feel free to ask me if you have any questions.

**Comment by goodmami** [comment]
@raosudha89 the Tutorial sheet in the spreadsheet looks incomplete. It is missing
- T6, *Commonsense Reasoning for Natural Language Processing*, by Maarten Sap, Vered Shwartz, Antoine Bosselut, Yejin Choi, Dan Roth
- T7, *Integrating Ethics into the NLP Curriculum*, by Emily M. Bender, Dirk Hovy and Alexandra Schofield

T7 appears to be partially filled out, though. The main thing is I don't have a slideslive video id for T6.

**Comment by goodmami** [comment]
Sorry, it looks like maybe it doesn't have a prerecorded talk, according to the `virtual_format_description` column in `sitedata_acl2020/tutorials.csv`. But then there are several other tutorials that *do* have a slideslive ID in the spreadsheet but the CSV file says they do not (T2, T7, T8), so I don't know which information to trust.

For now I'll put in the slideslive video ids for those in the spreadsheet.

**Comment by raosudha89** [comment]
@goodmami  I just submitted a PR https://github.com/acl-org/acl-2020-virtual-conference/pull/323 for this issue. I had to do this asap and so I did it myself. Sorry to overstep you. But I realized you had some missing context to work on this. 

I will need your help to do a similar thing for workshops (https://github.com/acl-org/acl-2020-virtual-conference/issues/310). I will assign you on that issue.

**Comment by raosudha89** [comment]
Keeping this open because of the following issue. Waiting for slideslive people to respond to fix it.

T2, T4, T7, T8:  Video IDs are in the spreadsheet but when I embed into website, it is not getting displayed.

**Comment by raosudha89** [comment]
Tutorial chairs confirmed that T2, T6, T7, T8 do not have pre-recorded talks.
I have asked them about T4.

**Comment by raosudha89** [comment]
T4 video is now getting displayed correct. Closing this. We have a different issue for adding pdf links for tutorials https://github.com/acl-org/acl-2020-virtual-conference/issues/335
