### ISSUE TITLE
Workshops: Add Slideslive video IDs for pre-recorded talks

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#310]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=1249246662) has  slideslive video ids for all pre-recorded workshop talks. 

Embed this appropriately into each workshop page.

**Comment by raosudha89** [comment]
@goodmami  Can you check the changes I did for adding pre-recorded talks of W1 and W2 in this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/328 

and do the same for the following workshops: W11, W12, W13, W14, W15, W16, W17, W18, W19

**Comment by goodmami** [comment]
@raosudha89 on it.

Immediately I notice that W4 (BioNLP) is incomplete in the spreadsheet, with only about half of the accepted papers listed (compared to https://aclweb.org/aclwiki/BioNLP_Workshop), and with several typos, so I'll skip that one for now. Who do we contact to get complete information?

Then W16 and W19 look like they have all talks listed (though I don't have a good way to confirm), but there are no slideslive IDs.

I'll take care of the rest.

**Comment by goodmami** [comment]
(by "the rest" I mean W11 through W19)

**Comment by sudhra** [comment]
@goodmami  Thanks. Yes, some may be missing slideslive id. We will have to make a note here and update them later. 

Thanks for taking care of W11 to W19. Can you also do W20? 

I am taking care of W3 to W9 right now. If you are curious about my workflow, I do the following:
1. I go to the workshop tab on the [spreadsheet](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=2016111506)
2. I download the content of the tab as a csv file
3. I delete these two columns: email(s) of speaker(s) | SL_PRESENTATION_LINK
4. I rename other headers to UID, title, speakers, presentation_id
5. I then save it as w<num>_papers.csv (e.g. w1_papers.csv) under sitedata_acl2020
6. After doing this for all workshops, I submit a PR.

**Comment by goodmami** [comment]
> Can you also do W20?

Sure

> I do the following:

That's exactly what I'm doing :) Although W12 has an extra column indicating if the talk is live or prerecorded. I just removed that column, too.

**Comment by raosudha89** [comment]
@goodmami  sounds great :) thanks!

**Comment by raosudha89** [comment]
@goodmami  I have merged your PR. Can you do one thing before we close this? Can you list all workshops that have some issue with pre-recorded talks? i.e. missing slideslive id or missing some other value?

**Comment by goodmami** [comment]
Short of actually cross-referencing the lists with all the workshop programs (if they are published) or verifying individual slideslive videos, here's what I see:

- W4 (incomplete list)
- W5 (closing remarks missing a speaker; is this a problem?)
- W12 (best paper talk missing a speaker)
- W16 (missing all slideslive ids)
- W19 (missing all slideslive ids)

In addition some of the invited talks have "TBD" or similar as the title. I'm not sure if that's an issue.

**Comment by raosudha89** [comment]
@goodmami  Thanks! I will follow up on these.

**Comment by raosudha89** [comment]
@goodmami The missing IDs for W16 and W19 have been added now https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=1369416394

Can you update their csv files? Thanks.

**Comment by goodmami** [comment]
Done on the sitedata repo: https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/131

**Comment by raosudha89** [comment]
@goodmami  Thanks! I merged the PR.

**Comment by raosudha89** [comment]
W4 is missing ID for one video (talk by Liyan Xu) in this spreadsheet https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=747737888

I have asked Jarda about this. Once I get an answer, we can close this.

**Comment by goodmami** [comment]
@raosudha89 that one missing ID isn't the biggest problem, as I pointed out above. Here are some other issues:
- The title of Liyan Xu's talk is "Liyan Xu"
- Yuxia Wang's talk's title starts with "Title:" (it should not)
- Manirupa Das's talk has a typo ("for for")
- The spreadsheet lists 11 talks, which is **half** of the 22 listed on the [BioNLP workshop website](https://aclweb.org/aclwiki/BioNLP_Workshop), not including the 4 invited talks

**Comment by raosudha89** [comment]
@goodmami  Thanks for listing out the issues. 

- Since the video is missing for that talk, we cannot update its title. Once we have the video we can update it
- Can you fix that?
- Can you fix that too?
- I think some talks are only going to be livestreamed. So maybe for this workshop, they have only 11 pre-recorded talks and the rest they plan to show only in the live session.

**Comment by goodmami** [comment]
Ok that's fine. I fixed those problems and another one or two. See https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/158

I also noticed that Manirupa Das's talk was missing the phrase "and Automated Text Categorization" compared to the title at the workshop website. Given this and the other errors, it looks like it was edited in the spreadsheet after the fact. I did not re-insert this phrase because I don't know the reason for the edits, but I did fix the other problems.

**Comment by goodmami** [comment]
Forgot to add: I only fixed this in the .csv file on GitHub. I don't have permissions to change the spreadsheet. So please be aware of this if someone later re-extracts the info by downloading the csv file from the spreadsheet, as it would overwrite my changes.

**Comment by raosudha89** [comment]
The title of Liyan Xu's talk has been updated. Closing this since all pre-recorded talks have been added. Thanks @goodmami
