### ISSUE TITLE
Improve CONTRIBUTION-ACL2020.md

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#317]
**Number of volunteers**: 1-2

Can someone familiar with this repo make a pass on the CONTRIBUTION-ACL2020.md and see if there is any problem?
We will need to ask on-call volunteers during the conference to make adhoc changs.
Thanks!

**Comment by clefourrier** [comment]
@hao-fang 
- Setup environment: LGTM (though the virtualenv part could be restructured a bit for clarity, I can do it if needed)
- Pull request: LGTM
- Pages overview: Only talks about sponsors, **do we want to add other page types?**
- Deploy at AWS with login authentication: **Need to be done**
- FAQ: Almost empty, but I don't know the kind of info which would need to be added.

**Comment by hao-fang** [comment]
@clefourrier Thanks for taking a look!

> * Setup environment: LGTM (though the virtualenv part could be restructured a bit for clarity, I can do it if needed)

Yes, please help to make it better!

> * Pull request: LGTM

Cool!

> * Pages overview: Only talks about sponsors, **do we want to add other page types?**

Yes, if it is possible. But I don't know how hard it would be to write down the documents. I guess we should probably just tell which page corresponds to which html file under the `templates/` folder.

> * Deploy at AWS with login authentication: **Need to be done**

You can delete this one. GitHub action will automatically deploy the website to AWS for every PR merge.

> * FAQ: Almost empty, but I don't know the kind of info which would need to be added.

I guess there are some common errors which prevent people from passing the Github checks.
1. They need to run `make format` locally to auto-format some codes.
2. They can run `make` to run all checks locally and fix issues.

> I would also add a link to the README for the general MiniConf structure.

Sounds good.


Another thing I want to add is the `git submodule` stuff, which seems to have confused multiple people.
Basically, when we need to change anything under `sitedata_acl2020`, they should follow these steps.
1. Make changes in the `sitedata_acl2020` and creates a PR in that repo
```
cd acl-2020-virtual-conference/sitedata_acl2020
git checkout -b NEW_BRANCH
# make changes
git commit -am "blah"
git push
```
2. Wait for the PR in the `sitedata_acl2020` repo to be merged, and update your local submodule
```
cd acl-2020-virtual-conference/sitedata_acl2020
git checkout master 
git pull
```
3. Make changes in the main repo `acl-2020-virtual-conference` and create a PR in the main repo.
```
cd acl-2020-virtual-conference
git checkout -b NEW_BRANCH
# make changes
git commit -am "blah"
git push
```

You might want to explain why we need this private `sitedata_acl2020`, i.e., the files under the `sitedata_acl2020` contain some sensitive information, e.g., emails & zoom links, which should **not** be made to the public.

Let me know if you need more information. Thanks for your help!

**Comment by clefourrier** [comment]
Ok, I'll do it during the day!

**Comment by clefourrier** [comment]
@hao-fang Have a look, and tell me if more info is needed

**Comment by hao-fang** [comment]
@clefourrier -- thanks! I approved the PR with two minor comments. Can you fix them and merge the PR? Thanks!
