### ISSUE TITLE
Demo papers webpage

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#32]
**Number of Volunteers**: 1

Some demo papers will provide a link to their online demo.
Need to add the link to the webpage.

**Comment by GuyAglionby** [comment]
My idea here is to create a new csv which maps paper ID to demo link (so as not to clutter papers.csv), then add a (conditional) button to the regular poster template. Will go ahead with this in the next couple of days unless anyone has comments

**Comment by hao-fang** [comment]
> My idea here is to create a new csv which maps paper ID to demo link (so as not to clutter papers.csv), then add a (conditional) button to the regular poster template. Will go ahead with this in the next couple of days unless anyone has comments

This sounds like a good plan. Thanks!

**Comment by GuyAglionby** [comment]
@hao-fang is there anything else that needs doing on this issue?

**Comment by hao-fang** [comment]
@GuyAglionby We will need to replace the dummy demo file in `sitedata_acl2020` with the actual data. Let's keep this open for now. We will need to reach out to the demo chairs to get the information.
Do you want to keep working on this one? We can see if we can find another volunteer to take this one if you want to focus on other issues.

**Comment by hao-fang** [comment]
@GuyAglionby Sorry. I forgot we have another issue #72 to fill in the `sitedata_acl2020` and there is a volunteer working on that now.
I'll close this one.
