### ISSUE TITLE
BUG: Calendar view shows incorrect time on hovering over an event

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#320]
Emily Bender (from acl2020 committee) says: I noticed something odd about the calendar on virtual.acl2020.org: When I hover over an event, it shows me a pop-up window with time info that doesn’t match what’s in the calendar view (and also isn’t UTC). Do you know what this is supposed to be?

**Comment by tlikhit** [comment]
@raosudha89 Sorry, this should be fixed with #325
