### ISSUE TITLE
Append text to Queer in AI social event description

### ISSUE THREAD

**Issue by maartensap** [acl-org/acl-2020-virtual-conference#327]
Could some please update the queer in AI social event description (on https://virtual.acl2020.org/socials.html) to 

> The ACL QueerInAI social is an event for queer folks who work in NLP or AI to share their experiences, network with others, and discuss queer issues in research. To facilitate this, the social will involve a mix of mini-testimonials and breakout discussions. All event information will remain confidential to respect the privacy and safety of participants. People of all identities (including allies) are invited to attend!

diff: I've added the last sentence "People of all identities (including allies) are invited to attend!"

**Comment by hao-fang** [comment]
@prabhat1081 can you fix this one?

**Comment by hao-fang** [comment]
https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/152
