### ISSUE TITLE
[ON HOLD] Livestream Page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#33]
**Number of Volunteers**: TBD

We will livestream all plenary sessions on the main conference day.
Let's add a "Livestream" page which shows the livestream video and the schedule of the livestreaming events.

UPDATE: Need to get some details from SlidesLive.

**Comment by hao-fang** [comment]
@vladdy We still need to get some details from SlidesLive. I'll post more instructions later.

**Comment by raosudha89** [comment]
Note from meeting with PCs: maybe we don't have this separate tab since it is confusing. We can just highlight live sessions in the calendar under schedule tab.
