### ISSUE TITLE
Create RocketChat channels for workshops

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#332]
**Number of Volunteers: 2**

I'll share the acl2020-admin-bot account info with you to create these channels. There are 20 channels, one for each workshop.

**Comment by hao-fang** [comment]
#workshop-1-winlp
#workshop-2-iwslt
#workshop-3-NLP4ConvAI
#workshop-4-bionlp
#workshop-5-fever
#workshop-6-iwpt
#workshop-7-flp
#workshop-8-nuse
#workshop-9-alvr
#workshop-10-RepL4NLP
#workshop-11-nli
#workshop-12-wngt
#workshop-13-bea
#workshop-14-SIGMORPHON
#workshop-15
#workshop-16
#workshop-17
#workshop-18
#workshop-19
#workshop-20

**Comment by anaerobeth** [comment]
I can help with this task if needed. Let me know where to find relevant documentation for this task.

**Comment by hao-fang** [comment]
@anaerobeth I'll put you in touch with @finiteautomata via email

**Comment by anaerobeth** [comment]
Done creating public channels for W11-W20 and setting their topics and descriptions

**Comment by raosudha89** [comment]
I merged this PR https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/142

And created this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/364  for using the newly added channel names correctly.

**Comment by raosudha89** [comment]
@finiteautomata  Sorry I had revert your PR. You seem to have changed an older version of workshops.csv file.

Can you make sure you update your sitedata_acl2020 submodule to the latest version and then add rocketchat channel in that version? Thanks.

**Comment by anaerobeth** [comment]
@raosudha89 Let me know if you need me to update the workshops.csv file and create a new PR.
