### ISSUE TITLE
Update FAQ page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#334]
**Number of Volunteers: 1**

Change the General data protection FAQ on https://virtual.acl2020.org/about.html to be called "General Data Protection and Privacy" and add a sentence at the end saying "For more information on privacy practices of all the conference software, we encourage all attendees to consult the statements from each of the companies at https://zoom.us/privacy, https://slideslive.com/privacy-policy, and https://rocket.chat/privacy."

cc @dreasysnail

**Comment by Robert-Alonso** [comment]
Hi @hao-fang I can work on it :+1:

**Comment by hao-fang** [comment]
@Robert-Alonso  Thanks!

**Comment by Robert-Alonso** [comment]
Done :)
