### ISSUE TITLE
Add pdf links for some tutorials pages

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#335]
**Number of Volunteers: 2**

From Tutorial Chairs: The Tutorial pages will need some extra links to the tutorial material:
Links to Pdf slides for those tutorials which are not pre-recorded (T2, T6, T7, T8). We should have all the slides by tomorrow Wednesday). Let us know if you can also host the slides or if we should make a Google folder on our own.
Links to external tools like Doory (for brainstorming) for 1 or 2 tutorials (the tools are to be set up by the teachers themselves).

cc @raosudha89

**Comment by raosudha89** [comment]
@hao-fang  At this point, I think we should just post the slides as a link to a pdf. Not try to display the slides as a slideshow.

**Comment by raosudha89** [comment]
@hao-fang Can you forward me the email when they send this information?

**Comment by raosudha89** [comment]
@hao-fang  Sounds good.

**Comment by raosudha89** [comment]
Tutorial chair have given us the pdfs: https://drive.google.com/drive/folders/1b082SUDSqnkZTCggTJV3ymgMKav9-s6m

**Comment by raosudha89** [comment]
I am working on this.

**Comment by raosudha89** [comment]
Slides for T2, T7, T8 have been added using a 'Slides' link under main header. 

![image](https://user-images.githubusercontent.com/7291397/86398799-07f89980-bc5b-11ea-968b-b9bcf0ea1215.png)

However, T6 has multiple slide pdfs (under static/pdf/T6-Slides folder). I am not sure how to display multiple slide decks.

@hao-fang  Any suggestions as to which volunteer might be able to work on this?

**Comment by raosudha89** [comment]
@tlikhit  Do you have any ideas for how to do this?

**Comment by anaerobeth** [comment]
> However, T6 has multiple slide pdfs (under static/pdf/T6-Slides folder). I am not sure how to display multiple slide decks.

I took a stab at this and programmatically built an onclick event with the locations of the T6-files:
![open-multiple-slides](https://user-images.githubusercontent.com/3663322/86414703-bec43c00-bc92-11ea-82db-baa93da46db3.gif)


However, some browsers may prevent opening of multiple tabs at once (depending on pop up blocker or redirect settings). Another option is to allow downloading a zip file of the 6 slides.

**Comment by raosudha89** [comment]
@anaerobeth  Yes, opening multiple tabs automatically could be prevented in some browsers. And it could be confusing too since it is slightly uncommon. The option of downloading a zip file sounds good to me. Can you do that? Thanks

**Comment by raosudha89** [comment]
@anaerobeth  Thank you so much for fixing this. I have merged your PRs.
