### ISSUE TITLE
[Accessibility] The images besides the paper don't have alt-tags.

### ISSUE THREAD

**Issue by SushantKafle** [acl-org/acl-2020-virtual-conference#345]
The images besides the paper don't have alt-tags.

Solution: Provide alternate description to the images.

**Comment by anaerobeth** [comment]
@SushantKafle There is no information available for the images so we can only add something generic like "A representative figure from paper ..."

<img width="848" alt="Screen Shot 2020-07-06 at 10 11 30 AM" src="https://user-images.githubusercontent.com/3663322/86602927-5e264f00-bf71-11ea-8450-03be1e45b6f8.png">

**Comment by anaerobeth** [comment]
@SushantKafle Let me know if the commit referenced above works and I will open a PR. Thanks.

**Comment by hao-fang** [comment]
@anaerobeth If you have time to implement this, your proposal sounds good to me!
