### ISSUE TITLE
Add link to Dory on T1 tutorial page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#360]
Link should be called: Question and discussion topic collection via Dory
Link: https://www.dory.app/c/google.com/aaabb999_acl-20-interpretability-tutorial/questions

**Comment by anaerobeth** [comment]
@raosudha89  I can pick up this task. Do you want the link added after the tutorial description but before the Livestreaming block?

**Comment by raosudha89** [comment]
@anaerobeth Looks great. I merged your PR. You are awesome :) thanks!
