### ISSUE TITLE
make sure the scroll to the top when open the plenary session page from the calendar

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#365]
**Number of Volunteers: 1**

Currently, when using plenary_sessions.html#tab-july7 to open the plenary session page, it will focus in the middle, instead of 
the top.
I'm not sure how to fix this behavior.

**Comment by anaerobeth** [comment]
A quick way to do this is to move the ids to empty `div`s above the date block:

<img width="985" alt="Screen Shot 2020-07-02 at 12 35 22 AM" src="https://user-images.githubusercontent.com/3663322/86407879-e2cc5100-bc83-11ea-9557-2bcb2d44938a.png">

Demo:
![plenary-scroll-top](https://user-images.githubusercontent.com/3663322/86408197-861d6600-bc84-11ea-8e2e-f5e5915ef040.gif)


Alternatives would be setting the ids in nested divs or refactoring to use classes in the links.

**Comment by anaerobeth** [comment]
> ... or refactoring to use `classes` in the links.

Might not work if anchor links require `id`s to find the target `div`(ex. plenary_sessions.html#tab-july7)

**Comment by hao-fang** [comment]
@anaerobeth hmm yeah ... we need to make sure when clicking the calendar card, it brings us to the right date..

**Comment by anaerobeth** [comment]
The calendar card dives have their own `id`s separate from the anchor tag id:

<img width="522" alt="Screen Shot 2020-07-02 at 6 42 18 PM" src="https://user-images.githubusercontent.com/3663322/86415047-cd5f2300-bc93-11ea-99e0-6be1663cf574.png">

**Comment by hao-fang** [comment]
@anaerobeth Thank you so much!
Just FYI -- we are going to freeze the website at 11pm PST today. It's fine if this change didn't make to the 1.0 release.
You can still create and merge PRs, but those PRs will not be automatically deployed to the virtual.acl2020.org. We will manually do it during the conference.

**Comment by anaerobeth** [comment]
@hao-fang Alternate implementation where I created a `base_plenary.html` from `base.html` and added a window scroll after the script for hash tags finishes:

![plenary-scroll-to-top](https://user-images.githubusercontent.com/3663322/86479448-31c4c580-bd1a-11ea-9b84-7084196b2808.gif)

Note: Buggy behavior seen in about 1 out of 15 times I click the plenary links

**Comment by hao-fang** [comment]
@anaerobeth Thanks! Do you think we can merge this fix? Or do you suggest we wait and find the "right" solution?

**Comment by anaerobeth** [comment]
It is an improvement over the current behavior. We can always patch with something better when we have time.
