### ISSUE TITLE
Organizing Committee

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#37]
**Number of Volunteers**: 1

Should replace the committee information.
This needs to be done in the private sitedata repo https://github.com/acl-org/acl-2020-virtual-conference-sitedata.

**Comment by hao-fang** [comment]
@dreasysnail can you send the committee info to @sgdgp?
I think we just need to edit this file https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/committee.yml

@sgdgp The PR should be created in  https://github.com/acl-org/acl-2020-virtual-conference-sitedata/ first, and then we should bump the git submodule version in https://github.com/acl-org/acl-2020-virtual-conference repo.
You probably need to understand how `git submodule` works.

**Comment by sgdgp** [comment]
@hao-fang Thanks for the instructions. However [https://github.com/acl-org/acl-2020-virtual-conference-sitedata/](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/) shows 404 error, I guess I am not added in that repo yet.

**Comment by hao-fang** [comment]
> @hao-fang Thanks for the instructions. However https://github.com/acl-org/acl-2020-virtual-conference-sitedata/ shows 404 error, I guess I am not added in that repo yet.

@sgdgp I just added you to that repo. Can you try again?

**Comment by sgdgp** [comment]
@hao-fang Yeah I can access it now. Thanks!

**Comment by sgdgp** [comment]
@hao-fang Should I take the committee info from [https://acl2020.org/committees/organization](https://acl2020.org/committees/organization). Is there any particular profile image provided by the members beforehand or should I use from the personal websites etc. ?

**Comment by hao-fang** [comment]
@ardakdemir I un-assigned you from this issue because @sgdgp has started working on it.
I now added a "Number of Volunteers" section at the beginning for each issue. Sorry for the confusion. I'll also send a clarification email to our mailing list soon.
