### ISSUE TITLE
Workshop: Open each workshop paper talk in a new page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#370]
Currently, all pre-recorded talks of a workshop are all displayed in one page (e.g. https://virtual.acl2020.org/workshop_W1.html has about 50 talks all in one page).

Can we instead have a separate page for each talk and just have a link to that page in the main page?

**Comment by raosudha89** [comment]
We need to do this asap for W1 since it is scheduled on July 5.

**Comment by raosudha89** [comment]
@tlikhit  Can you see if you can work on this? Thanks.

**Comment by tlikhit** [comment]
@raosudha89 Sure! Will each talk have content other than the slideslive embed? If not, what do you think about just loading the talk below the title on click?

**Comment by raosudha89** [comment]
@tlikhit  Each talk just have title, speakers and the video. 

When you say load on click, do you mean like on click it will show the video and otherwise it will be hidden? We just need to be able to not load all talks by default. If this helps in that, then yes, sounds great. 

We need this done in next few hours please. thanks.

**Comment by raosudha89** [comment]
Attendee asked for this too on rocketchat:

[Website] I wish you hadn't embedded the videos in the main WiNLP page. It takes so long to be loaded.

https://acl2020.rocket.chat/channel/helpdesk?msg=FskwnezzHbjRMJtF7

**Comment by tlikhit** [comment]
@raosudha89 Yeah, that's what I meant. Should I also make it so that there is only one presentation playing at a time? i.e. if a presentation is currently playing and another presentation is clicked it closes the current one

**Comment by anaerobeth** [comment]
@raosudha89 @tlikhit If page load time is a problem for pages like W1, n alternative would be to display links to open the videos in separate tabs:

![open-video-in-new-tab](https://user-images.githubusercontent.com/3663322/86498506-170f4280-bd54-11ea-85db-2d6c0efcceaa.gif)

**Comment by raosudha89** [comment]
> @raosudha89 @tlikhit If page load time is a problem for pages like W1, an alternative would be to display links to open the videos in separate tabs:
> 

I am not sure about this since we don't want them to watch it on slideslive webpage rather watch it on acl webpage.

**Comment by raosudha89** [comment]
> @raosudha89 Yeah, that's what I meant. Should I also make it so that there is only one presentation playing at a time? i.e. if a presentation is currently playing and another presentation is clicked it closes the current one

That sounds like a good idea. Thanks.

**Comment by tlikhit** [comment]
@raosudha89 Got it! I'm looking at some other optimizations to reduce load time. For example, the slideslive embed script is ~500kb and is being loaded inside a loop. Will see if I can find anything else and push 👍

**Comment by raosudha89** [comment]
@tlikhit  Sounds good. Hope we can push this change in today's release. Tagging @hao-fang to check this PR before he does the release for tonight.

**Comment by raosudha89** [comment]
@tlikhit  I am testing your solution right now and I am seeing some issues. 

- As I am watching one video, if I click another video, the first one collapses, but the audio continues
- Also sometimes when I go back to the first video, intermittently, the video becomes smaller and smaller until it disappears

I wonder if these things are happening because we are trying to collapse first video when starting another video. Maybe we don't try to do that?

**Comment by tlikhit** [comment]
#442 should fix this. Sorry, I couldn't debug properly earlier because all embeds were buffering for me. Also, would you prefer to not collapse the first video before starting another?
