### ISSUE TITLE
Workshops: Add detailed scheduled of W7 to W20

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#371]
W7 to W20 workshops are all is currently missing detailed scheduled. 

The schedule of each workshop can be found in its tab in [this spreadsheet](https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=646602401).

Check how this is done for W1 to W6 in workshops_schedule.json

**Comment by raosudha89** [comment]
@tlikhit  When you add the detailed schedule of W7, can you check this https://github.com/acl-org/acl-2020-virtual-conference/issues/448 ?

Their last keynote has a separate zoom link that we need to post in the schedule.

**Comment by raosudha89** [comment]
W7 to W19 (bar W15 since it has some discrepancies) have been added https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/203

**Comment by parry2403** [comment]
@raosudha89 I have updated the spreadsheet. Can you provide inputs on what is missing for W15 ?
https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=646602401

**Comment by tlikhit** [comment]
Updated W15. Only W20 remains to be updated now, waiting on the schedule from their end.

**Comment by parry2403** [comment]
When will this reflect on the website  ?

**Comment by tlikhit** [comment]
@parry2403 The website should be updated now!

**Comment by parry2403** [comment]
Detailed Schedule is not visible again.
