### ISSUE TITLE
Workshops: Verify that all pre-recorded talks are displayed correctly

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#373]
I found that some pre-recorded talks just keep loading and never show the video. For e.g.

- W8 : Talk by Andrew
- W8: Talk by Kathleen
- W15: Talk by Steven

Not sure if its a slideslive video error or just my browser being slow to load videos.

**Comment by anaerobeth** [comment]
I tested loading the videos in Chrome Version 80.0.3987, Firefox 72.0.2 and Safari 11.0.2 

The following videos are stuck in loading:
W8: Andrew, Kathleen and Andress
W15: Steven and Kass-hout

**Comment by raosudha89** [comment]
@anaerobeth  Thanks for the detailed list. Can you check on the 'others' tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1RDUVoKz2qy8JSwMjJPDyzQ8-x7UnxJhLQadrf-MMnwU/edit#gid=1412903199) the status of these videos? If they are still 'incoming' that means they are yet to be uploaded. But if they are 'finished' then we will need to contact slideslive to see why they aren't loading.

**Comment by anaerobeth** [comment]
Status of videos:
W1: Gina-not recording, Catherine-uploaded
W3: Olabiyi-returned
W4: Liyan-finished
W11: Monica-not recording
W14: Clara-finished  **
W17: Parsale-uploaded, Sara-uploaded

All the rest are still 'incoming' . 

** W14: Clara is the only one marked 'finished' but does not load. It's presentation id is 38929866 but it's slideslive link in the spreadsheet is https://slideslive.com/38929867

**Comment by raosudha89** [comment]
@anaerobeth  Thanks! 

Regarding W14: Clara -- can you fix the presentation id in w14_papers.csv file?

Regarding W4: Liyan -- you marked this finished too. Is it an id mismatch as well?

**Comment by anaerobeth** [comment]
I'll update the link for W14: Clara. 
I removed W4: Liyan from the list since it loads OK now

**Comment by anaerobeth** [comment]
@raosudha89 Looks like Google sheet records are swapped out for Clara and Jane.
In the in the Google sheet:
W14 SIGMORPHON | W1402 | finished | Recursive Schemes for Phonological Analysis | Clara Vania | slideslive.com/38929867
W14 SIGMORPHON | W1401 | incoming | On Understanding Character-level Models for Representing Morphology | Jane Ch, lee | slideslive.com/38929866

In w14_papers.csv
  1 UID,title,speakers,presentation_id
  2 W1401,On Understanding Character-level Models for Representing Morphology,Clara Vania,38929866
  3 W1402,Recursive Schemes for Phonological Analysis,Jane Chandlee,38929867

Google search for "Recursive Schemes for Phonological Analysis" gives Jane Chandlee as author while 
search for "On Understanding Character-level Models for Representing Morphology" gives Clara Vania. 

38929866 is incoming and it's video does not display as expected. I think it is the Google sheet that is inaccurate.

**Comment by ozancaglayan** [comment]
The link to `Audio-Visual Understanding of Passenger Intents for In-Cabin Conversational Agents` talk at https://virtual.acl2020.org/workshop_W1.html is wrong, i.e. it opens another talk. The link below from the google sheets is correct:

https://slideslive.com/38931265/audiovisual-understanding-of-passenger-intents-for-incabin-conversational-agents
