### ISSUE TITLE
[RocketChat] Channels list often shuffle itself

### ISSUE THREAD

**Issue by sanxing-chen** [acl-org/acl-2020-virtual-conference#393]
The channels list on the left of the panel frequently shuffles itself, after some animation the order seems to be unchanged.

The issue occurs in both Safari, Edge browser, and client in macOS, and the animation is synchronous across clients.

One minor issue: link for downloading the desktop version of rocket chat in https://acl2020.rocket.chat/home is incorrect, should be https://rocket.chat/install/.

**Comment by clefourrier** [comment]
I can confirm this behavior on Firefox and Chrome.

**Comment by sanxing-chen** [comment]
This can be solved by changing the order channels by alphabet rather than activities in the user side. But it’s still unclear why there’s invisible activity. Providing an instruction to users could be helpful.

https://twitter.com/emmasmanning/status/1279089238877888512?s=21

**Comment by hao-fang** [comment]
@sanxing-chen  @clefourrier If you choose sort by `activity`, should it always put the most recent updated channels on top? Sorry I may have misunderstood this ..

**Comment by clefourrier** [comment]
@hao-fang The problem is that the server seems to "check" on each channel (by reordering them) even when no new activity happened.

**Comment by hao-fang** [comment]
@clefourrier I see. I think I know why this happens. I have hide all system messages (e.g., new user joins a channel) but the RocketChat must have treated those system messages as new activity. So it keeps shuffle the list.

I have now make the "default user preference" to be sort by alphabetical. Hope this will help new users.
![image](https://user-images.githubusercontent.com/9957482/86509172-d8e94180-bd9a-11ea-8601-2f0a471342a5.png)
