### ISSUE TITLE
Sponsors: Live page does not contain any logo/link towards sponsor spaces

### ISSUE THREAD

**Issue by clefourrier** [acl-org/acl-2020-virtual-conference#394]
The sponsors page seems to be broken on the live website: the logos are not visible, and though it's possible to hover above, they do not redirect anywhere.

![image](https://user-images.githubusercontent.com/22726840/86483444-5e95ce80-bd54-11ea-9cbd-7a0281393e73.png)

**Comment by sanxing-chen** [comment]
It looks good in my client, try maybe refresh cache?

![image](https://user-images.githubusercontent.com/18565449/86484262-d3044980-bd23-11ea-8241-c6d052f0fa26.png)

**Comment by clefourrier** [comment]
Cache problem, closing the issue.
Thks @sanxing-chen
