### ISSUE TITLE
Set up Google Analytics so can report Page Views

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#40]
**Number of Volunteers**: 1

**Comment by hao-fang** [comment]
@ppartha03 Thanks for working on this! Let me know if you need additional information.
I imagine this will be inserted somewhere in the [base.html](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/templates/base.html).

**Comment by hao-fang** [comment]
@ppartha03 any updates on this?

**Comment by tlikhit** [comment]
@hao-fang Should I work on this?

**Comment by hao-fang** [comment]
@tlikhit This is low priority, but if you can figure out the current status then it would be good. My guess is that we only need to set the ID in `config.google_analytics_id` but I didn't dive into this.
