### ISSUE TITLE
Corrections on the WiNLP page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#400]
Rename FFR v1.0 to FFR v1.1 on WiNLP workshop https://virtual.acl2020.org/workshop_W1.html

**Comment by raosudha89** [comment]
1. The website shows the schedule from 9 am - 2 am PDT .
https://virtual.acl2020.org/workshop_W1.html

However, the workshop runs from 9 am - 4:15 pm PDT, according to the schedule on the spreadsheet. 
https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit?pli=1#gid=936853935

Would you please help correct that?

2. Also, our organizer list is 
Rossana Cunha, Samira Shaikh, Erika Varis, Ryan Georgi, Antonios Anastasopoulos, Khyathi Raghavi Chandu and Alicia Tsai

which is incorrect on the website: 
Samira Shaikh, Rossana da Cunha Silva, Ann Clifton, Erika Doggett and Ryan Georgi

**Comment by raosudha89** [comment]
This has been fixed now.
