### ISSUE TITLE
Workshop schedules are displayed incorrectly 

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#405]
@anaerobeth It looks like all workshop schedules are displayed incorrectly. Like W2 is from 9am to 1:30 PDT but it has been listed as 09:00-13:30 GMT. Please note that we should be using the schedule mentioned in [this spreadsheet](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=1102315556) and they are in PST (and not GMT).

If some schedule in missing in that spreadsheet, then we need to check [this older spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=402639445)

**Comment by raosudha89** [comment]
@anaerobeth  I will start working on this since several workshop organizers are emailing us.

**Comment by anaerobeth** [comment]
OK please go ahead. Apologies for not getting to this sooner.

**Comment by raosudha89** [comment]
@anaerobeth  No worries. I am working on it now.

**Comment by raosudha89** [comment]
Required PRs have been merged.
