### ISSUE TITLE
RocketChat requests

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#414]
Used to summarize all RocketChat related requests.

**Comment by hao-fang** [comment]
https://acl2020.rocket.chat/channel/helpdesk?msg=jaARc347Y4omdBEKG

[RocketChat] Hi, is it possible to become admins of our paper's channels? For instance if I'd like to add a link to the code in the description, or pin a message. (incidentally it seems like the abstract in the channel description comes from the submitted version of the paper, not the camera ready)

**Comment by ozancaglayan** [comment]
Is it only me who can't login to RocketChat at all? It says, "Login with your ACL2020 account" and when I click, the throbber spins a bit and stops, and that's all.

**Comment by hao-fang** [comment]
@ozancaglayan Can you try below?

![image](https://user-images.githubusercontent.com/9957482/86508898-a3dbef80-bd98-11ea-9f27-86eefa8328c2.png)
We have added this to https://virtual.acl2020.org/about.html.

**Comment by ozancaglayan** [comment]
Ok, sorry, I did disable Ad-blocker but did not notice that this required enabling cookies which are marked to be "tracking cookies". Thanks.
