### ISSUE TITLE
Better way to embed videos for workshop papers

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#416]
[Website] I wish you hadn't embedded the videos in the main WiNLP page. It takes so long to be loaded.

https://acl2020.rocket.chat/channel/helpdesk?msg=FskwnezzHbjRMJtF7

**Comment by raosudha89** [comment]
This is a duplicate of https://github.com/acl-org/acl-2020-virtual-conference/issues/370
