### ISSUE TITLE
Update FAQ with the login issue

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#421]
Q: After I login to the main site, if I click on the "Login with ACL2020 account" button on any page (such as Chat), the circular spinner shows up but freezes and nothing else happens.

![image](https://user-images.githubusercontent.com/9957482/86498600-5da47300-bd3b-11ea-85a9-319a668bad4d.png)

Two possible reasons:
1) the pop-up windows are blocked
2) need to allow third party cookies

**Comment by raosudha89** [comment]
@hao-fang  I added it to the common Issue i made for many FAQs https://github.com/acl-org/acl-2020-virtual-conference/issues/398
