### ISSUE TITLE
[Plenary] add date and show time in local timezone in plenary session pages

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#424]
Currently date is missing

![image](https://user-images.githubusercontent.com/9957482/86499861-2ab1ad80-bd42-11ea-846b-cc402b967e5f.png)

Also, the time is hard coded in GMT and PDT. Instead use the code from paper page/workshop page to display time in GMT and local timezone.

**Comment by raosudha89** [comment]
I am working on this.

**Comment by raosudha89** [comment]
I added the day. I wasn't able to add time in local timezone. That still needs to be fixed.
