### ISSUE TITLE
Fix paper abstract for main.249

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#427]
**Volunteers: 1**

https://acl2020.rocket.chat/channel/presenter-helpdesk?msg=kruC8hoeTXLon4Gnj

> Hi, this is not a critical issue but the abstract for my paper on the website (https://virtual.acl2020.org/paper_main.249.html) seems to be from an earlier version of the paper (possibly the abstract we first submitted for review). The main difference in my case is that it says "(Our code will be made publicly available on publication.)" instead of "Code to reproduce our experiments is available at https://github.com/neulab/RIPPLe." (in the pdf at https://www.aclweb.org/anthology/2020.acl-main.249.pdf). This might be more of an issue for other papers though.

**Comment by anaerobeth** [comment]
@hao-fang I can pick up this task
