### ISSUE TITLE
[W7] Update timing and add zoom link to keynote

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#448]
W7 organizer says: 

There are three issues with the schedule and the workshop page on the
ACL virtual conference website:

1. We have an invited talk at 2pm, which we run as a separate zoom
session ourselves and it would need to be listed on the workshop's
virtual page (so that people know that it's happening and how to
access it; see below).

2. The current end time of the workshop listed on the website is 2pm,
but should be corrected to 3pm (after the invited talk).

3. info for our Keynote for the FLP workshop. 

14:00-15:00 PDT Invited talk: Marilyn Walker: Generating Expressive Language by Mining User Reviews

Join Zoom Meeting: (redacted)

**Comment by raosudha89** [comment]
The workshop schedule has been added - acl-org/acl-2020-virtual-conference-sitedata#203

The zoom link is still to be added.

**Comment by eshutova** [comment]
Hi Soudha,

Thanks a lot for adding the schedule! Two issues:

1. The keynote at 2pm is still not there.
2. At the bottom of the schedule, there is a link to livestream, which points to some NeuroIPS 2019 presentation. So I guess there is typo in some link.

Thanks a lot!
Katia

**Comment by raosudha89** [comment]
1. @tlikhit  Can you fix this? We need to include the last keynote from 2pm-3pm as stated here https://sites.google.com/view/figlang2020/workshop-program?authuser=0

2. @eshutova   We are yet to receive the livestream ID for workshops from SlidesLive. Right now the link included is a placeholder. It will be fixed once SlidesLive give us the ID. Please follow https://github.com/acl-org/acl-2020-virtual-conference/issues/339
