### ISSUE TITLE
[T8] Update slides

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#449]
Dear tutorial chairs, 

Can you help us remove the "slides" link from our website ASAP (see the screenshot): 
https://virtual.acl2020.org/tutorial_T8.html
It is only linked to a 2-page version and I start receiving messages about this. I already uploaded all the slides to the Github link: https://github.com/danqi/acl2020-openqa-tutorial so removing it is better.

One quick thing - I wonder if we can customize our page similar to the T6 website (see the screenshot) so we can have a table of sections and links to all the slides there too? Please let me know what format I should follow and I can send you all the information soon.

Thank you again for your help!

Best,
Danqi

**Comment by danqi** [comment]
@raosudha89 Thank you so much for the help!

This looks great!  Can you maybe also help us add one more speaker column?

The order of the 8 parts are:
Danqi Chen
Scott Yih
Scott Yih
Danqi Chen
Danqi Chen
Danqi Chen
Scott Yih
Scott Yih

**Comment by raosudha89** [comment]
Done. This is should be reflected upon today's website release. 

![image](https://user-images.githubusercontent.com/7291397/86523320-78501800-be1f-11ea-9029-ebb41f73a8d6.png)
