### ISSUE TITLE
Update socials on schedule page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#454]
Here are the sessions along with the timeslots.
S3: 1-2pm PDT on July 6
S4: 10-11pm PDT on July 6
S5: 11am-Noon PDT on July 7
S6: 1-2pm PDT on July 7
 
You can just call them Birds of a Feather (Session number).

**Comment by prabhat1081** [comment]
@raosudha89  PR for the update: https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/190

**Comment by raosudha89** [comment]
Thanks @prabhat1081  Merged.
