### ISSUE TITLE
Create general RocketChat channels

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#46]
**Number of Volunteers**: 4

- [ ] Get the list of channels from PCs (should ask them to give a short description of the channels)
   - [x] a channel for each paper #38 
   - [x] invited speaker Kathy McKeown 
   - [x] invited speaker Josh Tenenbaum
   - [ ] LTA award
   - [ ] DSA and ToT live
   - [x] Business meeting
   - [x] Review meeting
   - [ ] general PC channel (check with PCs if this should be private or not)
- [x] Create RocketChat channels for all sponsors (if needed), see #25 
- [x] Ask/Help tutorial chairs to create their own channels
- [ ] Ask/Help workshop chairs to create their own channels
- [ ] Ask/Help D&I chairs to create their own channels

### UPDATE (2020-06-15)
~~Still need to figure out the #62 and what channels are needed. Will come back on this issue later.~~

**Comment by luanyi** [comment]
Talk to RocketChat people and see how to give sponsors permission to invite people to their channal only. @hao-fang

**Comment by hao-fang** [comment]
> Talk to RocketChat people and see how to give sponsors permission to invite people to their channel only. @hao-fang

This is not possible now because we go through our AWS Cognito user pool for login authentication. They will need to provide the emails for people they want to invite and we will create the account for them manually. There is no automatic sign-up option right now.

For future reference -- this will be further discussed in #62, i.e., granting the right permission to different roles so that they can manage their channels with the "owner" permission.

The login issue will be discussed in #55, which I decide to use a manual process right now. But if we can figure out a way to do sign-up + manual verification, this might be slightly better.
