### ISSUE TITLE
Display CART captions for plenary Q+As

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#463]
From Caption Chairs:

we think the better solution is to add the iframe code under the Livestream video, either above or to the side of the Live Chat. We recommend reducing the default font size to 24 or so (replacing “fs=48” to “fs=24”) in the code in the iframe (default font size is larger than other font sizes on the website) and the iframe width and height can also be changed in the code. 

As a backup, you can also announce the other URL to attendees if there’s an issue..

Below is a screenshot of trying the iframe option out using the changed parameters below (highlighted in yellow):

<iframe src="http://www.streamtext.net/text.aspx?event=ACSDEMO&chat=false&controls=true&header=true&footer=true&ff=arial&fs=24&bgc=000000&fgc=ffffff&spacing=1.5" marginwidth="0px" marginheight="0px" scrolling="no" frameborder="0" class="style7" id="stFrame" style="width:950px;height:250px">  </iframe>

![cart-captions](https://user-images.githubusercontent.com/7291397/86523412-dcbfa700-be20-11ea-98bd-58a7422baaeb.png)

**Comment by hao-fang** [comment]
Would be nice to do something based on this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/466
* By default "hide/header"
* Change the "Caption" button to be "Show/Hide Caption".

**Comment by ananyaganesh** [comment]
Thank you for implementing this!

Note: `event=ACSDEMO` should be changed to `event=ACLCONFERENCE` for live captions. 

Also, would it be possible to display the following text in a sidebar on the webpage where the livestream for plenary sessions will be played?

> Live CART captions for plenary Q&A sessions (provided by ACS Captions)
> Note: Due to technical reasons, captions may show with a delay of 30-60 seconds
> If you experience issues viewing the CART captions in the window below, you can alternatively use this link to open them in > a separate browser tab: `https://www.streamtext.net/player?event=ACLCONFERENCE`
