### ISSUE TITLE
Share link to Anthology pages (rather than Anthology pdfs)

### ISSUE THREAD

**Issue by emilymbender** [acl-org/acl-2020-virtual-conference#465]
A request that came in over Twitter:

Brilliant thx. Any chance it would be easy to add a share option on the virtual site that can be used to copy title plus anthology link for pasting elsewhere? Current link is great but goes to the PDF instead of the corresponding web page.
https://twitter.com/benhachey/status/1279609714758660096

**Comment by emilymbender** [comment]
I replied: 

I will forward the suggestion. Meanwhile, you can easily get to the Anthology pages by just removing the .pdf at the end of the URL.

**Comment by hao-fang** [comment]
@emilymbender Thanks for replying the person! I just saw this.
We could add a button to get to the Anthology pages, but there are some CL & TACL papers that do not have Anthology pages right now.

To volunteers: you can probably just add add a link to "Anthology" by simply removing the ".pdf" in the URL, Just need to make sure to check the URL first and only do this for `https://www.aclweb.org/anthology/` links.
