### ISSUE TITLE
Wrong Author Order in the Pre-record Talk

### ISSUE THREAD

**Issue by ranyd18** [acl-org/acl-2020-virtual-conference#469]
Zhepei Wei reported through acl2020-virtual-helpdesk google group that in the extra preface added to the slides where the title and authors are presented, the order of authors is wrong. 

The correct order should be as below:

Zhepei Wei, Jianlin Su, Yue Wang, Yuan Tian, Yi Chang

**Comment by americast** [comment]
I believe SlidesLive has kept the author names in lexicographical order in the preface slide for all the presentations. :confused:

**Comment by ranyd18** [comment]
Hello Sayan,

Thanks for the reply. Is there any way we could change it? If not, i will
get back to the author who reported this issue.

Best,
Yiding

**Comment by americast** [comment]
Hi @ranyd18! I don't think we can make the change by issuing any patch in this repo. We would have to contact SlidesLive to make the change from their end. He has been contacted on chat, so let's hope this issue gets resolved soon! :smiley:

**Comment by ranyd18** [comment]
Hello Sayan,

Thanks for the prompt response! I will update the authors with this
information.

Best,
Yiding
