### ISSUE TITLE
Fix presenter name in SocialNLP virtual site

### ISSUE THREAD

**Issue by americast** [acl-org/acl-2020-virtual-conference#472]
Hi everyone,

  The presenter name for the paper `NARMADA: Need and Available Resource Managing Assistant for Disasters and Adversities` in `W17: Natural Language Processing for Social Media (SocialNLP)` needs to be changed to `Sayan Sinha`. It would be great if this could be addressed quickly.

Link: https://virtual.acl2020.org/workshop_W17.html#

@raosudha89 Given that I am also a volunteer, I am willing to issue a quick fix for this issue in the data repo. I would need access to the same.

Thanks!

**Comment by hao-fang** [comment]
@americast I have just granted you the access to both repos. Please submit a PR to fix https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/w17_papers.csv

See [here](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING-ACL2020.md#how-to-create-a-pull-request-for-the-website-acl-2020-virtual-conference-and-the-data-sitedata_acl2020) for instructions.

**Comment by americast** [comment]
Thanks @hao-fang! I just sent a patch. I shall send another PR in this repo updating the submodule when it gets approved and merged.

**Comment by raosudha89** [comment]
@americast  I have merged your PR https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/198
