### ISSUE TITLE
Schedule time zone adjustment doesn't hold when switching pages

### ISSUE THREAD

**Issue by savary** [acl-org/acl-2020-virtual-conference#476]
A tutorial teacher signaled that when the timezone is adjusted here:
https://virtual.acl2020.org/schedule.html 
and then we go to the tutorial page:
https://virtual.acl2020.org/tutorials.html
the timezone is again local (not adjusted).

**Comment by raosudha89** [comment]
The timezone change has to be done on each page separately. As of now we don't have the feature to get the change reflected on other pages.

**Comment by savary** [comment]
Sure. Thanks anyway!
