### ISSUE TITLE
Tutorial #3 (reviewing): adding material (pdf files)

### ISSUE THREAD

**Issue by kaagithub** [acl-org/acl-2020-virtual-conference#478]
Hi,
We need our material to be on the web site ASAP! 
[Paper42_Reviews.pdf](https://github.com/acl-org/acl-2020-virtual-conference/files/4874615/Paper42_Reviews.pdf)
[Paper42.pdf](https://github.com/acl-org/acl-2020-virtual-conference/files/4874616/Paper42.pdf)

**Comment by raosudha89** [comment]
It has been added under 'Slides' of https://virtual.acl2020.org/tutorial_T3.html

**Comment by savary** [comment]
I see. "Exercises" would be a more accurate title than "Slides". But I'll tell the authors that the link is there.
Thanks!

**Comment by raosudha89** [comment]
We can update it in tonight's release. But yes, for now, please let authors know. Thanks.

**Comment by savary** [comment]
Sorry, there previous link was non permanent. Please, replace the linked under "Material" by:
https://github.com/reviewingNLP/ACL2020T3material
Thanks!
