### ISSUE TITLE
Add link to the tutorial modalities

### ISSUE THREAD

**Issue by savary** [acl-org/acl-2020-virtual-conference#481]
Please, add the link to this new post:
https://acl2020.org/blog/detailed-modalities-of-tutorials/
from two tutorial pages:
https://acl2020.org/program/tutorials/
https://virtual.acl2020.org/tutorials.html
Thanks!

**Comment by raosudha89** [comment]
Hi Agata,

We have added it here https://acl2020.org/program/tutorials/

We couldn't add it in time for our yesterday's release of the virtual website. So as a workaround, I added a link to the new blog post in the [old blog post](https://acl2020.org/blog/intro-to-tutorial-infrastructure/) that is linked on https://virtual.acl2020.org/tutorials.html

**Comment by savary** [comment]
Sure, thanks!
