### ISSUE TITLE
[Paper] Wrong author info in video thumbnails

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#485]
I am Manling, an author of main conference paper (submission #47, webpage https://virtual.acl2020.org/paper_main.230.html). It seems that the author order in the video thumbnails is wrong. Our author order is `Manling Li, Alireza Zareian, Qi Zeng, Spencer Whitehead, Di Lu, Heng Ji, Shih-Fu Chang`. By any chance, is it possible to update to the correct author order? Thank you so much!

**Comment by hao-fang** [comment]
See [this](https://acl2020.rocket.chat/channel/announcements?msg=wzgBhNbPSSSMRXNFY).

We can probably add a sentence in the paper page.
> The ACL 2020 website uses SlidesLive to display the content for each paper. Unfortunately, we don't have control over the presented order of authors, so please check the Anthology or the paper pdf for the correct order!
