### ISSUE TITLE
[W14] Update organizers list

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#487]
Hi All - somehow, one of the co-chairs for W14 - SIGMORPHON was left off the workshop description - Our three organizers are myself, Kyle Gorman, and Ryan Cotterell, but Ryan's name doesn't appear.  If someone could please fix that, it would be appreciated.  Thank you!

Garrett Nicolai

**Comment by anaerobeth** [comment]
@raosudha89 I can do this update

**Comment by raosudha89** [comment]
Thanks @anaerobeth
