### ISSUE TITLE
[W5] Update speaker name

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#488]
Hi Sudha, Hao,

One of our presenters informed us that the listing on the schedule of W-5 FEVER shows the wrong speaker. For the paper "Simple Compounded-Label Training for Fact Extraction and Verification" (https://slideslive.com/38929663; ID 9 in the spreadsheet) show Yixin Nie as the speaker, but it should be Lisa Bauer. I have made the change in the spreadsheet - would it be possible to change it in the virtual schedule?

Thanks
Christos

**Comment by anaerobeth** [comment]
@raosudha89 I can do this update

**Comment by raosudha89** [comment]
Thanks @anaerobeth
