### ISSUE TITLE
Updating authors of D&I Financial Access blog post

### ISSUE THREAD

**Issue by vinodkpg** [acl-org/acl-2020-virtual-conference#490]
Hi Sudha & Yizhe (or others),

Could you please update the author line of ACL D&I financial subcommittee efforts as follows (preferably in two lines):

D&I Financial Access Chairs 
Tirthankar Ghosal, Allyson Ettinger & Ryan Georgi

Here's the blog link:
https://acl2020.org/blog/increasing-financial-accessibility/

Also, if possible, please correct the short note on the main acl2020 page:
"July 4, 2020. Checkout the new blogpost by diversity & inclusion chairs describing their initiative for increasing financial accessibility of ACL2020."
to
"July 4, 2020. Checkout the new blogpost by D&I financial access chairs describing their initiative for increasing financial accessibility of ACL2020."

Vinod & Cissi

**Comment by raosudha89** [comment]
Done https://acl2020.org/blog/increasing-financial-accessibility/

**Comment by vinodkpg** [comment]
Sudha, so sorry to open this again. We found an error in the blog post; since it concerns the Sponsors, we want to fix it ASAP. Could you please change in the last para:

"financial subsidies to more than 80 conference participants." --->  "financial subsidies to more than 80 conference participants and writing support to over a thousand authors." 

I have also updated the original doc here, if you want to refer: https://docs.google.com/document/d/1uosxMoeWuHMhc8Sf5VQfQgKfHozEghyIZwbCqXCc_j0/edit?ts=5ef3b3d4#

I also noticed that there is a huge gap between the Figures and corresponding captions. Is there a way you can reduce it? Not a big deal if it is too much effort. 

Vinod
