### ISSUE TITLE
W2: IWSLT - Schedule to be fixed

### ISSUE THREAD

**Issue by marcellofederico** [acl-org/acl-2020-virtual-conference#491]
The schedule needs to be fixed as follows: 
Time (PDT) | Event | Speakers
July 9, 9:00 AM-9:15 AM | Foreword/Introduction | Marcello Federico/Alex Waibel
July 9, 9:15 AM-10:15 AM | Keynote + Q&A | Klaus Welle
July 9, 10:15 AM-11:15 AM | Findings of IWSLT 2020 +Q&A | Sebastian Stüker et al.
July 9, 11:30 PM-12:30 PM | Panel Offline Speech Translation | Marco Turchi et al.
July 9, 12:30 PM-1:30 PM | Panel Simultaneous ST | Jiatao Gu et al.
July 9, 5:00 PM- 6:00 PM | Panel Open Domain MT | Ajay Nagesh et al.
July 10, 9:00 AM-9:10 AM | Opening remarks | Marcello Federico
July 10, 9:10 AM-10:10 AM | Panel of experts | Alex Waibel

Reference: http://iwslt.org/doku.php?id=program

Thank you!
Marcello Federico

**Comment by raosudha89** [comment]
Thanks @GuyAglionby 

@marcellofederico  This has been fixed. It will be reflected after tonight's release.
