### ISSUE TITLE
Update main.415 abstract

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#492]
https://acl2020.rocket.chat/channel/presenter-helpdesk?msg=ojJGg6TF4kZB9DcDA

> Hi, same issue as Paul -- for my paper here on the virtual acl website https://virtual.acl2020.org/paper_main.415.html the abstract was updated quite a bit for camera-ready (camera-ready abstract here: https://www.aclweb.org/anthology/2020.acl-main.415/), and also now includes the link to the data and site. It would be awesome if it were possible to update. Thanks!

**Comment by anaerobeth** [comment]
@hao-fang I can do this update

**Comment by raosudha89** [comment]
Thanks @anaerobeth
