### ISSUE TITLE
[Websites] Detailed info for each social event session in the calendar

### ISSUE THREAD

**Issue by sanxing-chen** [acl-org/acl-2020-virtual-conference#493]
Currently, the calendar only shows "Birds of a feather - session n", clicking on the item brings the user to a page contains all the social events which will take more effort to find the specific session again.

@raosudha89 @dreasysnail @hao-fang @tlikhit can you please help evaluate this issue?

![image](https://user-images.githubusercontent.com/18565449/86543754-7190d600-beef-11ea-8965-9fc93d6c0fdc.png)
 
ref: https://acl2020.rocket.chat/channel/helpdesk?msg=2ynDeGYgP2WzKwds4

**Comment by hao-fang** [comment]
I think in general we need to improve the socials page / naming. But there is no consistent format / schedule for these events so it becomes a little hard to manage. So I don't have a good suggestion. I'll leave this open though.

For future conferences, we may figure out an easy/automatic way to update the calendar information with dynamically provided schedule from social event organizers.

**Comment by sanxing-chen** [comment]
The problem is that there aren't even session numbers on the social page, the users can only lookup by time.

**Comment by hao-fang** [comment]
I see. This needs to be done in two steps.

1. Someone probably needs to add the `name` field to each session based on the time
http://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/fc69deacb5cf3a02a3bcde1490433afc9c74b9ff/socials.yml#L92-L94 The name should be something live `S-Session 1`, where `S-` is a special prefix for social event sessions.

2. And then update the main repo code 
http://github.com/acl-org/acl-2020-virtual-conference/blob/40adcc248446d038b41ea112468315a6a3865ed0/miniconf/site_data.py#L38-L40 and http://github.com/acl-org/acl-2020-virtual-conference/blob/40adcc248446d038b41ea112468315a6a3865ed0/miniconf/load_site_data.py#L597-L597 which is currently hard-coded to set the session name to `S-0`.

If some volunteer can do Step 1, then it would take ~5min for me to do Step 2.
