### ISSUE TITLE
Set up Digital Ocean account

### ISSUE THREAD

**Issue by desilinguist** [acl-org/acl-2020-virtual-conference#5]
- [ ] Run the idea by Dan, Priscilla, and David to make sure they are all on board.
- [ ] If approved, create a DO account for ACL with the ACL credit card.
- [ ] Create a droplet based on the decision of #4. 
- [ ] Set up nginx and Python (and any other tooling) on the droplet

**Comment by hao-fang** [comment]
Close this for now b/c we are going to use AWS.
