### ISSUE TITLE
Embed Twitter timeline

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#50]
**Number of Volunteers**: 1

Would be nice if we can embed a Twitter timeline on our home page.
See [here](https://help.twitter.com/en/using-twitter/embed-twitter-feed) for instructions.

Should be easy but low priority.
Probably check with Publicity chairs about this.

**Comment by hao-fang** [comment]
@ppartha03 @raghavjajodia @ninell-oldenburg Can you three discuss who will work on this? I think we probably only need one person.
Also, this is pretty low priority right now so it would be nice to work on higher priority issues first.

**Comment by ninell-oldenburg** [comment]
I'll unassign myself. I started working on another issue :-)

**Comment by hao-fang** [comment]
Close this since we will have a bot in Rocket.Chat to sync tweets.
