### ISSUE TITLE
[W-4] missing Olga Kovaleva pre-recorded talk

### ISSUE THREAD

**Issue by ddemner** [acl-org/acl-2020-virtual-conference#502]
Olga Kovaleva recorded her BioNLP talk (#16 Towards Visual Dialogue for Radiology), but it is not on the workshop page.

**Comment by raosudha89** [comment]
We didn't get Olga's talk ID from slideslive. Please check tab W4 in [this spreadsheet](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=747737888)

Can you contact slideslive and ask why Olga's talk is missing from this sheet?

**Comment by raosudha89** [comment]
Note from Olga about this in relevant email thread:

Thanks for trying to look into the issue, I am not sure what exactly happened, I will just present live. 
I appreciate your time!

Closing this.
