### ISSUE TITLE
[Website] Invalid link on paper visualization page

### ISSUE THREAD

**Issue by sanxing-chen** [acl-org/acl-2020-virtual-conference#503]
Paper links on the right-hand side of the paper [visualization page](https://virtual.acl2020.org/papers_vis.html) are all invalid now. This is probably a regression.

@raosudha89 @dreasysnail @hao-fang @tlikhit can you please help evaluate this issue?

![image](https://user-images.githubusercontent.com/18565449/86554769-86379300-bf1c-11ea-8af0-34c8dafdd1bc.png)
![image](https://user-images.githubusercontent.com/18565449/86554787-8e8fce00-bf1c-11ea-8518-78015d67cce1.png)

**Comment by hao-fang** [comment]
@sanxing-chen I'm going to take a look now

**Comment by hao-fang** [comment]
Resolved with #504
