### ISSUE TITLE
[Website] Wrong timezone for ics files in Safari

### ISSUE THREAD

**Issue by EggplantElf** [acl-org/acl-2020-virtual-conference#509]
Hi, I think there might be some problem with the calendar ics file for the paper QA sessions. For example, an event is on 09:00-10:00 GMT / 11:00-12:00 CEST according to the webpage, and my time zone is CEST (2 hours ahead of GMT/UTC), the downloaded ics file has the attribute DTSTART:20200706T110000Z, with the suffix "Z" meaning the UTC time, so it ends up with 13:00-14:00 in my calendar. 

This problem only appears in Safari, using Chrome is fine.

**Comment by hao-fang** [comment]
Duplicated with #486
