### ISSUE TITLE
Another (URGENT; sorry!) update to Financial Access blog post

### ISSUE THREAD

**Issue by vinodkpg** [acl-org/acl-2020-virtual-conference#511]
Sudha, 

So sorry to do this again. We found an error in the blog post: https://acl2020.org/blog/increasing-financial-accessibility/. Since it concerns the Sponsors, we want to fix it ASAP. Could you please make the following change in the last para:

"financial subsidies to more than 80 conference participants." ---> "financial subsidies to more than 80 conference participants and writing support to over a thousand authors."

I have updated the original doc here, if you want to refer: https://docs.google.com/document/d/1uosxMoeWuHMhc8Sf5VQfQgKfHozEghyIZwbCqXCc_j0/edit?ts=5ef3b3d4#

I also noticed in the published blog post that there is a huge gap between the Figures and corresponding captions --- it is hard to tell that it is the Figure caption. Is there a way you can reduce it? Not a big deal if it is too much effort.

Vinod

**Comment by raosudha89** [comment]
@vinodkpg  I have updated the text in the blog https://acl2020.org/blog/increasing-financial-accessibility/

I can't seem to figure out how to reduce the gap. But hopefully the 'Figure 1' and "Figure 2" in the beginning of the caption will help people know which caption is for which image. Sorry about this. Only if I had more time.. :)

**Comment by vinodkpg** [comment]
Thanks a million, Sudha!!! Don't worry about the Figure captions :)
