### ISSUE TITLE
Fix title of PCC presentation in business meeting

### ISSUE THREAD

**Issue by emilymbender** [acl-org/acl-2020-virtual-conference#515]
Hi!

On https://virtual.acl2020.org/plenary_session_business_meeting.html the title of the PCC presentation should be "Report of the Professional Conduct Committee" (not what's currently there "Report of Professional Code of Conduct").  Thanks!

Emily

**Comment by emilymbender** [comment]
I see that this slideslive page has the same problem https://slideslive.com/38929526/professional-conduct-committee-cochairs-report-to-acl-2020-business-meeting

**Comment by hao-fang** [comment]
Resolved by #212. Will release by tonight.
