### ISSUE TITLE
Issue with Demo Paper 69 link

### ISSUE THREAD

**Issue by karakiz** [acl-org/acl-2020-virtual-conference#521]
The authors of the  demo paper 69: 
https://virtual.acl2020.org/paper_demo.69.html
Says that the link to their demo is wrong. 
The issue is the HTTPS header actually, they need to change it from HTTPS:// to HTTP://.

The correct link to their demo is: http://syntagnet.org/
Can you change it?

**Comment by hao-fang** [comment]
Resolved with  acl-org/acl-2020-virtual-conference-sitedata#215. Will be released by tonight.
