### ISSUE TITLE
Paper 211 has wrong category

### ISSUE THREAD

**Issue by tlikhit** [acl-org/acl-2020-virtual-conference#523]
>An author reported that his paper (main conference #211) should be under the theme category, but it shows "Semantics: Textual Inference and Other Areas of Semantics" here https://virtual.acl2020.org/paper_main.211.html .

**Comment by hao-fang** [comment]
I replied https://acl2020.rocket.chat/channel/helpdesk?msg=WCJrZ2jzjwwojdEWu

We can re-open after the authors have confirmed with PCs.
