### ISSUE TITLE
Document Login Auth

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#53]
## AWS Preparation
1. Grant necessary permissions to the AWS user. (TODO: check with Nitin)
![image](https://user-images.githubusercontent.com/9957482/84460767-9dd27300-ac1f-11ea-9d0a-792c130be49f.png)
1. Click [this link](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge) to create all necessary resources. This solution comes from this [blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/authorizationedge-using-cookies-protect-your-amazon-cloudfront-content-from-being-downloaded-by-unauthenticated-users/).
    * Application name: `acl2020-virtual-conference-website`
    * EnableSPAMode: `false`
    * HttpHeaders: Remove `"Content-Security-Policy":"..."` from the default value
    * LogLevel: `info`
    * Version (optional): `1.0`
    * AlternateDomainNames (optional): `virtual.acl2020.org`

2. Go to "Service" -> "CloudFormation", it should show the created stack `serverlessrepo-acl2020-virtual-conference-website`. After the creation completes, all created resources are available under the "Outputs" tab.
    * Find the "WebsiteUrl" in the "Outputs" tab. Click it will redirect you to the login page. 
![image](https://user-images.githubusercontent.com/9957482/84460957-251fe680-ac20-11ea-8640-cbfea4d3d2bb.png)

## AWS Cognito Setup
1. To customize sign-in UI, go to "App integration" -> "UI customization". Choose the "App client to customize".
    * Upload the `acl-logo.png` and click "Save Changes". This will make the login page looks like below.
![image](https://user-images.githubusercontent.com/9957482/84461004-3c5ed400-ac20-11ea-89be-f9347c66970d.png)

## RocketChat OAuth Setup
1. Create a new OAuth: Administration -> OAuth -> Add custom oauth
```
Token Path: /oauth2/token
Token Sent Via: Header
ID Token Sent Via: Header
Identity Path: /oauth2/userInfo
Authorize Path: /login
Scope: openid
Param Name for AT: access_token
id: <App client id from Cognito App Clients tab>
Secrete: <App client secrete from Cognito App Clients tab>
```

2. Configure AWS Cognito. Add the Callback URL `https://<workspace>.rocket.chat/_oauth/<name>` (shown in the RocketChat OAuth page) to the AWS Cogito user pool -> App client settings -> Callback URL(s). 

3. Disable the login form: Administration -> Accounts -> Show Default Login Form
![image](https://user-images.githubusercontent.com/9957482/84357872-2cd97f80-ab7b-11ea-8a4c-82e220607902.png)
It will make the login interface looks like below,
![image](https://user-images.githubusercontent.com/9957482/84358819-8d1cf100-ab7c-11ea-8c03-e916c258e45a.png)
When click the button, it will redirect to the login page.
![image](https://user-images.githubusercontent.com/9957482/84358891-acb41980-ab7c-11ea-8a84-b0e182b6eadc.png)

## Links
* [Original Issue](https://github.com/acl-org/acl-2020-virtual-conference/issues/13).

**Comment by hao-fang** [comment]
close this for now. we can re-open after the conference

**Comment by hao-fang** [comment]
AWS Lambda set up for `signin.acl2020.org`.


### serverlessrepo-acl2020-virtual-co-CheckAuthHandler-xxxxx
![image](https://user-images.githubusercontent.com/9957482/85105339-34260c00-b1bf-11ea-9292-89cf664eefa5.png)

* Save
* Action ->Publish New Version
* Action -> Deploy to Lambda@Edge

### serverlessrepo-acl2020-virtual-co-ParseAuthHandler-xxxxx
![image](https://user-images.githubusercontent.com/9957482/85105469-69caf500-b1bf-11ea-80d3-ba2d0fba10fd.png)

* Save
* Action -> Publish New Version

### serverlessrepo-acl2020-virtual-conf-SignOutHandler-xxxxx
![image](https://user-images.githubusercontent.com/9957482/85105522-7a7b6b00-b1bf-11ea-9dcd-28905c11fd53.png)

* Save
* Action -> Publish New Version

**Comment by hao-fang** [comment]
Remember to bump the quota for sending welcome emails. Otherwise, it can only send 50 emails per day.
* https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html

**Comment by cyriltw** [comment]
Something to add on the Rocket.Chat side of setting up Custom OAuth, it will ask for a URL. This should be URL on AWS Cognito, should look something like `https://<app_name>.auth.us-east-1.amazoncognito.com`
