### ISSUE TITLE
Update and Add NLPMC schedule

### ISSUE THREAD

**Issue by parry2403** [acl-org/acl-2020-virtual-conference#536]
We have updated the spreadsheet but it has not been updated on the website.

https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=646602401

https://virtual.acl2020.org/workshop_W15.html

**Comment by raosudha89** [comment]
@tlikhit  Can you update the W15 schedule? Thanks

**Comment by tlikhit** [comment]
Closing with https://github.com/acl-org/acl-2020-virtual-conference-sitedata/commit/924d6ec6e9c0c94ec9c4cba460659622650ab76e

**Comment by parry2403** [comment]
@tlikhit @raosudha89  Detailed schedule is not visible again for W15.

**Comment by tlikhit** [comment]
Yes, it appears that a later commit reverted some changes. Sorry for the trouble, I will look into this.

**Comment by tlikhit** [comment]
@raosudha89 It appears that https://github.com/acl-org/acl-2020-virtual-conference-sitedata/commit/afe554d049bf83d9a50ea4d1cdb74598371c9ef8 reverted some changes, including removing W15 data. I will add in W15 data for now and will look through the diff for any other changes.

**Comment by raosudha89** [comment]
@tlikhit  Oh I am sorry, I don't know how that happened. Thanks for adding it again. Let me know when you do that. I will merge it for tonight's release (scheduled for 11pm PST).

**Comment by tlikhit** [comment]
@raosudha89 I've sent in PRs to update sitedata and bump it
