### ISSUE TITLE
Add Demo link for Demo Paper 58

### ISSUE THREAD

**Issue by chokkyvista** [acl-org/acl-2020-virtual-conference#538]
Hi, one of the authors here.
Can we add a "Demo" link to our system-demo paper (https://virtual.acl2020.org/paper_demo.58.html) please?
We've just released a demo video for it at https://youtu.be/2he8Jgmjo9M.
Many thanks!

**Comment by sanxing-chen** [comment]
@raosudha89 Can you please take a look at this, I'm happy to help with PR if you can give me access to the repo. Thanks! (I'm one of the volunteers btw)

**Comment by hao-fang** [comment]
@sanxing-chen I gave you the access. Please follow instructions here to make your PRs

https://github.com/acl-org/acl-2020-virtual-conference/blob/master/CONTRIBUTING-ACL2020.md#how-to-create-a-pull-request-for-the-website-acl-2020-virtual-conference-and-the-data-sitedata_acl2020
