### ISSUE TITLE
Basic "Similar Papers" function

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#54]
**Number of Volunteers**: 1

This is available in ICLR2020, but we will need to re-run the model.

- [ ] Get the paper with abstract by merging these two files
    * [accepted papers](https://docs.google.com/spreadsheets/d/15WSbGv1BZQcZWMrVQK7YlbSpYAPgFK0h/edit#gid=1292329301) 
    * [abstracts](https://docs.google.com/spreadsheets/d/1_pIMrRR9luRNbRBwJRNGpYzMz3WdXidRTOAx2F-fOQE/edit#gid=0)
- [ ] Follow the instruction [here](https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/README.md) to create embeddings
- [ ] See this issue https://github.com/Mini-Conf/Mini-Conf/issues/21 and follow up there to request more information.

**Comment by Chandrahasd** [comment]
Is there any resource where we can get more details about the model?

**Comment by hao-fang** [comment]
> Is there any resource where we can get more details about the model?
> I could find a method to convert abstracts to embeddings at https://github.com/Mini-Conf/Mini-Conf/tree/master/scripts. Do we plan to use the same?

@Chandrahasd Let's start with the same method. I updated the description with some actionable items. Please let me know if you have more questions.

**Comment by georgepar** [comment]
Hi all,

I extracted the embeddings and saved them to this drive link, if anybody needs them:

https://drive.google.com/file/d/1BM-HtX5dOpiO3M_yDf-shVY-KMH72wwt/view?usp=sharing

**Comment by hao-fang** [comment]
> I used the pretrained model from iclr.github.io and produced some paper recommendations.

@georgepar This is great! We probably will have a pretrained model on ACL2020 papers which may work better. I'll keep you posted about this.

**Comment by hao-fang** [comment]
@vladdy @Chandrahasd @kaushal0494 @dpappas @ninell-oldenburg I un-assigned you from this issue because @georgepar has started working on it.
I now added a "**Number of Volunteers**" section at the beginning for each issue. Sorry for the confusion. I'll also send a clarification email to our mailing list soon.

But if you have already started working on this and get some update, please post here and we can see if we can merge a version soon. Thanks!
