### ISSUE TITLE
[Website] Title of "Context-Driven Satirical Headline Generation" is not updated in the anthology

### ISSUE THREAD

**Issue by abdullah-alnahas** [acl-org/acl-2020-virtual-conference#548]
This paper's title (@ https://www.aclweb.org/anthology/2020.figlang-1.5/) is not updated according to the camera-ready submission.
The updated title is: "Context-Driven Satirical Headline Generation", however, in the anthology and the ACL program an older version of the title is presented, which is "Context-Driven Satirical News Generation".

How to proceed with this?

**Comment by hao-fang** [comment]
@abdullah-alnahas They need to reach out to acl2020programchairs@gmail.com for such requests. 
Our website will be based on the proceedings / Anthology.
