### ISSUE TITLE
[Website] Video not available for paper_main.45

### ISSUE THREAD

**Issue by duynht** [acl-org/acl-2020-virtual-conference#551]
The pre-recorded video is not available on both [the virtual conference](https://virtual.acl2020.org/paper_main.45.html) and [SlidesLive](https://slideslive.com/38928694).

@raosudha89 @dreasysnail @hao-fang @tlikhit

**Comment by hao-fang** [comment]
> The video for this paper is not available and is still under processing by SlidesLive

![image](https://user-images.githubusercontent.com/9957482/86795323-4b1f8780-c022-11ea-9604-b97239ae9c56.png)

**Comment by hao-fang** [comment]
![image](https://user-images.githubusercontent.com/9957482/86870051-8b1b5480-c08c-11ea-8937-60a3bf8d9ddd.png)
