### ISSUE TITLE
[W10] missing papers and keynote for REPL4NLP 

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#559]
Dear Hao and Sudha,

Can you help us out here? I appreciate you must be really busy but there isn’t long until the workshop and a number of the papers (extended abstracts) are missing from the REPL4NLP website, and the authors are getting understandably upset.

Alex from slideslive confirmed these papers have been edited and are ready on their end, how can we get them on the website

These are the missing papers:

- On the Ability of Self-Attention Networks to Recognize Counter Languages, Satwik Bhattamishra, Kabir Ahuja and Navin Goyal, t-satbh@microsoft.com
- Variational Inference for Learning Representations of Natural Language Edits, Edison Marrese-Taylor, Machel Reid and Yutaka Matsuo, emarrese@weblab.t.u-tokyo.ac.jp
- Predicting Sexual and Reproductive Health of Migrants using Data Science, Amber Nigam, Pragati Jaiswal, Teertha Arora, Uma Girkar and Leo Anthony Celi, anigam9@gatech.edu
- Job Recommendation through Progression of Job Selection, Amber Nigam, Aakash Roy, Hartaran Singh and Arpan Saxena, anigam9@gatech.edu
- A Simple Approach to Learning Unsupervised Multilingual Embeddings, Pratik Jawanpuria, Mayank Meghwanshi and Bamdev Mishra, pratik.iitb@gmail.com
- AI4Bharat-IndicNLP Dataset: Monolingual Corpora and Word Embeddings for Indic Languages: Monolingual Corpora and Word Embeddings for Indic Languages, Anoop Kunchukuttan, Divyanshu Kakwani, Satish Golla, Gokul N.C., Avik Bhattacharyya, Mitesh M. Khapra and Pratyush Kumar, ankunchu@microsoft.com

Patrick

We are also still missing video for Invited Talk 4 (Evelina Fedorenko) that was uploaded earlier today, with id: 20200707T155721Z__ACL__w10__W1004__invited-talk.

**Comment by ariepratama** [comment]
hello @raosudha89 where can I found the presentation id for these papers? or do I need to contact slideslive?

**Comment by raosudha89** [comment]
@ariepratama  You can find them here: https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=2130696280

Will be working on this in the next hour? If yes, please let me know. 

We need to add this information in tonight's release. So if you are unavailable to work on this, then I can work on it.

**Comment by raosudha89** [comment]
Note: Keynote 4 is not missing: https://virtual.acl2020.org/workshop_W10.html

**Comment by raosudha89** [comment]
The missing papers are missing from the [spreadsheet ](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=2130696280) as well.  I have emailed SlidesLive about this. We can add them only once the IDs have been added to the spreadsheet.

**Comment by ariepratama** [comment]
@raosudha89 ok will be working in this in a few minutes

**Comment by raosudha89** [comment]
@ariepratama  The IDs have been updated in the [spreadsheet ](https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=2130696280) now. Please use these IDs to update your PR. Thanks.

**Comment by ariepratama** [comment]
okay!

**Comment by ariepratama** [comment]
@raosudha89 updated and tested on my local

**Comment by strubell** [comment]
can we please merge these changes asap
