### ISSUE TITLE
Add tile in Socials page for Black in AI Social

### ISSUE THREAD

**Issue by vinodkpg** [acl-org/acl-2020-virtual-conference#560]
Hi Sudha/Yizhe/Hao (or anyone else in the virtual infra committee)

Could you please add a new "tile" to the virtual site's Socials page? Black in AI has expressed interest to host a Social at ACL!
It is the first time for ACL and I am excited. Sorry for the short notice, but we would love to have this up on the Socials page asap. 

**Title**: Black in AI Social
**Logo**: https://drive.google.com/file/d/1oXHa5Fu8Y82EMCdPwmuPa2_uXGWjx-Pn/view?usp=sharing
**Organizers**: AnnMargaret Tutu and Krystal Maughan
**RocketChat channel**: #black-in-ai
**Website**: https://blackinai.github.io/
**Description**: The ACL BlackInAI social is an event for those who self-identify as Black and are looking for a space to socialize, share ideas and to discuss research on NLP or AI. This social will involve an ice breaker and introductions, small presentations and details about the group Black in AI.
**Event times**: Friday, July 10th, 2020, 7am PDT/10am EST/2pm UTC

NOTE 1: Like Queer in AI, they would like for this to be a "closed" groups where they will share the Zoom link in the Rocket Chat channel. So no need to add the Zoom link in the tile. 

NOTE 2:I am planning to re-use one of the Academic Inclusion Zoom links for this purpose. Hope thats ok. 

Vinod

**Comment by hao-fang** [comment]
@vinodkpg How long the session should be?

**Comment by vinodkpg** [comment]
Thanks Hao. I dont see it listed online still --- would it take a while to show?

**Comment by hao-fang** [comment]
@vinodkpg I just pushed the new release. It should be updated now.
During the conference time, our website is not updated in real-time because we need to exercise extra carefulness to check all changes does not break any existing pages. Therefore, we only schedule the update every night PST.

**Comment by vinodkpg** [comment]
Oh great, makes sense! Thanks a ton!

Vinodkumar Prabhakaran
Research Scientist
Google, San Francisco.
https://www.cs.stanford.edu/~vinod/

**Comment by hao-fang** [comment]
@vinodkpg Happy to help :)
