### ISSUE TITLE
[W20]

### ISSUE THREAD

**Issue by kverspoor** [acl-org/acl-2020-virtual-conference#569]
Late update of the schedule. So so sorry it is so late but we just made our final decisions ~24 hours ago!

I have added in the schedule to the "ACL 2020 Workshop Information" sheet under W20 tab. Should we update it on the workshop page or how do you want to handle it at this stage?

**Comment by tlikhit** [comment]
@kverspoor  I will add this onto the workshop page. I see that there are quite a few unlabeled events. Is there any reason you've added only certain events? If not, is it okay if I put in all events mentioned in the detailed spreadsheet? (https://docs.google.com/spreadsheets/d/1eem24ssMD1wzWWBqSrlmqdIoM_0NkeM8UjOKKyu0B2M/edit#gid=0)

**Comment by tlikhit** [comment]
@kverspoor Okay, I noticed your comment below the doc link and copied everything over. Is it possible to get a timeline for  the closing end time?

**Comment by kverspoor** [comment]
We will end after the final Q&A, so 21:30

**Comment by kverspoor** [comment]
Sorry I think I must have two "ACL 2020 Workshop Information" spreadsheets because I put the complete details in a different one. Anyway since you found the source that is fine :)

**Comment by tlikhit** [comment]
> We will end after the final Q&A, so 21:30

Sorry for being ambiguous. Our default schedule format includes both start and end times for each event. I understand that the spreadsheet only lists the start times for events. I meant to ask about the time the closing concludes (21:30-XX:XX)
<img width="1045" alt="Screen Shot 2020-07-08 at 4 24 32 AM" src="https://user-images.githubusercontent.com/58948612/86895927-30591b80-c0d3-11ea-9bf8-157e93fd65c6.png">




> Sorry I think I must have two "ACL 2020 Workshop Information" spreadsheets because I put the complete details in a different one. Anyway since you found the source that is fine :)

Yeah, it's all good :)

**Comment by kverspoor** [comment]
I really meant that we are ending at 21:30. There is no "closing session". So just 21:30-21:30!

Best regards,
Karin

sent from a device that encourages brevity and typos

________________________________

**Comment by tlikhit** [comment]
Ah, that makes sense. Thanks!
> sent from a device that encourages brevity and typos

 😂
