### ISSUE TITLE
[Website] Paper with question marks on references

### ISSUE THREAD

**Issue by paulomann** [acl-org/acl-2020-virtual-conference#572]
Hi,

This paper (https://www.aclweb.org/anthology/2020.acl-main.769.pdf) has question marks on references. The author Rabeeh Karimi Mahabadi (@rkarimi) is certain that uploaded the correct version.

Can anyone check on this? Thanks.

@dreasysnail @raosudha89 @hao-fang @tlikhit

**Comment by hao-fang** [comment]
The authors have reached out to program chairs to correct the Anthology PDF.
