### ISSUE TITLE
[FAQ] RocketChat and website availability after conference

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#579]
From Dan,

I think we should announce about the rocketchat and also make and announce a decision about the rest of the website. (i.e. something like "The ACL2020 website will remain up for ACL attendees to rewatch any of the conference videos, although the RocketChat and zoom links will be removed  [?on DATE? Friday? Monday?].  The videos will also be uploaded to the ACL Anthology over the next few months"

**Comment by raosudha89** [comment]
@hao-fang  Do you know the exact details of when will do we plan to remove the links? I can then add the FAQ accordingly.

**Comment by hao-fang** [comment]
@raosudha89 not yet ... it will take some time to remove these links. maybe we say `by July 25` because our contract with RocketChat ends on that date.

**Comment by raosudha89** [comment]
@hao-fang  Do you think we should add some version of this FAQ in our tonight's release? I know that Joel said they don't have a definite answer as yet. But if you think many people are asking this question, then we can say something without specifying exact dates.

**Comment by hao-fang** [comment]
@raosudha89 Let's wait for tomorrow probably, just to make sure we do not communicate the wrong information to people.
If they ask, our volunteers will be able to give some answers.
And we can update the FAQ tomorrow around noon once PCs have made an official decision, and we can then update the FAQ & make an announcement.

**Comment by raosudha89** [comment]
Sounds good. Thanks.

**Comment by hao-fang** [comment]
Close this as we already make the announcement and the conference is almost over.
