### ISSUE TITLE
[Workshops] Verify pre-recorded talks for July 10

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#586]
Similar to the one for July 9 https://github.com/acl-org/acl-2020-virtual-conference/issues/576

**Comment by raosudha89** [comment]
@tlikhit  Will you be able to work on this sometime early tomorrow? Thanks.

**Comment by tlikhit** [comment]
@raosudha89 Okay, will do this after re-adding W15 data

**Comment by raosudha89** [comment]
@tlikhit  Any updates on this? If we need to do any updates to the website, please let me know.

**Comment by tlikhit** [comment]
I'll list issues one by one below:
W11: Invited Talks [3](https://slideslive.com/38929804/invited-talk-3),[4](https://slideslive.com/38929805/invited-talk-4),[5](https://slideslive.com/38929805/invited-talk-5),[6](https://slideslive.com/38929805/invited-talk-6) not recorded

**Comment by tlikhit** [comment]
W12 - Not Recorded:
- A Question Type Driven and Copy Loss Enhanced Framework for Answer-Agnostic Neural Question Generation, Xiuyu Wu
- The NiuTrans System for WNGT 2020 Efficiency Task, Chi Hu
- Increasing Lexical Diversity in Plug and Play Language Models, Soham Parikh

**Comment by tlikhit** [comment]
W14- Not Recorded:
- On Understanding Character-level Models for Representing Morphology, Clara Vania
- Inflectional data science and human/computer-aided linguistic analysis, Robert Malouf
- In search of isoglosses: continuous and discrete language embeddings in Slavic historical phonology, Chundra Cathcart

**Comment by tlikhit** [comment]
W15- Not Recorded:
- Medical Conversations: Challenges and Future, Kass-hout Taha

**Comment by tlikhit** [comment]
W16- Not Recorded
- How to Grow a (Product) Tree: Personalized Category Suggestions for eCommerce Type-Ahead - Jacopo Tagliabue, Bingqing Yu and Marie Beaulieu
- On Application of Bayesian Parametric and Non-parametric Methods for User Cohorting in Product Search, Shashank Gupta
-

**Comment by tlikhit** [comment]
W17 - Not Recorded
- Opening, Lun-Wei Ku
- Closing, Lun-Wei Ku

**Comment by tlikhit** [comment]
W19 - Not Recorded
- Opening Remarks, Amir Zadeh
- Keynote, Rada Mihalcea
- Keynote, Ruslan Salakhutdinov
- Closing Remarks, Amir Zadeh

**Comment by raosudha89** [comment]
@tlikhit  Thank you so much for the detailed list. This is very useful. I will go ahead and update the websites accordingly. Thanks.

**Comment by tlikhit** [comment]
@raosudha89 No problem! Please do let me know if I can help in updating the websites. I thought it'd be best to edit after getting clarification :)

**Comment by hao-fang** [comment]
Close this as the workshops are over.
