### ISSUE TITLE
Set up a GitHub action to deploy website to AWS

### ISSUE THREAD

**Issue by desilinguist** [acl-org/acl-2020-virtual-conference#6]
Create a GitHub action that will automatically update the static website on the DO droplet whenever any changes to the master branch are pushed. 

We can adapt the [publish workflow](https://github.com/acl-org/acl-anthology/blob/master/.github/workflows/publish.yml) used by the ACL Anthology.

**Comment by hao-fang** [comment]
This is partially done in https://github.com/Mini-Conf/Mini-Conf/issues/31.
But there are some remaining work.
- [ ] `make deploy` only deploy to Github gh-page. We need to deploy to AWS S3.
- [ ] We need to add a GitHub action. See [here](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions) for some additional instructions to set the AWS credentials.
