### ISSUE TITLE
[FEATURE] RocketChat username 

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#60]
Currently, when log into RocketChat with ACL2020 account (via AWS Cognito), it will ask the user to create a userame, but it does not ask for the "Name" field, so it will create a random string.
Unfortunately, the AWS Cognito doesn't store the First/Last name information.
Should figure out a way to show proper username in RocketChat.

**Comment by stupid-2020** [comment]
Haven't take a look yet.  But wonder if the "user-attributes" (via AWS Cognito) could help.

**Comment by hao-fang** [comment]
> Haven't taken a look yet. But wonder if the "user-attributes" (via AWS Cognito) could help.

@stupid-2020 I haven't tested it. So I created a CloudFormation stack using [this link](https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:520945424137:applications/cloudfront-authorization-at-edge) following the tutorial [here](https://aws.amazon.com/blogs/networking-and-content-delivery/authorizationedge-using-cookies-protect-your-amazon-cloudfront-content-from-being-downloaded-by-unauthenticated-users/).
But it seems the user pool created by the Cognito only allows username==email. So I don't have other "username" field.

It seems that after the user pool is created, I can add custom fields (e.g., username, name). But I don't know how to create a user with these fields. The console interface doesn't allow me to do that. May need to check the AWS CLI usage. If you can help dig out some information, that would be helpful. (I'll also try something when I have time.)

**Comment by hao-fang** [comment]
Ah, I added a `custom:name` field in the AWS Cognito and set the "Name" field in RocketChat OAuth to "custom:name`. Now it works well. I just need to set the `custom:name` field when creating the user (or update the attributes with [this command](https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/admin-update-user-attributes.html).

![image](https://user-images.githubusercontent.com/9957482/84536877-95238080-aca3-11ea-9487-067787646843.png)


![image](https://user-images.githubusercontent.com/9957482/84536857-8b018200-aca3-11ea-8d53-7a1d05a6ab69.png)
