### ISSUE TITLE
RocketChat Admin

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#62]
**Number of Volunteers**: 2

We will need two volunteers (ideally cover different time zones) to be the RocketChat admin.

Duties:
- [x] configure RocketChat settings
  - [x] Figure out the right permissions for different roles (e.g., `volunteers`, `sponsors`, `organizers`, etc.)
  - [x] Make the color scheme more close to ACL style (maybe red & white?)
  - [ ] Document all configurations (see #56 )
- [x] directly submit tickets (on website or via email) to get tech support from RocketChat
   * For this one, we may create a shared account to submit the ticket (b/c RocketChat only allows 3 such accounts), and all RocketChat volunteers can use this account.
- [x] answer RocketChat related questions from attendees, authors, sponsors, etc.
- [x] help RocketChat integration with the website (need additional volunteers to write the code if needed)

**Comment by stupid-2020** [comment]
Hi hao-fang

I would like to ask for the details if I am possible to help on this issue.

1. Configuration of RocketChat should be done before 01-JUL, right?
2. Support during the whole conference (from 06-JUL to 10-JUL)?
3. What is the "support level"?  Response in minutes or hour?

My available hours should be:
  09:00 - 18:00 HKT   = (01:00 - 10:00 UTC) = (18:00 - 03:00 PDT)

**Comment by hao-fang** [comment]
@stupid-2020 Thanks! Please see my answers inline.

> 1. Configuration of RocketChat should be done before 01-JUL, right?

Ideally this should be done as soon as possible. But we have a chance to fine-tune it before 01-JUL.

> 2. Support during the whole conference (from 06-JUL to 10-JUL)?

It should be 05-JUL to 10-JUL. 

> 3. What is the "support level"?  Response in minutes or hour?

We will probably get more volunteers for this. But for now we need to have 2 more "tech lead" for RocketChat. We haven't decided response turn-around time. 

> My available hours should be:
> 09:00 - 18:00 HKT = (01:00 - 10:00 UTC) = (18:00 - 03:00 PDT)
This is great to know!

Let me know if you need more details :)
If you are willing to take this role, I'll grant necessary permissions to your RocketChat account.

**Comment by vladdy** [comment]
I'd like to help with this as well. I'm in EDT timezone.

**Comment by hao-fang** [comment]
@vladdy Great! I'll schedule a meeting once we decide who will be the other RocketChat admin.

**Comment by stupid-2020** [comment]
@hao-fang I would like to help but I could only commit to support from 07-JUL to 10-JUL.  Is that ok?

**Comment by hao-fang** [comment]
> @hao-fang I would like to help but I could only commit to support from 07-JUL to 10-JUL. Is that ok?

@stupid-2020 That might not work because we need three admin to cover different timezones for the whole conference. 

One option is to create a shared email account which can directly get tech support from RocketChat. Multiple volunteers can use this account to ask questions.
(RocketChat's support plan only allows 3 accounts to directly contact them, including my own account.)

Let's see if there is any other volunteer can help this.

**Comment by stupid-2020** [comment]
@hao-fang I could setup an email account for forward emails if necessary.   Anyway, let's see if any other volunteer first.  Thanks and sorry for cause any inconvenience.

**Comment by tlikhit** [comment]
@hao-fang I could help as well. I'm in EDT, but I'll be on break during that week so I should be able to cover another timezone.

**Comment by hao-fang** [comment]
@vladdy I'll close this one for now since the descriptions are outdated.
I'm trying to clean up the issues so we get a v1.0 version ready.

I'll create another main issue of RocketChat related tasks to be tracked on and assign you on this.


@tlikhit -- I'm making a plan for on-call volunteers support and I may ask you about it. For now, let's focus on finishing the website issues.
