### ISSUE TITLE
Student Research Workshop page

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#64]
**Number of Volunteers**: 1

Student research workshop papers will be treated the same as main conference papers.
However, we will need to make a single SRW page to include the following:
- [ ] Overall schedule of the workshop which can be found in the SRW tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1sTRj-skkp7qYz1zwqvmPuXRay6HIHEOS7NOuUMsW8oE/edit#gid=198768287)
- [ ] Name of the organizers of SRW

The volunteer need to design the layout. May re-use the same layout as the regular workshop page #21.
The individual page will use the same layout as regular paper in #16. But it would be useful to double check the outcome.

**Comment by hao-fang** [comment]
We will also need to add the papers to `papers.csv`. See #74.

**Comment by raosudha89** [comment]
@hao-fang  and I decided that it would not make sense to have a separate page for SRW. We can just consider this as another track (under different tracks of papers). So closing this issue.
