### ISSUE TITLE
Convert accepted papers to a csv file

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#8]
Merge the following files to a csv file that can be loaded by Mini-Conf.
 
### Main Conference
* [Accepted Papers](https://docs.google.com/spreadsheets/d/15WSbGv1BZQcZWMrVQK7YlbSpYAPgFK0h/edit#gid=1292329301) 
* [Abstract & Author List](https://docs.google.com/spreadsheets/d/1_pIMrRR9luRNbRBwJRNGpYzMz3WdXidRTOAx2F-fOQE/edit#gid=0)
* [Track.xlsx](https://github.com/acl-org/acl-2020-virtual-conference/files/4769133/paper_tracks.xlsx)

### Demo Papers
TODO

### SRW Papers
TODO

**Comment by GuyAglionby** [comment]
Made [this csv](https://gist.github.com/GuyAglionby/cdfda342e978033c72bd04e895044182) using [this script](https://gist.github.com/GuyAglionby/8da5bf4852833c3d87516b1265282bda). 

Couple caveats:

- (Most key) I've assumed that the order of papers in your xls file corresponds to the IDs that they will be given in the anthology (first paper ID 1, second 2, etc). If this isn't correct then the IDs should be changed. Generally, it would be nice to use the same ID format for both the Anthology and here I think.
- No keywords yet (cf https://github.com/Mini-Conf/Mini-Conf/issues/34)
- No abstracts available 
- No sessions available. For ICLR this looks like it was only used for speakers? Maybe this could be used for the paper's track here

The missing elements should be able to be easily plugged in using the appropriate methods in the code.

**Comment by hao-fang** [comment]
@GuyAglionby I've updated the instruction. I think you have to modify your script to consume these three files.
* The paper ID is not the line number -- you need to find them in the "Abstract & Author List" spreadsheet or the "Track.xlsx" file.
* Sessions are now available.
* Abstracts are now available.
* We do not have keywords yet.

**Comment by georgepar** [comment]
created the [papers.csv](https://gist.github.com/georgepar/3d5cda48c50c6ee57f56aaea9b99603d#file-papers-csv) using [this file](https://docs.google.com/spreadsheets/d/1_pIMrRR9luRNbRBwJRNGpYzMz3WdXidRTOAx2F-fOQE/edit#gid=0) and [this script](https://gist.github.com/georgepar/3d5cda48c50c6ee57f56aaea9b99603d#file-create_papers_csv-py)

I haven't added session info yet and found keywords using TF-IDF

**Comment by GuyAglionby** [comment]
Snap @georgepar , also just updated my script :)

@hao-fang - thanks for the new files. It doesn't look like there's a distinction between long and short papers in track.xlsx - we need this if we want to use the Anthology format (`2020.acl-{volume}.{paper-id}`) as they live in different volumes and so have different paper id spaces. Do you have easy access to this? I can get in touch with the Anthology people if that would be easier.

**Comment by georgepar** [comment]
Sorry for that, I needed the csv file for #54

**Comment by GuyAglionby** [comment]
Gotcha! The projection looks cool. Happy to put the finishing touches on this

**Comment by georgepar** [comment]
Sounds good @GuyAglionby thanks :)

**Comment by hao-fang** [comment]
> Snap @georgepar , also just updated my script :)
> 
> @hao-fang - thanks for the new files. It doesn't look like there's a distinction between long and short papers in track.xlsx - we need this if we want to use the Anthology format (`2020.acl-{volume}.{paper-id}`) as they live in different volumes and so have different paper id spaces. Do you have easy access to this? I can get in touch with the Anthology people if that would be easier.

@GuyAglionby The submission type info is in the [Abstract & Author List](https://docs.google.com/spreadsheets/d/1_pIMrRR9luRNbRBwJRNGpYzMz3WdXidRTOAx2F-fOQE/edit?usp=sharing). Can you use that?

**Comment by GuyAglionby** [comment]
@hao-fang I can import that information, but from that I see that long and short papers are mixed together in track.xlsx. Because it's mixed I can't be confident in extracting separate paper IDs for each volume from that ordering, unless I e.g. take the first long paper as `2020.acl-1.1` and the first short as `2020.acl-2.1` and maintain separate counts going through. That would make sense but isn't guaranteed to be right.

**Comment by hao-fang** [comment]
@GuyAglionby I quickly checked the submission IDs and they seem to be unique. Do you have examples with duplicated IDs (in case I missed anything)?

**Comment by GuyAglionby** [comment]
@hao-fang sorry, I don't think I'm explaining this well! I realised I've assumed that short papers and long papers are split into separate volumes - they weren't in 2019 but were in the years before.

If they are in the same volume, there's no issue. If they're in a different volume, then we will need to end up with IDs `2020.acl-1.{1-571}` for the long papers and `2020.acl-2.{1-208}` for the short (format described [here](https://www.aclweb.org/anthology/faq/)), and I'm not clear how to map from tables.xlsx to these.

This is all assuming we'd like the website ID format to match the Anthology. I think it'd be nice, but am happy to go with the IDs as found in tables if this is all getting too complicated.

**Comment by hao-fang** [comment]
@GuyAglionby I see. Let's first assume they are in the same volume so we can get a basic website version ready. I'll reach out to our organizing committee and cc you to see what we are going to do with the Anthology.

**Comment by hao-fang** [comment]
@GuyAglionby I've merged https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/4.
Can you make a PR in this repo to update the `sitedata_acl2020`?
```bash
cd sitedate_acl2020
git pull
cd ..
git commit -am "update sitedate_acl2020"
```

We will need to add demo papers & SRW papers later. Do you think it can be in the same `papers.csv` file?
I'll get necessary files to you.

**Comment by GuyAglionby** [comment]
Yep should be no problem to use the same file

**Comment by hao-fang** [comment]
Close this one and make #72 for the SRW & demo papers.
