### ISSUE TITLE
Add Plenary Sessions to Schedule

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#84]
**Number of Volunteers**: 1

We will need to add plenary sessions to the Schedule page, e.g., opening/closing remarks, etc.

**Comment by sgdgp** [comment]
@hao-fang Will this be incorporated under #23 (as I find mention of making keynotes as plenary sessions and adding them) ?

**Comment by hao-fang** [comment]
@sgdgp Oh yes, you are right. I'll close this one. Thanks for catching this.
