### ISSUE TITLE
Fix missing photos for committee members

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#86]
**Number of Volunteers: 1**

There are a few missing photos.
- [x] Collect the list of committee members without a photo
- [x] Reach out to @raosudha89 @dreasysnail @hao-fang to get their emails
- [x] Get their photos or use a generic one

**Comment by stupid-2020** [comment]
List of committee members without a photo:

1. Priscilla Rasmussen
2. Milica Gašić
3. Dilek Hakkani-Tur
4. Lianhui Qin (invalid link)

**Comment by stupid-2020** [comment]
Once I get the photo URLs, I have to update [committee.yml](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/committee.yml), right?

**Comment by hao-fang** [comment]
@stupid-2020 Can you follow up with me next week if we didn't get back to you with these email addresses?
Feel free to replace the `http` with `https` first.

**Comment by stupid-2020** [comment]
> @stupid-2020 Can you follow up with me next week if we didn't get back to you with these email addresses?
ok.
> Feel free to replace the `http` with `https` first.
Will update soon.

**Comment by hao-fang** [comment]
@stupid-2020 FYI -- @raosudha89 has reached out to committee members to get their photos.

**Comment by stupid-2020** [comment]
@hao-fang @raosudha89  I will update the file once I have the information.  Thanks.

**Comment by stupid-2020** [comment]
@hao-fang @raosudha89  Would like to ask if the information is ready.  Thanks for your attention.

**Comment by raosudha89** [comment]
@stupid-2020  Sorry for the delay. We asked all committee members to give us their photo if they wanted to update their current photo on the website. I have added all the photos I received till now using this PR https://github.com/acl-org/acl-2020-virtual-conference/pull/283 

Once the PR is merged, please use them.

**Comment by hao-fang** [comment]
@stupid-2020 #283 is merged now. Please make the changes on https://github.com/acl-org/acl-2020-virtual-conference-sitedata/blob/master/committee.yml.
Thanks!

**Comment by stupid-2020** [comment]
> @stupid-2020 Sorry for the delay. We asked all committee members to give us their photo if they wanted to update their current photo on the website. I have added all the photos I received till now using this PR #283
> 
> Once the PR is merged, please use them.

Never mind

**Comment by stupid-2020** [comment]
> @stupid-2020 Sorry for the delay. We asked all committee members to give us their photo if they wanted to update their current photo on the website. I have added all the photos I received till now using this PR #283
> 
> Once the PR is merged, please use them.

Never mind.

**Comment by raosudha89** [comment]
@stupid-2020  I see https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/86 has been merged. But on the virtual website, I don't still see the updated photos. Has the sitedata been rebuilt? if not, can you do that?

**Comment by stupid-2020** [comment]
> @stupid-2020 I see [acl-org/acl-2020-virtual-conference-sitedata#86](https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/86) has been merged. But on the virtual website, I don't still see the updated photos. Has the sitedata been rebuilt? if not, can you do that?

@raosudha89 Sorry for late reply.  (I think we are working at different timezone)  I don't have the access to the virtual website you guys are working on.  Here is the output from my machine:

![image](https://user-images.githubusercontent.com/66775489/86071806-c1683b00-bab2-11ea-95a8-a93038cff5f1.png)

**Comment by hao-fang** [comment]
@stupid-2020 can you access virtual.acl2020.org? You should be able to login with the same account for RocketChat.

**Comment by stupid-2020** [comment]
> @stupid-2020 can you access virtual.acl2020.org? You should be able to login with the same account for RocketChat.

I can access the web but not the "console" to run "build freeze".

**Comment by hao-fang** [comment]
> > @stupid-2020 can you access virtual.acl2020.org? You should be able to login with the same account for RocketChat.
> 
> I can access the web but not the "console" to run "build freeze".

@stupid-2020 What do you mean by the "console"? The `make freeze` is executed in the Github Action.
