### ISSUE TITLE
Stress test the website

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#90]
- [x] Ask Cho and Sasha how they stress test ICLR
- [ ] Get a large number of volunteers to test the website a couple of days before the conference. 
- [ ] Think of ideas to stress test (based on Sasha's response below).

**Comment by raosudha89** [comment]
Response from Sasha:

The main website is pretty bullet proof as it is just HTML. The main stress testing was with chat, zoom, and videos. For rocket.chat it started out relatively slow so we had to scale to server with more memory (we used hosted so we just asked them to do it). Cho mostly ran the volunteer process, here is what he did: 

3. We noticed you had 500 volunteers.  What were their tasks?  And did you feel that was enough?

two main roles they served were:

(1) stress-test various platforms: for instance, i ran a couple of mock live QA sessions with more than 100 volunteers each to make sure people can access it from all corners of the world and that features were working as advertised. we found a number of issues, bugs and weird corner cases of slideslive, zoom, rocket.chat, etc. via these stress-test sessions.

(2) 24-hours helpdesk: because participants join the conference from all possible time zones (potentially except for a couple of time zones in the pacific,) we had to have a virtual helpdesk (#helpdesk channel on rocket.chat) run 24 hours. i tried my best to be present as much as i can, but it's simply impossible for a few people to be oncall the entire conference. i assigned at least 5 volunteers every 2-3 hour covering the entire conference duration (+ half a day before and half a day after.) they did an amazing job. 

in addition to those two which were done by all 500 volunteers, some volunteers helped us finalizing the web portal, scheduling social events under the guidance from the social chair (Adam White) and assisting live QA sessions.

it's really important to have a large group of volunteers from all over the world to ensure someone is available to assist authors and participants around the clock.

**Comment by hao-fang** [comment]
One thing to test is to use different browsers and report which one worked. Should be added to the Help page. #20

**Comment by stupid-2020** [comment]
Just wonder if we need the following testing:

- browser compatibility (browsers on both mobile, laptop/PC)
- simple load test (using [vegeta](https://github.com/tsenart/vegeta) or [ab](https://httpd.apache.org/docs/2.4/programs/ab.html))

**Comment by hao-fang** [comment]
@stupid-2020 thanks for the suggestions..
we didn't have time for this.... hope everything will be fine ... 🤞
