### ISSUE TITLE
Add more instructions to CONTRIBUTING-ACL2020.md

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#93]
I realize not everyone is familiar with the environment setup & workflow. It would be nice if someone can improve the `CONTRIBUTING-ACL2020.md`, e.g., adding some links to explain how to make a Pull Request etc.

**Comment by palooney** [comment]
I can work on this. How should I self-assign this task to me?

**Comment by hao-fang** [comment]
@palooney Sure!

Here are some more instructions about creating pull requests.
```
git pull
git checkout -b NEW_BRANCH_NAME
git add .
git commit -am "blah"
git push
```
You can then create the pull request on the GitHub. See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request.

**NOTE**: Since we are on a fork, we should choose the "base" to be "acl-org/acl-2020-virtual-conference", instead of the "Mini-Conf/Mini-Conf`.

**Comment by palooney** [comment]
Thanks! Are there any additional instructions we would like to include?

**Comment by hao-fang** [comment]
@palooney Probably explains how to do a PR that involves changes in `sitedata_acl2020`, which is a submodule.
Basically there are a few steps.
1. Make the changes in `sitedata_acl2020`
2. Create a PR in the `sitedata_acl2020` repo
3. After the PR in `sitedata_acl2020` is merged, bump the version in the main repo in your branch by `git pull`.
4. Create a PR in the main repo.

Would be useful to add the exact commands above. Let me know if you have any questions.

**Comment by palooney** [comment]
Sure! I have created a new PR for this.

**Comment by hao-fang** [comment]
@palooney I'm closing this for now to clean up our backlogs. But we may need to add more instructions about the `git submodule`. We can open a new issue then.
