### ISSUE TITLE
Fix the invalid images for regular paper pages

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#98]
**Number of Volunteers: 1**

Currently the images are missing for individual papers. We should just remove them for now.
![image](https://user-images.githubusercontent.com/9957482/84961331-dad3b500-b0b8-11ea-8d08-ba8321df5406.png)

We may be able to use https://github.com/Mini-Conf/image-extraction to extract a figure from the PDF, and use a default image if no figure is available.
But I don't know how it works. Can someone can quickly check whether the tool works and post results here?

**Comment by prabhat1081** [comment]
I tried out the tool in Google Colab with ACL2019 paper: https://arxiv.org/pdf/1901.05415.pdf. The tool does work for it.
![image](https://user-images.githubusercontent.com/7499972/84971544-d962b680-b0d1-11ea-9df9-737a1bf66f91.png)

**Comment by hao-fang** [comment]
@prabhat1081 This is cool! I can share all the PDFs with you. 

Do we need to pay to run this on Google Colab? We have ~800 papers. If so, do you have an estimate?

**Comment by prabhat1081** [comment]
The free version of Google Colab does have [usage limits](https://research.google.com/colaboratory/faq.html#usage-limits) but those have not been specified. I can try running and see what can be done if we hit any limits.

**Comment by hao-fang** [comment]
@prabhat1081 Cool! I'll send you the PDF via email. 
If possible, can you keep the receipt if it incurs any charges so we can reimburse you? Thanks!

**Comment by prabhat1081** [comment]
Ok thanks!

**Comment by hao-fang** [comment]
Potential issues:
* We may need to know how the mapping of paper IDs. It may use the ACL anthology ID, instead of the submission ID.
* We need to think about where to put the images. We can put it under `static/images/acl2020/papers`, but I'm not sure if this is too big for GitHub. Maybe we should directly upload it to a different place, e.g., AWS S3.
